/**
* NOTE: This file is auto-generated by scripts/prefetch_steam.ts
* DO NOT modify manually
*/
import type { Picture } from 'vite-imagetools';
import feXCHJXUggtA from '../assets/games/220.jpg?enhanced&format=webp'
import yTRrqqgxOOGC from '../assets/games/4000.jpg?enhanced&format=webp'
import vHXZFLNmIvJo from '../assets/games/2300.jpg?enhanced&format=webp'
import fHgkZoQNmThU from '../assets/games/20900.jpg?enhanced&format=webp'
import NLDnhJkzPnmg from '../assets/games/22300.jpg?enhanced&format=webp'
import ElETUfRdIYyg from '../assets/games/12210.jpg?enhanced&format=webp'
import YXiYDXaPWGpb from '../assets/games/17390.jpg?enhanced&format=webp'
import bJkATNYMEMNH from '../assets/games/29800.jpg?enhanced&format=webp'
import EpCJBBATrLjc from '../assets/games/6060.jpg?enhanced&format=webp'
import gfWYoZOMWtSN from '../assets/games/550.jpg?enhanced&format=webp'
import vWUjfcIuCsJL from '../assets/games/8190.jpg?enhanced&format=webp'
import ykEaUzLGJata from '../assets/games/57300.jpg?enhanced&format=webp'
import KwQNZioKNOSg from '../assets/games/8930.jpg?enhanced&format=webp'
import gJFMcudDxJPP from '../assets/games/40800.jpg?enhanced&format=webp'
import AIOSzoAuJyrK from '../assets/games/48190.jpg?enhanced&format=webp'
import KpesiCDcTYTb from '../assets/games/620.jpg?enhanced&format=webp'
import KHYQnJHfJTXU from '../assets/games/105600.jpg?enhanced&format=webp'
import azafRGNaxvah from '../assets/games/20920.jpg?enhanced&format=webp'
import mVzArTzHfdBX from '../assets/games/92100.jpg?enhanced&format=webp'
import aoyoUhlPnGrK from '../assets/games/22230.jpg?enhanced&format=webp'
import GkaRVePyTSvJ from '../assets/games/3830.jpg?enhanced&format=webp'
import BYjgYJPBVshd from '../assets/games/204030.jpg?enhanced&format=webp'
import TLSLSPJtAjsl from '../assets/games/207610.jpg?enhanced&format=webp'
import caXDMJlecaIT from '../assets/games/206440.jpg?enhanced&format=webp'
import wLkeUjQCYSSQ from '../assets/games/730.jpg?enhanced&format=webp'
import UuMOBgDiUoTb from '../assets/games/200260.jpg?enhanced&format=webp'
import WEvqvLnPihFz from '../assets/games/212680.jpg?enhanced&format=webp'
import NsrcdVKeNenY from '../assets/games/204360.jpg?enhanced&format=webp'
import WBVLbocfywWT from '../assets/games/49520.jpg?enhanced&format=webp'
import PzsONBgRItgm from '../assets/games/200710.jpg?enhanced&format=webp'
import AwYfzHkuOJYC from '../assets/games/205100.jpg?enhanced&format=webp'
import iLEdBGqQQXyU from '../assets/games/223470.jpg?enhanced&format=webp'
import hqxsuQNmdQXn from '../assets/games/55230.jpg?enhanced&format=webp'
import zRelLxrmttlL from '../assets/games/220700.jpg?enhanced&format=webp'
import WrfGYHvsovMW from '../assets/games/224540.jpg?enhanced&format=webp'
import DQmpKwvNyjaz from '../assets/games/200210.jpg?enhanced&format=webp'
import nNXAhwXSHMbt from '../assets/games/208090.jpg?enhanced&format=webp'
import yFptqqPdVGUO from '../assets/games/230410.jpg?enhanced&format=webp'
import tKImeiJWJNUk from '../assets/games/236390.jpg?enhanced&format=webp'
import AQXzALglaFeO from '../assets/games/39000.jpg?enhanced&format=webp'
import ZZtuoFsrUSRZ from '../assets/games/251670.jpg?enhanced&format=webp'
import MtggkGcAejgr from '../assets/games/221040.jpg?enhanced&format=webp'
import hTajnsFRaAIK from '../assets/games/203160.jpg?enhanced&format=webp'
import BIfQphdZTVkT from '../assets/games/47890.jpg?enhanced&format=webp'
import FjyVeQSRgfKQ from '../assets/games/233450.jpg?enhanced&format=webp'
import jDTxrJyinWyf from '../assets/games/233720.jpg?enhanced&format=webp'
import HlEYbUPclxMa from '../assets/games/224760.jpg?enhanced&format=webp'
import cJyvBNZSXnkK from '../assets/games/219740.jpg?enhanced&format=webp'
import sJqxcOjyuOcE from '../assets/games/322330.jpg?enhanced&format=webp'
import osBVAAuKqxMR from '../assets/games/234710.jpg?enhanced&format=webp'
import uorfXuuLQAGi from '../assets/games/72850.jpg?enhanced&format=webp'
import LKSyzWOjYgYX from '../assets/games/35720.jpg?enhanced&format=webp'
import YmOyFgRfOlmY from '../assets/games/242760.jpg?enhanced&format=webp'
import wPLDCkXEEBvz from '../assets/games/242860.jpg?enhanced&format=webp'
import JWXrceOIommR from '../assets/games/242920.jpg?enhanced&format=webp'
import ouORMVyvyByo from '../assets/games/244850.jpg?enhanced&format=webp'
import ORGoKdKyXfYX from '../assets/games/218620.jpg?enhanced&format=webp'
import ytejbJqgDPLX from '../assets/games/239820.jpg?enhanced&format=webp'
import xRZfVqdmoDYm from '../assets/games/252950.jpg?enhanced&format=webp'
import pjqKAelerfum from '../assets/games/242050.jpg?enhanced&format=webp'
import WKdCULbqUVWy from '../assets/games/219990.jpg?enhanced&format=webp'
import QdcMWoeuuaXu from '../assets/games/257750.jpg?enhanced&format=webp'
import XoxuncNuiucz from '../assets/games/221910.jpg?enhanced&format=webp'
import lSMFZiqBdjge from '../assets/games/209170.jpg?enhanced&format=webp'
import jSIqvycUpXtU from '../assets/games/264140.jpg?enhanced&format=webp'
import uqtZjyoLfOiP from '../assets/games/264710.jpg?enhanced&format=webp'
import YzwUpSPPitJO from '../assets/games/265930.jpg?enhanced&format=webp'
import SwxeWxyXFbpk from '../assets/games/266010.jpg?enhanced&format=webp'
import GnZmDVIYYncs from '../assets/games/211820.jpg?enhanced&format=webp'
import ThPMSvSzNbFV from '../assets/games/221100.jpg?enhanced&format=webp'
import alVMAUDUHtFz from '../assets/games/268910.jpg?enhanced&format=webp'
import pCjkxemRSjhW from '../assets/games/237870.jpg?enhanced&format=webp'
import AMoVKUiyEIeX from '../assets/games/225840.jpg?enhanced&format=webp'
import dmTaCNZkrbYR from '../assets/games/282140.jpg?enhanced&format=webp'
import WhSBXwGqbpIv from '../assets/games/287700.jpg?enhanced&format=webp'
import mxSZrcnPoMjs from '../assets/games/292030.jpg?enhanced&format=webp'
import zXENQzvQTEKU from '../assets/games/286160.jpg?enhanced&format=webp'
import ZERwTMPwQDVB from '../assets/games/289130.jpg?enhanced&format=webp'
import HXZgAWiNNltB from '../assets/games/238460.jpg?enhanced&format=webp'
import PBOkjooAtXIw from '../assets/games/299460.jpg?enhanced&format=webp'
import jTecaHXtiWYz from '../assets/games/243470.jpg?enhanced&format=webp'
import jevzMYxygPrt from '../assets/games/304930.jpg?enhanced&format=webp'
import kvjwNWphTzHU from '../assets/games/306020.jpg?enhanced&format=webp'
import SbwkONUiEbow from '../assets/games/9900.jpg?enhanced&format=webp'
import sCLBfXoXbIQm from '../assets/games/311690.jpg?enhanced&format=webp'
import YgTQmCxKbvQc from '../assets/games/206420.jpg?enhanced&format=webp'
import lpQmHgavmoOC from '../assets/games/314650.jpg?enhanced&format=webp'
import ShhxMWLwkRzv from '../assets/games/241930.jpg?enhanced&format=webp'
import mQfcAEZgqNdB from '../assets/games/322170.jpg?enhanced&format=webp'
import uWHMLWXNbuIv from '../assets/games/214490.jpg?enhanced&format=webp'
import KwCUEeuJxFSR from '../assets/games/238320.jpg?enhanced&format=webp'
import zkCiDGDQzcTG from '../assets/games/327140.jpg?enhanced&format=webp'
import sgBgZROrGgEz from '../assets/games/327890.jpg?enhanced&format=webp'
import BwhRoaiRvVSC from '../assets/games/261640.jpg?enhanced&format=webp'
import FuONkfUJrVcB from '../assets/games/211420.jpg?enhanced&format=webp'
import uZHAzYSZPCko from '../assets/games/330350.jpg?enhanced&format=webp'
import kzUgjKZSUDGB from '../assets/games/298110.jpg?enhanced&format=webp'
import yQfzNBHXxZyp from '../assets/games/305620.jpg?enhanced&format=webp'
import VLtBZSJbvoAD from '../assets/games/252490.jpg?enhanced&format=webp'
import dqGmKwLmiARb from '../assets/games/250900.jpg?enhanced&format=webp'
import TiUJrgcMgZzS from '../assets/games/319630.jpg?enhanced&format=webp'
import bCjhIvBTtvMm from '../assets/games/219150.jpg?enhanced&format=webp'
import LCTKVtPlOVaV from '../assets/games/274170.jpg?enhanced&format=webp'
import pZHhZDVOkzNu from '../assets/games/346010.jpg?enhanced&format=webp'
import jqYUrATslOHH from '../assets/games/346110.jpg?enhanced&format=webp'
import XgGkHbRbiMkz from '../assets/games/346900.jpg?enhanced&format=webp'
import lPndxnCBqhdF from '../assets/games/298630.jpg?enhanced&format=webp'
import giQgITWNpItf from '../assets/games/255710.jpg?enhanced&format=webp'
import zOmbBYoIuFOH from '../assets/games/306130.jpg?enhanced&format=webp'
import dXNqRfVmCzrC from '../assets/games/271590.jpg?enhanced&format=webp'
import bSzTJTDLDkRp from '../assets/games/359050.jpg?enhanced&format=webp'
import iNZcbirHMiuV from '../assets/games/363970.jpg?enhanced&format=webp'
import ijzgyzHyKpBr from '../assets/games/365720.jpg?enhanced&format=webp'
import vnfaWWQBtDvZ from '../assets/games/367520.jpg?enhanced&format=webp'
import QODAdRsYrrBs from '../assets/games/375950.jpg?enhanced&format=webp'
import OrAglTDazWtn from '../assets/games/377160.jpg?enhanced&format=webp'
import SkDRzMsUoyKN from '../assets/games/384190.jpg?enhanced&format=webp'
import zSrBSpLVZAUe from '../assets/games/391540.jpg?enhanced&format=webp'
import FUcWDuDLjYSt from '../assets/games/392110.jpg?enhanced&format=webp'
import zNetSMvhiOeZ from '../assets/games/393380.jpg?enhanced&format=webp'
import kumriSCDoMfo from '../assets/games/413150.jpg?enhanced&format=webp'
import RVaUllcZitch from '../assets/games/225540.jpg?enhanced&format=webp'
import aIloWYcwByLw from '../assets/games/417860.jpg?enhanced&format=webp'
import MopdzPuUuEOc from '../assets/games/208650.jpg?enhanced&format=webp'
import MmkrROynoahu from '../assets/games/420530.jpg?enhanced&format=webp'
import oTOSDICIrRLf from '../assets/games/391220.jpg?enhanced&format=webp'
import kphZJvWVWYOM from '../assets/games/427520.jpg?enhanced&format=webp'
import xlAiYmZFsaiu from '../assets/games/210970.jpg?enhanced&format=webp'
import hYtVUcDsveSd from '../assets/games/359550.jpg?enhanced&format=webp'
import eqyDtarBgJDM from '../assets/games/623990.jpg?enhanced&format=webp'
import XoiGiHzbWFtr from '../assets/games/239140.jpg?enhanced&format=webp'
import VPVMrIBUpBGN from '../assets/games/431960.jpg?enhanced&format=webp'
import pjrEUveUcnCP from '../assets/games/434260.jpg?enhanced&format=webp'
import qmOTzxfkkPJZ from '../assets/games/434570.jpg?enhanced&format=webp'
import onptFAKEsiKI from '../assets/games/374320.jpg?enhanced&format=webp'
import pQBzMIAqhZAm from '../assets/games/275850.jpg?enhanced&format=webp'
import SMmWwgzookcy from '../assets/games/457550.jpg?enhanced&format=webp'
import JHeJRSfVjfhK from '../assets/games/403640.jpg?enhanced&format=webp'
import AsSffuVxrDrq from '../assets/games/501300.jpg?enhanced&format=webp'
import ZYTeWSSqKFbR from '../assets/games/518790.jpg?enhanced&format=webp'
import xSbQVOqjbJYR from '../assets/games/289070.jpg?enhanced&format=webp'
import tOYPgCcQZlen from '../assets/games/534380.jpg?enhanced&format=webp'
import TmpVSqnaWKXF from '../assets/games/546560.jpg?enhanced&format=webp'
import JdPytqNBjGFX from '../assets/games/548430.jpg?enhanced&format=webp'
import knZOQIhkwCgu from '../assets/games/489830.jpg?enhanced&format=webp'
import dfdQgUUsQxJE from '../assets/games/553850.jpg?enhanced&format=webp'
import mhilTzXPpvLF from '../assets/games/555160.jpg?enhanced&format=webp'
import SGVAlvFAtjTg from '../assets/games/447040.jpg?enhanced&format=webp'
import HrMzSiSATViv from '../assets/games/460920.jpg?enhanced&format=webp'
import JnAUFVIvxyma from '../assets/games/564710.jpg?enhanced&format=webp'
import bFAkoVABrVoM from '../assets/games/578080.jpg?enhanced&format=webp'
import NuMhqAPBrUCY from '../assets/games/578620.jpg?enhanced&format=webp'
import CheQRYqOUjXf from '../assets/games/582660.jpg?enhanced&format=webp'
import IhfzrQIPSYTd from '../assets/games/588650.jpg?enhanced&format=webp'
import sNBzAZDhDNFm from '../assets/games/460930.jpg?enhanced&format=webp'
import xKeviVyJOnvQ from '../assets/games/611670.jpg?enhanced&format=webp'
import ELULkMhTEKeR from '../assets/games/617830.jpg?enhanced&format=webp'
import SoXenxDqyNVx from '../assets/games/619910.jpg?enhanced&format=webp'
import hnRpYNPbHtSB from '../assets/games/620980.jpg?enhanced&format=webp'
import wEELydkWEECZ from '../assets/games/629730.jpg?enhanced&format=webp'
import hfTPGaUTviKe from '../assets/games/632360.jpg?enhanced&format=webp'
import CEJdkcZugncn from '../assets/games/671860.jpg?enhanced&format=webp'
import XnfQefCDfhhN from '../assets/games/683320.jpg?enhanced&format=webp'
import FQCsBrwMaxtt from '../assets/games/414340.jpg?enhanced&format=webp'
import empsYZEITWJX from '../assets/games/240720.jpg?enhanced&format=webp'
import OzQMlEgIMquW from '../assets/games/582160.jpg?enhanced&format=webp'
import UbVPuOhmaVVy from '../assets/games/739630.jpg?enhanced&format=webp'
import LNoxRQcqdQax from '../assets/games/418370.jpg?enhanced&format=webp'
import JnNVHCCDiXfg from '../assets/games/812140.jpg?enhanced&format=webp'
import oeKPbLBRgBtC from '../assets/games/552500.jpg?enhanced&format=webp'
import qqEaHAlCqFBX from '../assets/games/750920.jpg?enhanced&format=webp'
import VRoLXIZurhJe from '../assets/games/858260.jpg?enhanced&format=webp'
import CPqIzuAmLKWD from '../assets/games/892970.jpg?enhanced&format=webp'
import kvehtHReswzX from '../assets/games/899770.jpg?enhanced&format=webp'
import aatlfALxmwIf from '../assets/games/814380.jpg?enhanced&format=webp'
import dmIyzAaPThAV from '../assets/games/993090.jpg?enhanced&format=webp'
import vFpmXcypDmpN from '../assets/games/1063730.jpg?enhanced&format=webp'
import txcrpyKhzEMw from '../assets/games/1079800.jpg?enhanced&format=webp'
import sgxqSQTNwvMR from '../assets/games/1091500.jpg?enhanced&format=webp'
import EkLqxtREvccc from '../assets/games/1145360.jpg?enhanced&format=webp'
import FgbGJyGljExX from '../assets/games/1151640.jpg?enhanced&format=webp'
import zpiSaHdNiKxW from '../assets/games/1172620.jpg?enhanced&format=webp'
import sOVbapaZrzNU from '../assets/games/1174180.jpg?enhanced&format=webp'
import uTqkwGiSusCD from '../assets/games/397540.jpg?enhanced&format=webp'
import kWXACwoyykur from '../assets/games/582010.jpg?enhanced&format=webp'
import zTIBzzQKDFeP from '../assets/games/1222670.jpg?enhanced&format=webp'
import KMuhyhjgycyc from '../assets/games/1238840.jpg?enhanced&format=webp'
import hzdLnzZefkvj from '../assets/games/1237950.jpg?enhanced&format=webp'
import kcJMUaaegvHj from '../assets/games/1245620.jpg?enhanced&format=webp'
import cIGysLpaodxH from '../assets/games/1151340.jpg?enhanced&format=webp'
import CnXzojxEGHGm from '../assets/games/1349230.jpg?enhanced&format=webp'
import TAGiZQPElJua from '../assets/games/1403370.jpg?enhanced&format=webp'
import EqKxvAOEzZtx from '../assets/games/1454400.jpg?enhanced&format=webp'
import SfpzvjvCvWpV from '../assets/games/1468260.jpg?enhanced&format=webp'
import AuvXgYGfrzYN from '../assets/games/1475810.jpg?enhanced&format=webp'
import WdgOBVQanvTw from '../assets/games/1476970.jpg?enhanced&format=webp'
import wmKdIZuIpXbM from '../assets/games/1562420.jpg?enhanced&format=webp'
import WPTkNnkSXnZo from '../assets/games/1593500.jpg?enhanced&format=webp'
import urXPOuqdOvNR from '../assets/games/1599340.jpg?enhanced&format=webp'
import FaUeeuFbLGue from '../assets/games/1353300.jpg?enhanced&format=webp'
import trbQKZbjZKYA from '../assets/games/1240440.jpg?enhanced&format=webp'
import aUTRFSmfDNfc from '../assets/games/1794680.jpg?enhanced&format=webp'
import fkSssrcSVVdW from '../assets/games/1446780.jpg?enhanced&format=webp'
import suUvucsiypbR from '../assets/games/1817070.jpg?enhanced&format=webp'
import JMEzBklmWRBr from '../assets/games/1943950.jpg?enhanced&format=webp'
import oaQJDHjfwllg from '../assets/games/1966720.jpg?enhanced&format=webp'
import ZKRbSyIhzEHe from '../assets/games/1999360.jpg?enhanced&format=webp'
import KdNQJvnJrNCX from '../assets/games/2012840.jpg?enhanced&format=webp'
import sJSFnskzYbBz from '../assets/games/1286680.jpg?enhanced&format=webp'
import vPMquSlWzGEb from '../assets/games/1313140.jpg?enhanced&format=webp'
import VowGMPzLyBxv from '../assets/games/990080.jpg?enhanced&format=webp'
import KxXuNWadnbLw from '../assets/games/2399830.jpg?enhanced&format=webp'
import WkKPMpGKcWtl from '../assets/games/2420110.jpg?enhanced&format=webp'
import GvISgYbSDOad from '../assets/games/1086940.jpg?enhanced&format=webp'
import BekwGUDRCReU from '../assets/games/1361210.jpg?enhanced&format=webp'
import gwpOWhlZWpYq from '../assets/games/2840770.jpg?enhanced&format=webp'
import xYAEqbduQcEV from '../assets/games/2561580.jpg?enhanced&format=webp'
import nLaAYAMgmwjR from '../assets/games/440.jpg?enhanced&format=webp'
import LYiSRKWmlyVl from '../assets/games/570.jpg?enhanced&format=webp'

const gameHeroDict: Record<string, Picture> = {
	[220]: feXCHJXUggtA,
	[4000]: yTRrqqgxOOGC,
	[2300]: vHXZFLNmIvJo,
	[20900]: fHgkZoQNmThU,
	[22300]: NLDnhJkzPnmg,
	[12210]: ElETUfRdIYyg,
	[17390]: YXiYDXaPWGpb,
	[29800]: bJkATNYMEMNH,
	[6060]: EpCJBBATrLjc,
	[550]: gfWYoZOMWtSN,
	[8190]: vWUjfcIuCsJL,
	[57300]: ykEaUzLGJata,
	[8930]: KwQNZioKNOSg,
	[40800]: gJFMcudDxJPP,
	[48190]: AIOSzoAuJyrK,
	[620]: KpesiCDcTYTb,
	[105600]: KHYQnJHfJTXU,
	[20920]: azafRGNaxvah,
	[92100]: mVzArTzHfdBX,
	[22230]: aoyoUhlPnGrK,
	[3830]: GkaRVePyTSvJ,
	[204030]: BYjgYJPBVshd,
	[207610]: TLSLSPJtAjsl,
	[206440]: caXDMJlecaIT,
	[730]: wLkeUjQCYSSQ,
	[200260]: UuMOBgDiUoTb,
	[212680]: WEvqvLnPihFz,
	[204360]: NsrcdVKeNenY,
	[49520]: WBVLbocfywWT,
	[200710]: PzsONBgRItgm,
	[205100]: AwYfzHkuOJYC,
	[223470]: iLEdBGqQQXyU,
	[55230]: hqxsuQNmdQXn,
	[220700]: zRelLxrmttlL,
	[224540]: WrfGYHvsovMW,
	[200210]: DQmpKwvNyjaz,
	[208090]: nNXAhwXSHMbt,
	[230410]: yFptqqPdVGUO,
	[236390]: tKImeiJWJNUk,
	[39000]: AQXzALglaFeO,
	[251670]: ZZtuoFsrUSRZ,
	[221040]: MtggkGcAejgr,
	[203160]: hTajnsFRaAIK,
	[47890]: BIfQphdZTVkT,
	[233450]: FjyVeQSRgfKQ,
	[233720]: jDTxrJyinWyf,
	[224760]: HlEYbUPclxMa,
	[219740]: cJyvBNZSXnkK,
	[322330]: sJqxcOjyuOcE,
	[234710]: osBVAAuKqxMR,
	[72850]: uorfXuuLQAGi,
	[35720]: LKSyzWOjYgYX,
	[242760]: YmOyFgRfOlmY,
	[242860]: wPLDCkXEEBvz,
	[242920]: JWXrceOIommR,
	[244850]: ouORMVyvyByo,
	[218620]: ORGoKdKyXfYX,
	[239820]: ytejbJqgDPLX,
	[252950]: xRZfVqdmoDYm,
	[242050]: pjqKAelerfum,
	[219990]: WKdCULbqUVWy,
	[257750]: QdcMWoeuuaXu,
	[221910]: XoxuncNuiucz,
	[209170]: lSMFZiqBdjge,
	[264140]: jSIqvycUpXtU,
	[264710]: uqtZjyoLfOiP,
	[265930]: YzwUpSPPitJO,
	[266010]: SwxeWxyXFbpk,
	[211820]: GnZmDVIYYncs,
	[221100]: ThPMSvSzNbFV,
	[268910]: alVMAUDUHtFz,
	[237870]: pCjkxemRSjhW,
	[225840]: AMoVKUiyEIeX,
	[282140]: dmTaCNZkrbYR,
	[287700]: WhSBXwGqbpIv,
	[292030]: mxSZrcnPoMjs,
	[286160]: zXENQzvQTEKU,
	[289130]: ZERwTMPwQDVB,
	[238460]: HXZgAWiNNltB,
	[299460]: PBOkjooAtXIw,
	[243470]: jTecaHXtiWYz,
	[304930]: jevzMYxygPrt,
	[306020]: kvjwNWphTzHU,
	[9900]: SbwkONUiEbow,
	[311690]: sCLBfXoXbIQm,
	[206420]: YgTQmCxKbvQc,
	[314650]: lpQmHgavmoOC,
	[241930]: ShhxMWLwkRzv,
	[322170]: mQfcAEZgqNdB,
	[214490]: uWHMLWXNbuIv,
	[238320]: KwCUEeuJxFSR,
	[327140]: zkCiDGDQzcTG,
	[327890]: sgBgZROrGgEz,
	[261640]: BwhRoaiRvVSC,
	[211420]: FuONkfUJrVcB,
	[330350]: uZHAzYSZPCko,
	[298110]: kzUgjKZSUDGB,
	[305620]: yQfzNBHXxZyp,
	[252490]: VLtBZSJbvoAD,
	[250900]: dqGmKwLmiARb,
	[319630]: TiUJrgcMgZzS,
	[219150]: bCjhIvBTtvMm,
	[274170]: LCTKVtPlOVaV,
	[346010]: pZHhZDVOkzNu,
	[346110]: jqYUrATslOHH,
	[346900]: XgGkHbRbiMkz,
	[298630]: lPndxnCBqhdF,
	[255710]: giQgITWNpItf,
	[306130]: zOmbBYoIuFOH,
	[271590]: dXNqRfVmCzrC,
	[359050]: bSzTJTDLDkRp,
	[363970]: iNZcbirHMiuV,
	[365720]: ijzgyzHyKpBr,
	[367520]: vnfaWWQBtDvZ,
	[375950]: QODAdRsYrrBs,
	[377160]: OrAglTDazWtn,
	[384190]: SkDRzMsUoyKN,
	[391540]: zSrBSpLVZAUe,
	[392110]: FUcWDuDLjYSt,
	[393380]: zNetSMvhiOeZ,
	[413150]: kumriSCDoMfo,
	[225540]: RVaUllcZitch,
	[417860]: aIloWYcwByLw,
	[208650]: MopdzPuUuEOc,
	[420530]: MmkrROynoahu,
	[391220]: oTOSDICIrRLf,
	[427520]: kphZJvWVWYOM,
	[210970]: xlAiYmZFsaiu,
	[359550]: hYtVUcDsveSd,
	[623990]: eqyDtarBgJDM,
	[239140]: XoiGiHzbWFtr,
	[431960]: VPVMrIBUpBGN,
	[434260]: pjrEUveUcnCP,
	[434570]: qmOTzxfkkPJZ,
	[374320]: onptFAKEsiKI,
	[275850]: pQBzMIAqhZAm,
	[457550]: SMmWwgzookcy,
	[403640]: JHeJRSfVjfhK,
	[501300]: AsSffuVxrDrq,
	[518790]: ZYTeWSSqKFbR,
	[289070]: xSbQVOqjbJYR,
	[534380]: tOYPgCcQZlen,
	[546560]: TmpVSqnaWKXF,
	[548430]: JdPytqNBjGFX,
	[489830]: knZOQIhkwCgu,
	[553850]: dfdQgUUsQxJE,
	[555160]: mhilTzXPpvLF,
	[447040]: SGVAlvFAtjTg,
	[460920]: HrMzSiSATViv,
	[564710]: JnAUFVIvxyma,
	[578080]: bFAkoVABrVoM,
	[578620]: NuMhqAPBrUCY,
	[582660]: CheQRYqOUjXf,
	[588650]: IhfzrQIPSYTd,
	[460930]: sNBzAZDhDNFm,
	[611670]: xKeviVyJOnvQ,
	[617830]: ELULkMhTEKeR,
	[619910]: SoXenxDqyNVx,
	[620980]: hnRpYNPbHtSB,
	[629730]: wEELydkWEECZ,
	[632360]: hfTPGaUTviKe,
	[671860]: CEJdkcZugncn,
	[683320]: XnfQefCDfhhN,
	[414340]: FQCsBrwMaxtt,
	[240720]: empsYZEITWJX,
	[582160]: OzQMlEgIMquW,
	[739630]: UbVPuOhmaVVy,
	[418370]: LNoxRQcqdQax,
	[812140]: JnNVHCCDiXfg,
	[552500]: oeKPbLBRgBtC,
	[750920]: qqEaHAlCqFBX,
	[858260]: VRoLXIZurhJe,
	[892970]: CPqIzuAmLKWD,
	[899770]: kvehtHReswzX,
	[814380]: aatlfALxmwIf,
	[993090]: dmIyzAaPThAV,
	[1063730]: vFpmXcypDmpN,
	[1079800]: txcrpyKhzEMw,
	[1091500]: sgxqSQTNwvMR,
	[1145360]: EkLqxtREvccc,
	[1151640]: FgbGJyGljExX,
	[1172620]: zpiSaHdNiKxW,
	[1174180]: sOVbapaZrzNU,
	[397540]: uTqkwGiSusCD,
	[582010]: kWXACwoyykur,
	[1222670]: zTIBzzQKDFeP,
	[1238840]: KMuhyhjgycyc,
	[1237950]: hzdLnzZefkvj,
	[1245620]: kcJMUaaegvHj,
	[1151340]: cIGysLpaodxH,
	[1349230]: CnXzojxEGHGm,
	[1403370]: TAGiZQPElJua,
	[1454400]: EqKxvAOEzZtx,
	[1468260]: SfpzvjvCvWpV,
	[1475810]: AuvXgYGfrzYN,
	[1476970]: WdgOBVQanvTw,
	[1562420]: wmKdIZuIpXbM,
	[1593500]: WPTkNnkSXnZo,
	[1599340]: urXPOuqdOvNR,
	[1353300]: FaUeeuFbLGue,
	[1240440]: trbQKZbjZKYA,
	[1794680]: aUTRFSmfDNfc,
	[1446780]: fkSssrcSVVdW,
	[1817070]: suUvucsiypbR,
	[1943950]: JMEzBklmWRBr,
	[1966720]: oaQJDHjfwllg,
	[1999360]: ZKRbSyIhzEHe,
	[2012840]: KdNQJvnJrNCX,
	[1286680]: sJSFnskzYbBz,
	[1313140]: vPMquSlWzGEb,
	[990080]: VowGMPzLyBxv,
	[2399830]: KxXuNWadnbLw,
	[2420110]: WkKPMpGKcWtl,
	[1086940]: GvISgYbSDOad,
	[1361210]: BekwGUDRCReU,
	[2840770]: gwpOWhlZWpYq,
	[2561580]: xYAEqbduQcEV,
	[440]: nLaAYAMgmwjR,
	[570]: LYiSRKWmlyVl
};

const getGameHero = (appId: number) => {
	if (gameHeroDict[appId]) {
		return gameHeroDict[appId]
	}
	return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`
}
export { getGameHero }
import XRGtguRtBwrQ from '../assets/icons/220.jpg?enhanced&format=webp'
import LOQLGLIqxUVo from '../assets/icons/4000.jpg?enhanced&format=webp'
import eLcJXuTUHtIC from '../assets/icons/2300.jpg?enhanced&format=webp'
import vWeIXMgkAssZ from '../assets/icons/20900.jpg?enhanced&format=webp'
import SlFdHXMCBNxc from '../assets/icons/22300.jpg?enhanced&format=webp'
import XVtWUETEDObn from '../assets/icons/12210.jpg?enhanced&format=webp'
import hfQejKYcgPMd from '../assets/icons/17390.jpg?enhanced&format=webp'
import PmTyfjTdbgpz from '../assets/icons/29800.jpg?enhanced&format=webp'
import dBUWGphdawjX from '../assets/icons/6060.jpg?enhanced&format=webp'
import QiBhNyIYrZiC from '../assets/icons/550.jpg?enhanced&format=webp'
import obUseRwrwdav from '../assets/icons/8190.jpg?enhanced&format=webp'
import cswdFeiEQPbT from '../assets/icons/57300.jpg?enhanced&format=webp'
import XuIvfzzUVosC from '../assets/icons/8930.jpg?enhanced&format=webp'
import TVTynaVSXKLM from '../assets/icons/40800.jpg?enhanced&format=webp'
import UNhYiDFBwbfv from '../assets/icons/48190.jpg?enhanced&format=webp'
import weYVMdIPeUmM from '../assets/icons/620.jpg?enhanced&format=webp'
import yJEoRDAlorAY from '../assets/icons/105600.jpg?enhanced&format=webp'
import avmSxROinXaJ from '../assets/icons/20920.jpg?enhanced&format=webp'
import DBXpXQlpLgMF from '../assets/icons/92100.jpg?enhanced&format=webp'
import nVQhlsUEpGTi from '../assets/icons/22230.jpg?enhanced&format=webp'
import nKDSOmxbPUvM from '../assets/icons/3830.jpg?enhanced&format=webp'
import KQEclFdRnCcJ from '../assets/icons/204030.jpg?enhanced&format=webp'
import fvUkgXNgbbzN from '../assets/icons/207610.jpg?enhanced&format=webp'
import KwOfvXmNoakH from '../assets/icons/206440.jpg?enhanced&format=webp'
import SwBgXiwmvmCx from '../assets/icons/730.jpg?enhanced&format=webp'
import iRKywigODmec from '../assets/icons/200260.jpg?enhanced&format=webp'
import aoopaSrQKvSz from '../assets/icons/212680.jpg?enhanced&format=webp'
import JddgUHtFIeVe from '../assets/icons/204360.jpg?enhanced&format=webp'
import LEKQTbQEswWt from '../assets/icons/49520.jpg?enhanced&format=webp'
import ooqtdHFXGUcE from '../assets/icons/200710.jpg?enhanced&format=webp'
import MFavjpUmKMcf from '../assets/icons/205100.jpg?enhanced&format=webp'
import pAEkOErIahOC from '../assets/icons/223470.jpg?enhanced&format=webp'
import nzihZpDSDjEa from '../assets/icons/55230.jpg?enhanced&format=webp'
import LIKOQCLNpGsE from '../assets/icons/220700.jpg?enhanced&format=webp'
import TAlOHnbslgAC from '../assets/icons/224540.jpg?enhanced&format=webp'
import prMtsKEWsoGt from '../assets/icons/200210.jpg?enhanced&format=webp'
import BbCibuYrPjVf from '../assets/icons/208090.jpg?enhanced&format=webp'
import lRpWCUmhUHfg from '../assets/icons/230410.jpg?enhanced&format=webp'
import pfqVKHUmITKT from '../assets/icons/236390.jpg?enhanced&format=webp'
import OvQCHUpSLkEu from '../assets/icons/39000.jpg?enhanced&format=webp'
import YrPZQbpRSXRF from '../assets/icons/251670.jpg?enhanced&format=webp'
import ZDmMOYJYkcWj from '../assets/icons/221040.jpg?enhanced&format=webp'
import JElAfXclWXwo from '../assets/icons/203160.jpg?enhanced&format=webp'
import JKVORlBhnDeG from '../assets/icons/47890.jpg?enhanced&format=webp'
import IKnIDlKJkBUS from '../assets/icons/233450.jpg?enhanced&format=webp'
import tIezTwVVyXai from '../assets/icons/233720.jpg?enhanced&format=webp'
import ifzYSWUoJQvM from '../assets/icons/224760.jpg?enhanced&format=webp'
import xIfHembYFVVx from '../assets/icons/219740.jpg?enhanced&format=webp'
import iwVXwpGVwydi from '../assets/icons/322330.jpg?enhanced&format=webp'
import BHeyeiqZptEn from '../assets/icons/234710.jpg?enhanced&format=webp'
import BAjhuzVcOLct from '../assets/icons/72850.jpg?enhanced&format=webp'
import yIfUnbBvSPhT from '../assets/icons/35720.jpg?enhanced&format=webp'
import WlIGwTafLJmz from '../assets/icons/242760.jpg?enhanced&format=webp'
import jyLbVbuuRHJn from '../assets/icons/242860.jpg?enhanced&format=webp'
import wEOqsnaBTOlP from '../assets/icons/242920.jpg?enhanced&format=webp'
import frvjpKkEVBeY from '../assets/icons/244850.jpg?enhanced&format=webp'
import bnxwbFtECEdG from '../assets/icons/218620.jpg?enhanced&format=webp'
import MxFEHaKgMRLC from '../assets/icons/239820.jpg?enhanced&format=webp'
import AEmTZWlVdRxU from '../assets/icons/252950.jpg?enhanced&format=webp'
import rOCzRnJjofzB from '../assets/icons/242050.jpg?enhanced&format=webp'
import vgjRNLZNKNgq from '../assets/icons/219990.jpg?enhanced&format=webp'
import RGxuLJqrLJxs from '../assets/icons/257750.jpg?enhanced&format=webp'
import RtEueGxqCtDc from '../assets/icons/221910.jpg?enhanced&format=webp'
import GmmZRCWDeQjF from '../assets/icons/209170.jpg?enhanced&format=webp'
import ouctyFHANddj from '../assets/icons/264140.jpg?enhanced&format=webp'
import ToKouhmbjMod from '../assets/icons/264710.jpg?enhanced&format=webp'
import iqMowKDtYMnx from '../assets/icons/265930.jpg?enhanced&format=webp'
import ABZSJbgSSPhK from '../assets/icons/266010.jpg?enhanced&format=webp'
import PTPSoOFcMtmq from '../assets/icons/211820.jpg?enhanced&format=webp'
import wnDDYTgFUVGY from '../assets/icons/221100.jpg?enhanced&format=webp'
import iNhVmJAtuFNg from '../assets/icons/268910.jpg?enhanced&format=webp'
import VfTTfWZYqXbp from '../assets/icons/237870.jpg?enhanced&format=webp'
import JrcKVFrJcTZL from '../assets/icons/225840.jpg?enhanced&format=webp'
import MKFEAvuZiaqR from '../assets/icons/282140.jpg?enhanced&format=webp'
import ZQrPNFbsSZkE from '../assets/icons/287700.jpg?enhanced&format=webp'
import pTnoQJIbWJAt from '../assets/icons/292030.jpg?enhanced&format=webp'
import HgSzsOzGWgil from '../assets/icons/286160.jpg?enhanced&format=webp'
import JWGTzvkLFVzm from '../assets/icons/289130.jpg?enhanced&format=webp'
import hIXvGcFNAuoS from '../assets/icons/238460.jpg?enhanced&format=webp'
import FIRxFiyTAQGQ from '../assets/icons/299460.jpg?enhanced&format=webp'
import gNLzrKWfvOFH from '../assets/icons/243470.jpg?enhanced&format=webp'
import ndrAPwhXaHcv from '../assets/icons/304930.jpg?enhanced&format=webp'
import VXPFrsGpyULk from '../assets/icons/306020.jpg?enhanced&format=webp'
import CpCkmxflIlzV from '../assets/icons/9900.jpg?enhanced&format=webp'
import cUAgKlsfRiqv from '../assets/icons/311690.jpg?enhanced&format=webp'
import NaQBzltzRYfO from '../assets/icons/206420.jpg?enhanced&format=webp'
import hYsFILLWkeTV from '../assets/icons/314650.jpg?enhanced&format=webp'
import hZuKeAzILZWs from '../assets/icons/241930.jpg?enhanced&format=webp'
import jztBXWuvCkIQ from '../assets/icons/322170.jpg?enhanced&format=webp'
import ROkmpPmJsBGs from '../assets/icons/214490.jpg?enhanced&format=webp'
import UTrzWgbustuI from '../assets/icons/238320.jpg?enhanced&format=webp'
import BpjGZHLpqDux from '../assets/icons/327140.jpg?enhanced&format=webp'
import XrmGsXuOuLdN from '../assets/icons/327890.jpg?enhanced&format=webp'
import nohHmznTCkfq from '../assets/icons/261640.jpg?enhanced&format=webp'
import iujYjofqgGMc from '../assets/icons/211420.jpg?enhanced&format=webp'
import dxDWPTisrlJU from '../assets/icons/330350.jpg?enhanced&format=webp'
import FePbPrTKBHAq from '../assets/icons/298110.jpg?enhanced&format=webp'
import PqzkMBWboJen from '../assets/icons/305620.jpg?enhanced&format=webp'
import XFlQAZXZrfWT from '../assets/icons/252490.jpg?enhanced&format=webp'
import oObaPGlvafHL from '../assets/icons/250900.jpg?enhanced&format=webp'
import irDGuuBiULGG from '../assets/icons/319630.jpg?enhanced&format=webp'
import qugQMxChRsae from '../assets/icons/219150.jpg?enhanced&format=webp'
import bohjxjdKxpOa from '../assets/icons/274170.jpg?enhanced&format=webp'
import kWSuvVgBgqOJ from '../assets/icons/346010.jpg?enhanced&format=webp'
import scaKUgYezrRI from '../assets/icons/346110.jpg?enhanced&format=webp'
import KZxIdPgQnCNl from '../assets/icons/346900.jpg?enhanced&format=webp'
import jzuWSuFxIYfx from '../assets/icons/298630.jpg?enhanced&format=webp'
import lmbApYLBwIsR from '../assets/icons/255710.jpg?enhanced&format=webp'
import cNCjEsQBkozW from '../assets/icons/306130.jpg?enhanced&format=webp'
import BlNOSuPYpzPN from '../assets/icons/271590.jpg?enhanced&format=webp'
import zKrPxcZzIuMO from '../assets/icons/359050.jpg?enhanced&format=webp'
import ORhtOSnJAXVa from '../assets/icons/363970.jpg?enhanced&format=webp'
import dxQYgQWJduIb from '../assets/icons/365720.jpg?enhanced&format=webp'
import ZmSNTBGEtevV from '../assets/icons/367520.jpg?enhanced&format=webp'
import aqMbCVkcPxrH from '../assets/icons/375950.jpg?enhanced&format=webp'
import HvxQXdZDnqkQ from '../assets/icons/377160.jpg?enhanced&format=webp'
import ENhsdxbpOzpY from '../assets/icons/384190.jpg?enhanced&format=webp'
import OjjZnzpyRZog from '../assets/icons/391540.jpg?enhanced&format=webp'
import PvLCWcvnWPgO from '../assets/icons/392110.jpg?enhanced&format=webp'
import mPIXsNVNEOsT from '../assets/icons/393380.jpg?enhanced&format=webp'
import wsiAWBPDuWfK from '../assets/icons/413150.jpg?enhanced&format=webp'
import ZUgiFuFGTNvw from '../assets/icons/225540.jpg?enhanced&format=webp'
import hslxVIRvShXW from '../assets/icons/417860.jpg?enhanced&format=webp'
import IQCrDylhawOZ from '../assets/icons/208650.jpg?enhanced&format=webp'
import gEuUymFRcXvU from '../assets/icons/420530.jpg?enhanced&format=webp'
import uiobcqVKKfGL from '../assets/icons/391220.jpg?enhanced&format=webp'
import mnUEkfExkPbZ from '../assets/icons/427520.jpg?enhanced&format=webp'
import pVhzDcRwQPhg from '../assets/icons/210970.jpg?enhanced&format=webp'
import sdkTJXklaGVt from '../assets/icons/359550.jpg?enhanced&format=webp'
import fDlNRifObtch from '../assets/icons/623990.jpg?enhanced&format=webp'
import zbBToXZCfMcF from '../assets/icons/239140.jpg?enhanced&format=webp'
import gLMvGglyeUKh from '../assets/icons/431960.jpg?enhanced&format=webp'
import xbbmowSseqqh from '../assets/icons/434260.jpg?enhanced&format=webp'
import rRpohOSJgGGe from '../assets/icons/434570.jpg?enhanced&format=webp'
import napqQPuDlHOy from '../assets/icons/374320.jpg?enhanced&format=webp'
import WEZBxlQKagoS from '../assets/icons/275850.jpg?enhanced&format=webp'
import WGiXFyfJxTwl from '../assets/icons/457550.jpg?enhanced&format=webp'
import tLLiaDLqTYAT from '../assets/icons/403640.jpg?enhanced&format=webp'
import THubxvzuWxAw from '../assets/icons/501300.jpg?enhanced&format=webp'
import TotFSbDBYMrZ from '../assets/icons/518790.jpg?enhanced&format=webp'
import ugzAYSaafZyH from '../assets/icons/289070.jpg?enhanced&format=webp'
import XkrqbPahEdFY from '../assets/icons/534380.jpg?enhanced&format=webp'
import FuoxEHhRnzDj from '../assets/icons/546560.jpg?enhanced&format=webp'
import qBQjyhwntfBY from '../assets/icons/548430.jpg?enhanced&format=webp'
import lxSOQCRCFWhg from '../assets/icons/489830.jpg?enhanced&format=webp'
import evaeyPsLZnjP from '../assets/icons/553850.jpg?enhanced&format=webp'
import YoFwpAczcAxs from '../assets/icons/555160.jpg?enhanced&format=webp'
import lpmQIYFxyDvP from '../assets/icons/447040.jpg?enhanced&format=webp'
import tmigoPvrGWAA from '../assets/icons/460920.jpg?enhanced&format=webp'
import KCUIDGljxWPA from '../assets/icons/564710.jpg?enhanced&format=webp'
import hXDkCEnGJUMR from '../assets/icons/578080.jpg?enhanced&format=webp'
import VXYqDvvSWfoC from '../assets/icons/578620.jpg?enhanced&format=webp'
import fMprujRCEZgP from '../assets/icons/582660.jpg?enhanced&format=webp'
import ITzhnwhOhGjU from '../assets/icons/588650.jpg?enhanced&format=webp'
import qNUzoxFDdins from '../assets/icons/460930.jpg?enhanced&format=webp'
import emlbeuGjsWdc from '../assets/icons/611670.jpg?enhanced&format=webp'
import hSeEiBJeTlRL from '../assets/icons/617830.jpg?enhanced&format=webp'
import uzTTMHoqZZVl from '../assets/icons/619910.jpg?enhanced&format=webp'
import kUaAiQmOTQzF from '../assets/icons/620980.jpg?enhanced&format=webp'
import FEUhDZaZmmru from '../assets/icons/629730.jpg?enhanced&format=webp'
import MrpSWxMDEXYE from '../assets/icons/632360.jpg?enhanced&format=webp'
import BaoJsPPtjqzL from '../assets/icons/671860.jpg?enhanced&format=webp'
import klnWlIIXqipz from '../assets/icons/683320.jpg?enhanced&format=webp'
import NzVQcfCxAJrf from '../assets/icons/414340.jpg?enhanced&format=webp'
import kReInszihUTG from '../assets/icons/240720.jpg?enhanced&format=webp'
import RthSlhDGhTuq from '../assets/icons/582160.jpg?enhanced&format=webp'
import VLnDhFwmohAH from '../assets/icons/739630.jpg?enhanced&format=webp'
import KRESiUSpOjoA from '../assets/icons/418370.jpg?enhanced&format=webp'
import SHnHoWjXfwGi from '../assets/icons/812140.jpg?enhanced&format=webp'
import ThdyLfNPmIsu from '../assets/icons/552500.jpg?enhanced&format=webp'
import XiAeJBRYUYAS from '../assets/icons/750920.jpg?enhanced&format=webp'
import qnECAhDduaBN from '../assets/icons/858260.jpg?enhanced&format=webp'
import mcmECbOvLAcP from '../assets/icons/892970.jpg?enhanced&format=webp'
import DZqTjUADLjVk from '../assets/icons/899770.jpg?enhanced&format=webp'
import OpvhFnvWktuE from '../assets/icons/814380.jpg?enhanced&format=webp'
import gVPwiJIrTCvb from '../assets/icons/993090.jpg?enhanced&format=webp'
import VyOlskRkPviX from '../assets/icons/1063730.jpg?enhanced&format=webp'
import MyhcHPxKxkfJ from '../assets/icons/1079800.jpg?enhanced&format=webp'
import KPsvHGqokKwH from '../assets/icons/1091500.jpg?enhanced&format=webp'
import maYQagDZjSaH from '../assets/icons/1145360.jpg?enhanced&format=webp'
import GNOPlPcoSEgB from '../assets/icons/1151640.jpg?enhanced&format=webp'
import WONBHlLJAglV from '../assets/icons/1172620.jpg?enhanced&format=webp'
import qAyovbCPjQoN from '../assets/icons/1174180.jpg?enhanced&format=webp'
import MFjVkizlPSKD from '../assets/icons/397540.jpg?enhanced&format=webp'
import vOluoOfMpzZn from '../assets/icons/582010.jpg?enhanced&format=webp'
import rUpunFqFwODB from '../assets/icons/1222670.jpg?enhanced&format=webp'
import tBunLiIGepEL from '../assets/icons/1238840.jpg?enhanced&format=webp'
import SIGVZulShYpm from '../assets/icons/1237950.jpg?enhanced&format=webp'
import voCAofEhsZcU from '../assets/icons/1245620.jpg?enhanced&format=webp'
import xVYIwNHVtwxc from '../assets/icons/1151340.jpg?enhanced&format=webp'
import AXCwwIfwAHeK from '../assets/icons/1349230.jpg?enhanced&format=webp'
import IIUsLimDTMuV from '../assets/icons/1403370.jpg?enhanced&format=webp'
import vWuzMlEdvgIE from '../assets/icons/1454400.jpg?enhanced&format=webp'
import zKRkwIGQIrPj from '../assets/icons/1468260.jpg?enhanced&format=webp'
import axeFbPyBXTog from '../assets/icons/1475810.jpg?enhanced&format=webp'
import SCjennlDIBES from '../assets/icons/1476970.jpg?enhanced&format=webp'
import aRcNOzzigaAD from '../assets/icons/1562420.jpg?enhanced&format=webp'
import LwtQobDJhMam from '../assets/icons/1593500.jpg?enhanced&format=webp'
import rKSKVdyqBPHz from '../assets/icons/1599340.jpg?enhanced&format=webp'
import UpjtrMFUXpzk from '../assets/icons/1353300.jpg?enhanced&format=webp'
import ZjonmSQdlvJY from '../assets/icons/1240440.jpg?enhanced&format=webp'
import RuyPEhexvyao from '../assets/icons/1794680.jpg?enhanced&format=webp'
import XsIHqkfULVtU from '../assets/icons/1446780.jpg?enhanced&format=webp'
import bbklLfMsYsgl from '../assets/icons/1817070.jpg?enhanced&format=webp'
import DehIOwIeVXOt from '../assets/icons/1943950.jpg?enhanced&format=webp'
import LZgjoZSpXKUm from '../assets/icons/1966720.jpg?enhanced&format=webp'
import BdNHyoSwSRMK from '../assets/icons/1999360.jpg?enhanced&format=webp'
import ubduHlUJjKbA from '../assets/icons/2012840.jpg?enhanced&format=webp'
import GMmXnqUFriUC from '../assets/icons/1286680.jpg?enhanced&format=webp'
import QJpWhjUBSAXE from '../assets/icons/1313140.jpg?enhanced&format=webp'
import GNBIyEmvCnrz from '../assets/icons/990080.jpg?enhanced&format=webp'
import wBZotlyToGyG from '../assets/icons/2399830.jpg?enhanced&format=webp'
import HqCuLzzZRdeU from '../assets/icons/2420110.jpg?enhanced&format=webp'
import LgCIiMuArIEJ from '../assets/icons/1086940.jpg?enhanced&format=webp'
import KhGGpeQvzGWT from '../assets/icons/1361210.jpg?enhanced&format=webp'
import fXpIOAtjMGyq from '../assets/icons/2840770.jpg?enhanced&format=webp'
import cgDlhkalPJKr from '../assets/icons/2561580.jpg?enhanced&format=webp'
import qaKeQiigOldh from '../assets/icons/440.jpg?enhanced&format=webp'
import BfoRXloHiDIh from '../assets/icons/570.jpg?enhanced&format=webp'

const gameIconDict: Record<string, Picture> = {
	[220]: XRGtguRtBwrQ,
	[4000]: LOQLGLIqxUVo,
	[2300]: eLcJXuTUHtIC,
	[20900]: vWeIXMgkAssZ,
	[22300]: SlFdHXMCBNxc,
	[12210]: XVtWUETEDObn,
	[17390]: hfQejKYcgPMd,
	[29800]: PmTyfjTdbgpz,
	[6060]: dBUWGphdawjX,
	[550]: QiBhNyIYrZiC,
	[8190]: obUseRwrwdav,
	[57300]: cswdFeiEQPbT,
	[8930]: XuIvfzzUVosC,
	[40800]: TVTynaVSXKLM,
	[48190]: UNhYiDFBwbfv,
	[620]: weYVMdIPeUmM,
	[105600]: yJEoRDAlorAY,
	[20920]: avmSxROinXaJ,
	[92100]: DBXpXQlpLgMF,
	[22230]: nVQhlsUEpGTi,
	[3830]: nKDSOmxbPUvM,
	[204030]: KQEclFdRnCcJ,
	[207610]: fvUkgXNgbbzN,
	[206440]: KwOfvXmNoakH,
	[730]: SwBgXiwmvmCx,
	[200260]: iRKywigODmec,
	[212680]: aoopaSrQKvSz,
	[204360]: JddgUHtFIeVe,
	[49520]: LEKQTbQEswWt,
	[200710]: ooqtdHFXGUcE,
	[205100]: MFavjpUmKMcf,
	[223470]: pAEkOErIahOC,
	[55230]: nzihZpDSDjEa,
	[220700]: LIKOQCLNpGsE,
	[224540]: TAlOHnbslgAC,
	[200210]: prMtsKEWsoGt,
	[208090]: BbCibuYrPjVf,
	[230410]: lRpWCUmhUHfg,
	[236390]: pfqVKHUmITKT,
	[39000]: OvQCHUpSLkEu,
	[251670]: YrPZQbpRSXRF,
	[221040]: ZDmMOYJYkcWj,
	[203160]: JElAfXclWXwo,
	[47890]: JKVORlBhnDeG,
	[233450]: IKnIDlKJkBUS,
	[233720]: tIezTwVVyXai,
	[224760]: ifzYSWUoJQvM,
	[219740]: xIfHembYFVVx,
	[322330]: iwVXwpGVwydi,
	[234710]: BHeyeiqZptEn,
	[72850]: BAjhuzVcOLct,
	[35720]: yIfUnbBvSPhT,
	[242760]: WlIGwTafLJmz,
	[242860]: jyLbVbuuRHJn,
	[242920]: wEOqsnaBTOlP,
	[244850]: frvjpKkEVBeY,
	[218620]: bnxwbFtECEdG,
	[239820]: MxFEHaKgMRLC,
	[252950]: AEmTZWlVdRxU,
	[242050]: rOCzRnJjofzB,
	[219990]: vgjRNLZNKNgq,
	[257750]: RGxuLJqrLJxs,
	[221910]: RtEueGxqCtDc,
	[209170]: GmmZRCWDeQjF,
	[264140]: ouctyFHANddj,
	[264710]: ToKouhmbjMod,
	[265930]: iqMowKDtYMnx,
	[266010]: ABZSJbgSSPhK,
	[211820]: PTPSoOFcMtmq,
	[221100]: wnDDYTgFUVGY,
	[268910]: iNhVmJAtuFNg,
	[237870]: VfTTfWZYqXbp,
	[225840]: JrcKVFrJcTZL,
	[282140]: MKFEAvuZiaqR,
	[287700]: ZQrPNFbsSZkE,
	[292030]: pTnoQJIbWJAt,
	[286160]: HgSzsOzGWgil,
	[289130]: JWGTzvkLFVzm,
	[238460]: hIXvGcFNAuoS,
	[299460]: FIRxFiyTAQGQ,
	[243470]: gNLzrKWfvOFH,
	[304930]: ndrAPwhXaHcv,
	[306020]: VXPFrsGpyULk,
	[9900]: CpCkmxflIlzV,
	[311690]: cUAgKlsfRiqv,
	[206420]: NaQBzltzRYfO,
	[314650]: hYsFILLWkeTV,
	[241930]: hZuKeAzILZWs,
	[322170]: jztBXWuvCkIQ,
	[214490]: ROkmpPmJsBGs,
	[238320]: UTrzWgbustuI,
	[327140]: BpjGZHLpqDux,
	[327890]: XrmGsXuOuLdN,
	[261640]: nohHmznTCkfq,
	[211420]: iujYjofqgGMc,
	[330350]: dxDWPTisrlJU,
	[298110]: FePbPrTKBHAq,
	[305620]: PqzkMBWboJen,
	[252490]: XFlQAZXZrfWT,
	[250900]: oObaPGlvafHL,
	[319630]: irDGuuBiULGG,
	[219150]: qugQMxChRsae,
	[274170]: bohjxjdKxpOa,
	[346010]: kWSuvVgBgqOJ,
	[346110]: scaKUgYezrRI,
	[346900]: KZxIdPgQnCNl,
	[298630]: jzuWSuFxIYfx,
	[255710]: lmbApYLBwIsR,
	[306130]: cNCjEsQBkozW,
	[271590]: BlNOSuPYpzPN,
	[359050]: zKrPxcZzIuMO,
	[363970]: ORhtOSnJAXVa,
	[365720]: dxQYgQWJduIb,
	[367520]: ZmSNTBGEtevV,
	[375950]: aqMbCVkcPxrH,
	[377160]: HvxQXdZDnqkQ,
	[384190]: ENhsdxbpOzpY,
	[391540]: OjjZnzpyRZog,
	[392110]: PvLCWcvnWPgO,
	[393380]: mPIXsNVNEOsT,
	[413150]: wsiAWBPDuWfK,
	[225540]: ZUgiFuFGTNvw,
	[417860]: hslxVIRvShXW,
	[208650]: IQCrDylhawOZ,
	[420530]: gEuUymFRcXvU,
	[391220]: uiobcqVKKfGL,
	[427520]: mnUEkfExkPbZ,
	[210970]: pVhzDcRwQPhg,
	[359550]: sdkTJXklaGVt,
	[623990]: fDlNRifObtch,
	[239140]: zbBToXZCfMcF,
	[431960]: gLMvGglyeUKh,
	[434260]: xbbmowSseqqh,
	[434570]: rRpohOSJgGGe,
	[374320]: napqQPuDlHOy,
	[275850]: WEZBxlQKagoS,
	[457550]: WGiXFyfJxTwl,
	[403640]: tLLiaDLqTYAT,
	[501300]: THubxvzuWxAw,
	[518790]: TotFSbDBYMrZ,
	[289070]: ugzAYSaafZyH,
	[534380]: XkrqbPahEdFY,
	[546560]: FuoxEHhRnzDj,
	[548430]: qBQjyhwntfBY,
	[489830]: lxSOQCRCFWhg,
	[553850]: evaeyPsLZnjP,
	[555160]: YoFwpAczcAxs,
	[447040]: lpmQIYFxyDvP,
	[460920]: tmigoPvrGWAA,
	[564710]: KCUIDGljxWPA,
	[578080]: hXDkCEnGJUMR,
	[578620]: VXYqDvvSWfoC,
	[582660]: fMprujRCEZgP,
	[588650]: ITzhnwhOhGjU,
	[460930]: qNUzoxFDdins,
	[611670]: emlbeuGjsWdc,
	[617830]: hSeEiBJeTlRL,
	[619910]: uzTTMHoqZZVl,
	[620980]: kUaAiQmOTQzF,
	[629730]: FEUhDZaZmmru,
	[632360]: MrpSWxMDEXYE,
	[671860]: BaoJsPPtjqzL,
	[683320]: klnWlIIXqipz,
	[414340]: NzVQcfCxAJrf,
	[240720]: kReInszihUTG,
	[582160]: RthSlhDGhTuq,
	[739630]: VLnDhFwmohAH,
	[418370]: KRESiUSpOjoA,
	[812140]: SHnHoWjXfwGi,
	[552500]: ThdyLfNPmIsu,
	[750920]: XiAeJBRYUYAS,
	[858260]: qnECAhDduaBN,
	[892970]: mcmECbOvLAcP,
	[899770]: DZqTjUADLjVk,
	[814380]: OpvhFnvWktuE,
	[993090]: gVPwiJIrTCvb,
	[1063730]: VyOlskRkPviX,
	[1079800]: MyhcHPxKxkfJ,
	[1091500]: KPsvHGqokKwH,
	[1145360]: maYQagDZjSaH,
	[1151640]: GNOPlPcoSEgB,
	[1172620]: WONBHlLJAglV,
	[1174180]: qAyovbCPjQoN,
	[397540]: MFjVkizlPSKD,
	[582010]: vOluoOfMpzZn,
	[1222670]: rUpunFqFwODB,
	[1238840]: tBunLiIGepEL,
	[1237950]: SIGVZulShYpm,
	[1245620]: voCAofEhsZcU,
	[1151340]: xVYIwNHVtwxc,
	[1349230]: AXCwwIfwAHeK,
	[1403370]: IIUsLimDTMuV,
	[1454400]: vWuzMlEdvgIE,
	[1468260]: zKRkwIGQIrPj,
	[1475810]: axeFbPyBXTog,
	[1476970]: SCjennlDIBES,
	[1562420]: aRcNOzzigaAD,
	[1593500]: LwtQobDJhMam,
	[1599340]: rKSKVdyqBPHz,
	[1353300]: UpjtrMFUXpzk,
	[1240440]: ZjonmSQdlvJY,
	[1794680]: RuyPEhexvyao,
	[1446780]: XsIHqkfULVtU,
	[1817070]: bbklLfMsYsgl,
	[1943950]: DehIOwIeVXOt,
	[1966720]: LZgjoZSpXKUm,
	[1999360]: BdNHyoSwSRMK,
	[2012840]: ubduHlUJjKbA,
	[1286680]: GMmXnqUFriUC,
	[1313140]: QJpWhjUBSAXE,
	[990080]: GNBIyEmvCnrz,
	[2399830]: wBZotlyToGyG,
	[2420110]: HqCuLzzZRdeU,
	[1086940]: LgCIiMuArIEJ,
	[1361210]: KhGGpeQvzGWT,
	[2840770]: fXpIOAtjMGyq,
	[2561580]: cgDlhkalPJKr,
	[440]: qaKeQiigOldh,
	[570]: BfoRXloHiDIh
};

const getGameIcon = (appId: number, icon_url: string) => {
	if (gameIconDict[appId]) {
		return gameIconDict[appId]
	}
	return `https://media.steampowered.com/steamcommunity/public/images/apps/${appId}/${icon_url}.jpg`
}
export { getGameIcon }
import jtKiqhltazGD from '../assets/profile_pictures/c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg?enhanced&format=webp&w=64;128;200'
import WfnsUxgWaoLL from '../assets/profile_pictures/543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg?enhanced&format=webp&w=64;128;200'
import yhaJxZitsgiy from '../assets/profile_pictures/c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg?enhanced&format=webp&w=64;128;200'
import rHoYyEuHVftL from '../assets/profile_pictures/cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg?enhanced&format=webp&w=64;128;200'
import gepIcDWXTFit from '../assets/profile_pictures/65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg?enhanced&format=webp&w=64;128;200'
import rFLyuXfarZxq from '../assets/profile_pictures/26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg?enhanced&format=webp&w=64;128;200'
import zgNKuzXmuyAU from '../assets/profile_pictures/2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg?enhanced&format=webp&w=64;128;200'
import IejMFRyanvEJ from '../assets/profile_pictures/cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg?enhanced&format=webp&w=64;128;200'
import tjkgIvPUFmIZ from '../assets/profile_pictures/acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg?enhanced&format=webp&w=64;128;200'
import glfrbPLhkcaL from '../assets/profile_pictures/027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg?enhanced&format=webp&w=64;128;200'
import RtaQLFqGqNYu from '../assets/profile_pictures/2e70ee0c16e6523cbe340bedb4f0a0857712d3b0_full.jpg?enhanced&format=webp&w=64;128;200'
import QgvSkURfmRqy from '../assets/profile_pictures/81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg?enhanced&format=webp&w=64;128;200'
import tuEfKwHhynlT from '../assets/profile_pictures/d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg?enhanced&format=webp&w=64;128;200'
import ewwpVWEwjvsZ from '../assets/profile_pictures/d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg?enhanced&format=webp&w=64;128;200'
import WVLXEeqwAwTY from '../assets/profile_pictures/37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg?enhanced&format=webp&w=64;128;200'
import bnjzLcGcVMmj from '../assets/profile_pictures/f924231652dc74192753cb3aea5ba883e9a843ff_full.jpg?enhanced&format=webp&w=64;128;200'
import kfWKoCOnTeQx from '../assets/profile_pictures/f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg?enhanced&format=webp&w=64;128;200'
import YcpzudRITxrw from '../assets/profile_pictures/83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg?enhanced&format=webp&w=64;128;200'
import xaWSTbfNIxtY from '../assets/profile_pictures/a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg?enhanced&format=webp&w=64;128;200'
import KDRqRgjqzSCP from '../assets/profile_pictures/5737632a6c34d49b2954c28ce0f970c145c252aa_full.jpg?enhanced&format=webp&w=64;128;200'
import DQSnQGaXBfOd from '../assets/profile_pictures/129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg?enhanced&format=webp&w=64;128;200'
import EeKCBiqvDXra from '../assets/profile_pictures/44933eeb90b5e4d5aefb7a31a8d2f72d569403c5_full.jpg?enhanced&format=webp&w=64;128;200'
import tFclIjfYJaac from '../assets/profile_pictures/e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg?enhanced&format=webp&w=64;128;200'
import vnxOfxZRtijK from '../assets/profile_pictures/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg?enhanced&format=webp&w=64;128;200'
import OIpjVookoIcQ from '../assets/profile_pictures/6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg?enhanced&format=webp&w=64;128;200'
import EUvvYLAFeZXS from '../assets/profile_pictures/d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg?enhanced&format=webp&w=64;128;200'
import nHsPeHZRfwkd from '../assets/profile_pictures/efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg?enhanced&format=webp&w=64;128;200'
import NCDHWrqcAxOd from '../assets/profile_pictures/1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg?enhanced&format=webp&w=64;128;200'
import uUHbLJoQypqa from '../assets/profile_pictures/c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg?enhanced&format=webp&w=64;128;200'
import oiRRrLEqXmim from '../assets/profile_pictures/a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg?enhanced&format=webp&w=64;128;200'
import ZkdoWsVcwrSD from '../assets/profile_pictures/f4f2fc58620a769dfcc51defda89ed5cb8fa7d75_full.jpg?enhanced&format=webp&w=64;128;200'
import CWxhfMFVsRza from '../assets/profile_pictures/330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg?enhanced&format=webp&w=64;128;200'
import KXRwiAaWGMUW from '../assets/profile_pictures/a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg?enhanced&format=webp&w=64;128;200'
import MvQqazwikvfI from '../assets/profile_pictures/0828e6eb804f312f914c446070331a35630b5d60_full.jpg?enhanced&format=webp&w=64;128;200'
import LFxWmSNnBhUU from '../assets/profile_pictures/bb056dd750e1444aee38309fc04c139a5948c077_full.jpg?enhanced&format=webp&w=64;128;200'
import ALgFEeaEKisI from '../assets/profile_pictures/5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg?enhanced&format=webp&w=64;128;200'
import jzpdMHoBHQIm from '../assets/profile_pictures/11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg?enhanced&format=webp&w=64;128;200'
import FYLxAfASaFxI from '../assets/profile_pictures/360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg?enhanced&format=webp&w=64;128;200'
import mGgdrOZjEBbI from '../assets/profile_pictures/943df69df7a93f95109bac568dcd20e416622838_full.jpg?enhanced&format=webp&w=64;128;200'
import YiMaMosmcGOh from '../assets/profile_pictures/cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg?enhanced&format=webp&w=64;128;200'
import qfkYVhWHwufC from '../assets/profile_pictures/79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg?enhanced&format=webp&w=64;128;200'
import FAuFUXlKrHet from '../assets/profile_pictures/7ed4ace4db81e7c1870f8af8452b4aa51eab39bf_full.jpg?enhanced&format=webp&w=64;128;200'
import vleNcNmtOZYT from '../assets/profile_pictures/a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg?enhanced&format=webp&w=64;128;200'
import HFaqJOGYywWR from '../assets/profile_pictures/cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg?enhanced&format=webp&w=64;128;200'
import rTuXuaKKbbIs from '../assets/profile_pictures/7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg?enhanced&format=webp&w=64;128;200'
import ujWKNyaYaMVj from '../assets/profile_pictures/ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg?enhanced&format=webp&w=64;128;200'
import QfqzYhCYCwGE from '../assets/profile_pictures/420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg?enhanced&format=webp&w=64;128;200'
import mNquMWeVnhCF from '../assets/profile_pictures/52bfe6828f7cc88655757907064a1e9533425083_full.jpg?enhanced&format=webp&w=64;128;200'
import xrtBQIMRoxAj from '../assets/profile_pictures/9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg?enhanced&format=webp&w=64;128;200'
import FdOaKRmsHASa from '../assets/profile_pictures/0f152b35bd9ab9e139a662d8ce7a1f26f025d3c6_full.jpg?enhanced&format=webp&w=64;128;200'
import MBlTXKVyKkuJ from '../assets/profile_pictures/9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg?enhanced&format=webp&w=64;128;200'
import PuMRrlNvnvXU from '../assets/profile_pictures/576a072e6da81175e6b47f000010d843bca92fd7_full.jpg?enhanced&format=webp&w=64;128;200'
import mzgtGCqSqxkI from '../assets/profile_pictures/e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg?enhanced&format=webp&w=64;128;200'
import kBJUXvPKfEOd from '../assets/profile_pictures/b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg?enhanced&format=webp&w=64;128;200'
import lmCjpyLihFDL from '../assets/profile_pictures/831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg?enhanced&format=webp&w=64;128;200'
import HJkCTPoAjDDw from '../assets/profile_pictures/0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg?enhanced&format=webp&w=64;128;200'
import wQFrrSmMzwvc from '../assets/profile_pictures/049116dc3827584518d1124b90aa06b7fab8d023_full.jpg?enhanced&format=webp&w=64;128;200'
import IlPtUBulbcXw from '../assets/profile_pictures/56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg?enhanced&format=webp&w=64;128;200'
import pCTBFiOriZYB from '../assets/profile_pictures/834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg?enhanced&format=webp&w=64;128;200'
import fPkVUpvGnbqR from '../assets/profile_pictures/6595a243739ae73573ddd184d2da3f6690bcc8a2_full.jpg?enhanced&format=webp&w=64;128;200'
import cyaRBPIRRkOw from '../assets/profile_pictures/4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg?enhanced&format=webp&w=64;128;200'
import JDfPWkyutqJQ from '../assets/profile_pictures/56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg?enhanced&format=webp&w=64;128;200'
import hJAYkdFoVtqe from '../assets/profile_pictures/49acdd7acab28c9344ec286e4dae713098043b02_full.jpg?enhanced&format=webp&w=64;128;200'
import ZKRUpOeiWElN from '../assets/profile_pictures/83764e067f3ee3bc0be68d65f4169c80d142b7af_full.jpg?enhanced&format=webp&w=64;128;200'
import IOxRPanKhTEU from '../assets/profile_pictures/7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg?enhanced&format=webp&w=64;128;200'
import TLavZHkZHtRX from '../assets/profile_pictures/2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg?enhanced&format=webp&w=64;128;200'
import kDpRiADxzfUd from '../assets/profile_pictures/618bfa7e8477cee17e56637af632fef4e31724b2_full.jpg?enhanced&format=webp&w=64;128;200'
import XkiyQqsrIXBv from '../assets/profile_pictures/203dfa2c44bce6446016a7444da7647838544183_full.jpg?enhanced&format=webp&w=64;128;200'
import njpMHDHXwSpg from '../assets/profile_pictures/7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg?enhanced&format=webp&w=64;128;200'
import OqhzlntlOHMx from '../assets/profile_pictures/c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg?enhanced&format=webp&w=64;128;200'
import ULPZTplAJgPM from '../assets/profile_pictures/00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg?enhanced&format=webp&w=64;128;200'
import bodtKGitGmlb from '../assets/profile_pictures/9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg?enhanced&format=webp&w=64;128;200'
import gmzwUVgQeCuU from '../assets/profile_pictures/6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg?enhanced&format=webp&w=64;128;200'
import olXWSxCgfdre from '../assets/profile_pictures/52a9de1668a398d4dc400b8f225c5374034e9d82_full.jpg?enhanced&format=webp&w=64;128;200'
import NEmgtUYdvLbj from '../assets/profile_pictures/7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg?enhanced&format=webp&w=64;128;200'
import IyyqJkGDtgCF from '../assets/profile_pictures/38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg?enhanced&format=webp&w=64;128;200'
import AZumvwJJqCqy from '../assets/profile_pictures/fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg?enhanced&format=webp&w=64;128;200'
import EXrNSfsrwQHi from '../assets/profile_pictures/9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg?enhanced&format=webp&w=64;128;200'
import SkfchShSxLTw from '../assets/profile_pictures/8879e59d4428c411c61e108f3d647dd13540d80d_full.jpg?enhanced&format=webp&w=64;128;200'
import FQvceVaUuKqj from '../assets/profile_pictures/de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg?enhanced&format=webp&w=64;128;200'
import ZqIIfujEIqpk from '../assets/profile_pictures/7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg?enhanced&format=webp&w=64;128;200'
import JxwrhWERnKmQ from '../assets/profile_pictures/b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg?enhanced&format=webp&w=64;128;200'

const pfpDict: Record<string, Picture> = {
	"c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg": jtKiqhltazGD,
	"543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg": WfnsUxgWaoLL,
	"c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg": yhaJxZitsgiy,
	"cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg": rHoYyEuHVftL,
	"65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg": gepIcDWXTFit,
	"26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg": rFLyuXfarZxq,
	"2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg": zgNKuzXmuyAU,
	"cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg": IejMFRyanvEJ,
	"acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg": tjkgIvPUFmIZ,
	"027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg": glfrbPLhkcaL,
	"2e70ee0c16e6523cbe340bedb4f0a0857712d3b0_full.jpg": RtaQLFqGqNYu,
	"81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg": QgvSkURfmRqy,
	"d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg": tuEfKwHhynlT,
	"d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg": ewwpVWEwjvsZ,
	"37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg": WVLXEeqwAwTY,
	"f924231652dc74192753cb3aea5ba883e9a843ff_full.jpg": bnjzLcGcVMmj,
	"f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg": kfWKoCOnTeQx,
	"83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg": YcpzudRITxrw,
	"a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg": xaWSTbfNIxtY,
	"5737632a6c34d49b2954c28ce0f970c145c252aa_full.jpg": KDRqRgjqzSCP,
	"129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg": DQSnQGaXBfOd,
	"44933eeb90b5e4d5aefb7a31a8d2f72d569403c5_full.jpg": EeKCBiqvDXra,
	"e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg": tFclIjfYJaac,
	"fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg": vnxOfxZRtijK,
	"6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg": OIpjVookoIcQ,
	"d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg": EUvvYLAFeZXS,
	"efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg": nHsPeHZRfwkd,
	"1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg": NCDHWrqcAxOd,
	"c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg": uUHbLJoQypqa,
	"a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg": oiRRrLEqXmim,
	"f4f2fc58620a769dfcc51defda89ed5cb8fa7d75_full.jpg": ZkdoWsVcwrSD,
	"330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg": CWxhfMFVsRza,
	"a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg": KXRwiAaWGMUW,
	"0828e6eb804f312f914c446070331a35630b5d60_full.jpg": MvQqazwikvfI,
	"bb056dd750e1444aee38309fc04c139a5948c077_full.jpg": LFxWmSNnBhUU,
	"5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg": ALgFEeaEKisI,
	"11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg": jzpdMHoBHQIm,
	"360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg": FYLxAfASaFxI,
	"943df69df7a93f95109bac568dcd20e416622838_full.jpg": mGgdrOZjEBbI,
	"cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg": YiMaMosmcGOh,
	"79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg": qfkYVhWHwufC,
	"7ed4ace4db81e7c1870f8af8452b4aa51eab39bf_full.jpg": FAuFUXlKrHet,
	"a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg": vleNcNmtOZYT,
	"cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg": HFaqJOGYywWR,
	"7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg": rTuXuaKKbbIs,
	"ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg": ujWKNyaYaMVj,
	"420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg": QfqzYhCYCwGE,
	"52bfe6828f7cc88655757907064a1e9533425083_full.jpg": mNquMWeVnhCF,
	"9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg": xrtBQIMRoxAj,
	"0f152b35bd9ab9e139a662d8ce7a1f26f025d3c6_full.jpg": FdOaKRmsHASa,
	"9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg": MBlTXKVyKkuJ,
	"576a072e6da81175e6b47f000010d843bca92fd7_full.jpg": PuMRrlNvnvXU,
	"e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg": mzgtGCqSqxkI,
	"b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg": kBJUXvPKfEOd,
	"831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg": lmCjpyLihFDL,
	"0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg": HJkCTPoAjDDw,
	"049116dc3827584518d1124b90aa06b7fab8d023_full.jpg": wQFrrSmMzwvc,
	"56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg": IlPtUBulbcXw,
	"834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg": pCTBFiOriZYB,
	"6595a243739ae73573ddd184d2da3f6690bcc8a2_full.jpg": fPkVUpvGnbqR,
	"4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg": cyaRBPIRRkOw,
	"56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg": JDfPWkyutqJQ,
	"49acdd7acab28c9344ec286e4dae713098043b02_full.jpg": hJAYkdFoVtqe,
	"83764e067f3ee3bc0be68d65f4169c80d142b7af_full.jpg": ZKRUpOeiWElN,
	"7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg": IOxRPanKhTEU,
	"2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg": TLavZHkZHtRX,
	"618bfa7e8477cee17e56637af632fef4e31724b2_full.jpg": kDpRiADxzfUd,
	"203dfa2c44bce6446016a7444da7647838544183_full.jpg": XkiyQqsrIXBv,
	"7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg": njpMHDHXwSpg,
	"c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg": OqhzlntlOHMx,
	"00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg": ULPZTplAJgPM,
	"9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg": bodtKGitGmlb,
	"6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg": gmzwUVgQeCuU,
	"52a9de1668a398d4dc400b8f225c5374034e9d82_full.jpg": olXWSxCgfdre,
	"7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg": NEmgtUYdvLbj,
	"38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg": IyyqJkGDtgCF,
	"fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg": AZumvwJJqCqy,
	"9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg": EXrNSfsrwQHi,
	"8879e59d4428c411c61e108f3d647dd13540d80d_full.jpg": SkfchShSxLTw,
	"de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg": FQvceVaUuKqj,
	"7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg": ZqIIfujEIqpk,
	"b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg": JxwrhWERnKmQ
};

const getProfilePicture = (profilePic: string) => {
    if (pfpDict[profilePic]) {
		return pfpDict[profilePic]
	}
    return `https://avatars.steamstatic.com/${profilePic}`
}
export { getProfilePicture }
