/**
* NOTE: This file is auto-generated by scripts/prefetch_steam.ts
* DO NOT modify manually
*/
import type { Picture } from 'vite-imagetools';
import OEzihZyrGDlt from '../assets/games/220.jpg?enhanced&format=webp'
import uIkNoLDMxfwB from '../assets/games/4000.jpg?enhanced&format=webp'
import cWCwumsgYbjB from '../assets/games/2300.jpg?enhanced&format=webp'
import eOvoMOOTnxCw from '../assets/games/20900.jpg?enhanced&format=webp'
import nAeWYwiEjdip from '../assets/games/22300.jpg?enhanced&format=webp'
import sGWEcgVYmIAs from '../assets/games/12210.jpg?enhanced&format=webp'
import miFKlHWcGqfO from '../assets/games/17390.jpg?enhanced&format=webp'
import WkwHxOVzcWtp from '../assets/games/29800.jpg?enhanced&format=webp'
import GvAEYQeZaHNG from '../assets/games/6060.jpg?enhanced&format=webp'
import AeErSuFTFmoH from '../assets/games/550.jpg?enhanced&format=webp'
import uvVwjQECHssR from '../assets/games/8190.jpg?enhanced&format=webp'
import auoZVDbmjxaT from '../assets/games/57300.jpg?enhanced&format=webp'
import fBmQMFMBNEoB from '../assets/games/8930.jpg?enhanced&format=webp'
import QQxCddMpxFdB from '../assets/games/40800.jpg?enhanced&format=webp'
import PtoENEjfERAF from '../assets/games/48190.jpg?enhanced&format=webp'
import zSzBaYGRiEBk from '../assets/games/620.jpg?enhanced&format=webp'
import rlDizcOqiFQx from '../assets/games/105600.jpg?enhanced&format=webp'
import gfJrqqZGyYzH from '../assets/games/20920.jpg?enhanced&format=webp'
import PaaWpbjnjAiz from '../assets/games/92100.jpg?enhanced&format=webp'
import AUtAZIjpsHvD from '../assets/games/22230.jpg?enhanced&format=webp'
import GInnRFkYpCfk from '../assets/games/3830.jpg?enhanced&format=webp'
import bcBMWfIEyArd from '../assets/games/204030.jpg?enhanced&format=webp'
import PwdRdPQeGIEp from '../assets/games/207610.jpg?enhanced&format=webp'
import pWrWfIAWgxYu from '../assets/games/206440.jpg?enhanced&format=webp'
import tagzNzkncFQL from '../assets/games/730.jpg?enhanced&format=webp'
import UgDnuHAGytBv from '../assets/games/200260.jpg?enhanced&format=webp'
import UKdXXFlGFzcd from '../assets/games/212680.jpg?enhanced&format=webp'
import uoTIlmjVAYgu from '../assets/games/204360.jpg?enhanced&format=webp'
import HTwIrlEqqorO from '../assets/games/49520.jpg?enhanced&format=webp'
import NezgsPJkGFCS from '../assets/games/200710.jpg?enhanced&format=webp'
import yTgFClCeSEjg from '../assets/games/205100.jpg?enhanced&format=webp'
import DgsuZhmwxtqE from '../assets/games/223470.jpg?enhanced&format=webp'
import yzORKRYpMKUE from '../assets/games/55230.jpg?enhanced&format=webp'
import rnHtaQTiwVtr from '../assets/games/220700.jpg?enhanced&format=webp'
import eTeJOqQpwffk from '../assets/games/224540.jpg?enhanced&format=webp'
import YCALsGaNqEng from '../assets/games/200210.jpg?enhanced&format=webp'
import ASCIYYjAxxsX from '../assets/games/208090.jpg?enhanced&format=webp'
import tEtSSiAomYuL from '../assets/games/230410.jpg?enhanced&format=webp'
import zopKpWGXAVda from '../assets/games/236390.jpg?enhanced&format=webp'
import tOMMvzwhuGIa from '../assets/games/39000.jpg?enhanced&format=webp'
import rVykZubpfwVr from '../assets/games/251670.jpg?enhanced&format=webp'
import UFZUXqvqEoib from '../assets/games/221040.jpg?enhanced&format=webp'
import NizCneEOoYCs from '../assets/games/203160.jpg?enhanced&format=webp'
import NuGYvuaucuBH from '../assets/games/47890.jpg?enhanced&format=webp'
import jfILLjnRdpZS from '../assets/games/233450.jpg?enhanced&format=webp'
import vNIoJWidnwsB from '../assets/games/233720.jpg?enhanced&format=webp'
import gIHLKKLKFDZD from '../assets/games/224760.jpg?enhanced&format=webp'
import zuefSbcNjfEl from '../assets/games/219740.jpg?enhanced&format=webp'
import ePwhYDEVTmZw from '../assets/games/322330.jpg?enhanced&format=webp'
import ifCejXhUttJt from '../assets/games/234710.jpg?enhanced&format=webp'
import vgFDpiqATMdz from '../assets/games/72850.jpg?enhanced&format=webp'
import KkGvctDmhrsF from '../assets/games/35720.jpg?enhanced&format=webp'
import BbEleUbbdyyH from '../assets/games/242760.jpg?enhanced&format=webp'
import vJgslrcotPXQ from '../assets/games/242860.jpg?enhanced&format=webp'
import DrXkjZzPiQqa from '../assets/games/242920.jpg?enhanced&format=webp'
import mfAjEJMfoCSQ from '../assets/games/244850.jpg?enhanced&format=webp'
import WlLbVtQyZAlU from '../assets/games/218620.jpg?enhanced&format=webp'
import NqtmMsGuHeWM from '../assets/games/239820.jpg?enhanced&format=webp'
import tdCWKVhGBsgT from '../assets/games/252950.jpg?enhanced&format=webp'
import YQLRDSgiMCMY from '../assets/games/242050.jpg?enhanced&format=webp'
import GoDsLSzqtVuO from '../assets/games/219990.jpg?enhanced&format=webp'
import zChAniKtmSMy from '../assets/games/257750.jpg?enhanced&format=webp'
import zoJmwwYuIsjZ from '../assets/games/221910.jpg?enhanced&format=webp'
import aCSBHFoClYcC from '../assets/games/209170.jpg?enhanced&format=webp'
import GCqPEAnlHiFR from '../assets/games/264140.jpg?enhanced&format=webp'
import GYIJwNyYpvLV from '../assets/games/264710.jpg?enhanced&format=webp'
import HtsLvqIYWJrW from '../assets/games/265930.jpg?enhanced&format=webp'
import QKPrpvBWAwGu from '../assets/games/266010.jpg?enhanced&format=webp'
import NJeaHvMgwfmD from '../assets/games/211820.jpg?enhanced&format=webp'
import iKgUgGDfFDgU from '../assets/games/221100.jpg?enhanced&format=webp'
import xZnIjXKlZmVy from '../assets/games/268910.jpg?enhanced&format=webp'
import HEIgPExUILpC from '../assets/games/237870.jpg?enhanced&format=webp'
import BKZsHNIuvjUF from '../assets/games/225840.jpg?enhanced&format=webp'
import iMqaxujEVlWx from '../assets/games/282140.jpg?enhanced&format=webp'
import MfWiTtxmOhEt from '../assets/games/287700.jpg?enhanced&format=webp'
import gZjZuErvDwlo from '../assets/games/292030.jpg?enhanced&format=webp'
import SrbMnNvIAeJj from '../assets/games/286160.jpg?enhanced&format=webp'
import RmQQWCqcJMrA from '../assets/games/289130.jpg?enhanced&format=webp'
import TqmewWIaNRxG from '../assets/games/238460.jpg?enhanced&format=webp'
import WuPozGFWGFrf from '../assets/games/299460.jpg?enhanced&format=webp'
import JWAyiHijoAHx from '../assets/games/243470.jpg?enhanced&format=webp'
import sLZLNpMRRgTv from '../assets/games/304930.jpg?enhanced&format=webp'
import AXzCjpJcDlRG from '../assets/games/306020.jpg?enhanced&format=webp'
import FyRiBJzkeQhC from '../assets/games/9900.jpg?enhanced&format=webp'
import YRqhzYKrovEW from '../assets/games/311690.jpg?enhanced&format=webp'
import XQHJHfsMukuV from '../assets/games/206420.jpg?enhanced&format=webp'
import lfljhCRvuIvl from '../assets/games/314650.jpg?enhanced&format=webp'
import FOGbOBolAUTO from '../assets/games/241930.jpg?enhanced&format=webp'
import fHTrJcknTIWm from '../assets/games/322170.jpg?enhanced&format=webp'
import oymYFRfpRExy from '../assets/games/214490.jpg?enhanced&format=webp'
import GbjZyprTVxgy from '../assets/games/238320.jpg?enhanced&format=webp'
import CwazCzkUMujB from '../assets/games/327140.jpg?enhanced&format=webp'
import wjIOchvwriJY from '../assets/games/327890.jpg?enhanced&format=webp'
import TKujfUQPwIXr from '../assets/games/261640.jpg?enhanced&format=webp'
import ZdIUdMELwLom from '../assets/games/211420.jpg?enhanced&format=webp'
import wqimmXkvsrTE from '../assets/games/330350.jpg?enhanced&format=webp'
import ogHsZLKTKMKo from '../assets/games/298110.jpg?enhanced&format=webp'
import HEUIMPQBQWLc from '../assets/games/305620.jpg?enhanced&format=webp'
import tmiqKLFltTgC from '../assets/games/252490.jpg?enhanced&format=webp'
import iGxkAKZefGeo from '../assets/games/250900.jpg?enhanced&format=webp'
import QMjaxiUBHYLo from '../assets/games/319630.jpg?enhanced&format=webp'
import BKOwWdcuHZXL from '../assets/games/219150.jpg?enhanced&format=webp'
import LnDlvlAIsFqu from '../assets/games/274170.jpg?enhanced&format=webp'
import PdOcmSnqwHhU from '../assets/games/346010.jpg?enhanced&format=webp'
import RaocpKLsYFXc from '../assets/games/346110.jpg?enhanced&format=webp'
import EJEucHAJfzZr from '../assets/games/346900.jpg?enhanced&format=webp'
import bmXpiezeXUlR from '../assets/games/298630.jpg?enhanced&format=webp'
import QVPhwPiLLuTn from '../assets/games/255710.jpg?enhanced&format=webp'
import ciVSJkwUltQH from '../assets/games/306130.jpg?enhanced&format=webp'
import ifRLiXcbHKJT from '../assets/games/271590.jpg?enhanced&format=webp'
import ytXNcXQMfQpK from '../assets/games/359050.jpg?enhanced&format=webp'
import qHhnEKgOAUvs from '../assets/games/363970.jpg?enhanced&format=webp'
import TJfnwejSDMQA from '../assets/games/365720.jpg?enhanced&format=webp'
import XJzdknzzalbW from '../assets/games/367520.jpg?enhanced&format=webp'
import KCiSAlVtAoWz from '../assets/games/375950.jpg?enhanced&format=webp'
import wzlVBcHRTZGK from '../assets/games/377160.jpg?enhanced&format=webp'
import cWXwZfwfmeRk from '../assets/games/384190.jpg?enhanced&format=webp'
import sYiRyMHQziSw from '../assets/games/391540.jpg?enhanced&format=webp'
import WMXBYsPpAQuf from '../assets/games/392110.jpg?enhanced&format=webp'
import ogeVKrODVCty from '../assets/games/393380.jpg?enhanced&format=webp'
import ScHmczdUKlUs from '../assets/games/413150.jpg?enhanced&format=webp'
import NQxWUWAcuVjc from '../assets/games/225540.jpg?enhanced&format=webp'
import olCpWEWYrqmB from '../assets/games/417860.jpg?enhanced&format=webp'
import JByDstLiutnf from '../assets/games/208650.jpg?enhanced&format=webp'
import HTyKbnZqrNaH from '../assets/games/420530.jpg?enhanced&format=webp'
import ISnzzapyyIgW from '../assets/games/391220.jpg?enhanced&format=webp'
import HTrUZzVKNjVL from '../assets/games/427520.jpg?enhanced&format=webp'
import oZvwUgBzIfHl from '../assets/games/210970.jpg?enhanced&format=webp'
import kwuhIuyxdWOT from '../assets/games/359550.jpg?enhanced&format=webp'
import KaVPUfilfEct from '../assets/games/623990.jpg?enhanced&format=webp'
import UPnAtEVSCAbd from '../assets/games/239140.jpg?enhanced&format=webp'
import VGeVewoJIdMO from '../assets/games/431960.jpg?enhanced&format=webp'
import SKRqMivQGpdg from '../assets/games/434260.jpg?enhanced&format=webp'
import YxRCMrNgQVtu from '../assets/games/434570.jpg?enhanced&format=webp'
import CSybvHVNugZh from '../assets/games/374320.jpg?enhanced&format=webp'
import aFvIRVlCeAfu from '../assets/games/275850.jpg?enhanced&format=webp'
import gDrBYQsOAMaY from '../assets/games/457550.jpg?enhanced&format=webp'
import wdgmkKjuTXgK from '../assets/games/403640.jpg?enhanced&format=webp'
import fctYphLKNYBl from '../assets/games/501300.jpg?enhanced&format=webp'
import tlHXKMOHAlwm from '../assets/games/518790.jpg?enhanced&format=webp'
import mUkgCDdUmsJA from '../assets/games/289070.jpg?enhanced&format=webp'
import afLbvFNNSWxN from '../assets/games/534380.jpg?enhanced&format=webp'
import NRzWBZpHdLlT from '../assets/games/546560.jpg?enhanced&format=webp'
import ehItnOliZqqB from '../assets/games/548430.jpg?enhanced&format=webp'
import CqNgEFxiPVVl from '../assets/games/489830.jpg?enhanced&format=webp'
import VdauRkoAUzSR from '../assets/games/553850.jpg?enhanced&format=webp'
import QAwxVKxUSmvK from '../assets/games/555160.jpg?enhanced&format=webp'
import NAiMrujqFHLD from '../assets/games/447040.jpg?enhanced&format=webp'
import EAxhkGvNeARU from '../assets/games/460920.jpg?enhanced&format=webp'
import OFiomUMlRgES from '../assets/games/564710.jpg?enhanced&format=webp'
import iqHLrvtFmMWN from '../assets/games/578080.jpg?enhanced&format=webp'
import McqWDwAueFmO from '../assets/games/578620.jpg?enhanced&format=webp'
import ONhbqgFrJRCc from '../assets/games/582660.jpg?enhanced&format=webp'
import nbcBDUDSrGGx from '../assets/games/588650.jpg?enhanced&format=webp'
import ouHBWCmcFEOx from '../assets/games/460930.jpg?enhanced&format=webp'
import BoxbGIIRGgBP from '../assets/games/611670.jpg?enhanced&format=webp'
import APliuIeqpctw from '../assets/games/617830.jpg?enhanced&format=webp'
import horBBEBcaxVd from '../assets/games/619910.jpg?enhanced&format=webp'
import CDeNiRRijqwC from '../assets/games/620980.jpg?enhanced&format=webp'
import krsTaiIxWKUD from '../assets/games/629730.jpg?enhanced&format=webp'
import rTeYjHIMNdDc from '../assets/games/632360.jpg?enhanced&format=webp'
import XutytwXSVlVx from '../assets/games/671860.jpg?enhanced&format=webp'
import WVvVZgllZqxl from '../assets/games/683320.jpg?enhanced&format=webp'
import ONeuLiawEeEP from '../assets/games/414340.jpg?enhanced&format=webp'
import dIVebfVqFqgm from '../assets/games/240720.jpg?enhanced&format=webp'
import isQafooJfXyf from '../assets/games/582160.jpg?enhanced&format=webp'
import aOPXtfhrGGxE from '../assets/games/739630.jpg?enhanced&format=webp'
import aQEryddzlZCY from '../assets/games/418370.jpg?enhanced&format=webp'
import BHGBSFYmjteX from '../assets/games/812140.jpg?enhanced&format=webp'
import RwEhLbaFqVAf from '../assets/games/552500.jpg?enhanced&format=webp'
import wQCaMQhociCI from '../assets/games/750920.jpg?enhanced&format=webp'
import MwXsgEjCKOcr from '../assets/games/858260.jpg?enhanced&format=webp'
import QuaJEQhgdgIs from '../assets/games/892970.jpg?enhanced&format=webp'
import MKGidVxiUopb from '../assets/games/899770.jpg?enhanced&format=webp'
import rgXKsQxmHxND from '../assets/games/814380.jpg?enhanced&format=webp'
import uKbBFifYqcGk from '../assets/games/993090.jpg?enhanced&format=webp'
import TXLYmUjiaOec from '../assets/games/1063730.jpg?enhanced&format=webp'
import kYEkvQtLGdzL from '../assets/games/1079800.jpg?enhanced&format=webp'
import GaqagDuAVGyU from '../assets/games/1091500.jpg?enhanced&format=webp'
import kyIdWMMNPBGP from '../assets/games/1145360.jpg?enhanced&format=webp'
import HJgCNBLMjtTp from '../assets/games/1151640.jpg?enhanced&format=webp'
import TiyjcqEIVPfK from '../assets/games/1172620.jpg?enhanced&format=webp'
import GYeBGIlakjNj from '../assets/games/1174180.jpg?enhanced&format=webp'
import GUFxklKmCOez from '../assets/games/397540.jpg?enhanced&format=webp'
import hggRQaPDxvSk from '../assets/games/582010.jpg?enhanced&format=webp'
import BAmWHudsqdMa from '../assets/games/1222670.jpg?enhanced&format=webp'
import vkYKvcyWoBer from '../assets/games/1238840.jpg?enhanced&format=webp'
import HzLUpxNvBxRQ from '../assets/games/1237950.jpg?enhanced&format=webp'
import VkOqrwhZpKyz from '../assets/games/1245620.jpg?enhanced&format=webp'
import wATogcMVQpeA from '../assets/games/1151340.jpg?enhanced&format=webp'
import puoaSzcVmULc from '../assets/games/1349230.jpg?enhanced&format=webp'
import VTllOwicgfhA from '../assets/games/1403370.jpg?enhanced&format=webp'
import tsUpwFyjjjxw from '../assets/games/1454400.jpg?enhanced&format=webp'
import unOZlkZSHdVl from '../assets/games/1468260.jpg?enhanced&format=webp'
import xBapCxAQNzDT from '../assets/games/1475810.jpg?enhanced&format=webp'
import yyGJMyUnazdc from '../assets/games/1476970.jpg?enhanced&format=webp'
import oGnfYXCScdwp from '../assets/games/1562420.jpg?enhanced&format=webp'
import FLmrmWrVmhpK from '../assets/games/1593500.jpg?enhanced&format=webp'
import RHXyXwsxOcvA from '../assets/games/1599340.jpg?enhanced&format=webp'
import kjtOcURwmusv from '../assets/games/1353300.jpg?enhanced&format=webp'
import OhVDJGnQfvzy from '../assets/games/1240440.jpg?enhanced&format=webp'
import ZCZhCkCINxnr from '../assets/games/1794680.jpg?enhanced&format=webp'
import RLfaLYMkbhlk from '../assets/games/1446780.jpg?enhanced&format=webp'
import TfyUwjPJSGQA from '../assets/games/1817070.jpg?enhanced&format=webp'
import DTYWqLLeauAr from '../assets/games/1943950.jpg?enhanced&format=webp'
import PYhqGRiGOGxJ from '../assets/games/1966720.jpg?enhanced&format=webp'
import zjUKSLMEvNce from '../assets/games/1999360.jpg?enhanced&format=webp'
import hmMlFnGfcoiu from '../assets/games/2012840.jpg?enhanced&format=webp'
import NdzyekzRyjRa from '../assets/games/1286680.jpg?enhanced&format=webp'
import NFfXshqfSxip from '../assets/games/1313140.jpg?enhanced&format=webp'
import ChAbamhAMTEG from '../assets/games/990080.jpg?enhanced&format=webp'
import cTriOGtUXIij from '../assets/games/2399830.jpg?enhanced&format=webp'
import yDrQvNQrlFcP from '../assets/games/2420110.jpg?enhanced&format=webp'
import tnLdEdZkACfe from '../assets/games/1086940.jpg?enhanced&format=webp'
import kcdaQHbZeowq from '../assets/games/1361210.jpg?enhanced&format=webp'
import BbRoIQpGitZR from '../assets/games/2840770.jpg?enhanced&format=webp'
import koMvyVqxAzqQ from '../assets/games/2561580.jpg?enhanced&format=webp'
import jilLgANooGOH from '../assets/games/2694490.jpg?enhanced&format=webp'
import QEFbdkDrlaLK from '../assets/games/440.jpg?enhanced&format=webp'
import LJeyCfEvmCHY from '../assets/games/570.jpg?enhanced&format=webp'

const gameHeroDict: Record<string, Picture> = {
	[220]: OEzihZyrGDlt,
	[4000]: uIkNoLDMxfwB,
	[2300]: cWCwumsgYbjB,
	[20900]: eOvoMOOTnxCw,
	[22300]: nAeWYwiEjdip,
	[12210]: sGWEcgVYmIAs,
	[17390]: miFKlHWcGqfO,
	[29800]: WkwHxOVzcWtp,
	[6060]: GvAEYQeZaHNG,
	[550]: AeErSuFTFmoH,
	[8190]: uvVwjQECHssR,
	[57300]: auoZVDbmjxaT,
	[8930]: fBmQMFMBNEoB,
	[40800]: QQxCddMpxFdB,
	[48190]: PtoENEjfERAF,
	[620]: zSzBaYGRiEBk,
	[105600]: rlDizcOqiFQx,
	[20920]: gfJrqqZGyYzH,
	[92100]: PaaWpbjnjAiz,
	[22230]: AUtAZIjpsHvD,
	[3830]: GInnRFkYpCfk,
	[204030]: bcBMWfIEyArd,
	[207610]: PwdRdPQeGIEp,
	[206440]: pWrWfIAWgxYu,
	[730]: tagzNzkncFQL,
	[200260]: UgDnuHAGytBv,
	[212680]: UKdXXFlGFzcd,
	[204360]: uoTIlmjVAYgu,
	[49520]: HTwIrlEqqorO,
	[200710]: NezgsPJkGFCS,
	[205100]: yTgFClCeSEjg,
	[223470]: DgsuZhmwxtqE,
	[55230]: yzORKRYpMKUE,
	[220700]: rnHtaQTiwVtr,
	[224540]: eTeJOqQpwffk,
	[200210]: YCALsGaNqEng,
	[208090]: ASCIYYjAxxsX,
	[230410]: tEtSSiAomYuL,
	[236390]: zopKpWGXAVda,
	[39000]: tOMMvzwhuGIa,
	[251670]: rVykZubpfwVr,
	[221040]: UFZUXqvqEoib,
	[203160]: NizCneEOoYCs,
	[47890]: NuGYvuaucuBH,
	[233450]: jfILLjnRdpZS,
	[233720]: vNIoJWidnwsB,
	[224760]: gIHLKKLKFDZD,
	[219740]: zuefSbcNjfEl,
	[322330]: ePwhYDEVTmZw,
	[234710]: ifCejXhUttJt,
	[72850]: vgFDpiqATMdz,
	[35720]: KkGvctDmhrsF,
	[242760]: BbEleUbbdyyH,
	[242860]: vJgslrcotPXQ,
	[242920]: DrXkjZzPiQqa,
	[244850]: mfAjEJMfoCSQ,
	[218620]: WlLbVtQyZAlU,
	[239820]: NqtmMsGuHeWM,
	[252950]: tdCWKVhGBsgT,
	[242050]: YQLRDSgiMCMY,
	[219990]: GoDsLSzqtVuO,
	[257750]: zChAniKtmSMy,
	[221910]: zoJmwwYuIsjZ,
	[209170]: aCSBHFoClYcC,
	[264140]: GCqPEAnlHiFR,
	[264710]: GYIJwNyYpvLV,
	[265930]: HtsLvqIYWJrW,
	[266010]: QKPrpvBWAwGu,
	[211820]: NJeaHvMgwfmD,
	[221100]: iKgUgGDfFDgU,
	[268910]: xZnIjXKlZmVy,
	[237870]: HEIgPExUILpC,
	[225840]: BKZsHNIuvjUF,
	[282140]: iMqaxujEVlWx,
	[287700]: MfWiTtxmOhEt,
	[292030]: gZjZuErvDwlo,
	[286160]: SrbMnNvIAeJj,
	[289130]: RmQQWCqcJMrA,
	[238460]: TqmewWIaNRxG,
	[299460]: WuPozGFWGFrf,
	[243470]: JWAyiHijoAHx,
	[304930]: sLZLNpMRRgTv,
	[306020]: AXzCjpJcDlRG,
	[9900]: FyRiBJzkeQhC,
	[311690]: YRqhzYKrovEW,
	[206420]: XQHJHfsMukuV,
	[314650]: lfljhCRvuIvl,
	[241930]: FOGbOBolAUTO,
	[322170]: fHTrJcknTIWm,
	[214490]: oymYFRfpRExy,
	[238320]: GbjZyprTVxgy,
	[327140]: CwazCzkUMujB,
	[327890]: wjIOchvwriJY,
	[261640]: TKujfUQPwIXr,
	[211420]: ZdIUdMELwLom,
	[330350]: wqimmXkvsrTE,
	[298110]: ogHsZLKTKMKo,
	[305620]: HEUIMPQBQWLc,
	[252490]: tmiqKLFltTgC,
	[250900]: iGxkAKZefGeo,
	[319630]: QMjaxiUBHYLo,
	[219150]: BKOwWdcuHZXL,
	[274170]: LnDlvlAIsFqu,
	[346010]: PdOcmSnqwHhU,
	[346110]: RaocpKLsYFXc,
	[346900]: EJEucHAJfzZr,
	[298630]: bmXpiezeXUlR,
	[255710]: QVPhwPiLLuTn,
	[306130]: ciVSJkwUltQH,
	[271590]: ifRLiXcbHKJT,
	[359050]: ytXNcXQMfQpK,
	[363970]: qHhnEKgOAUvs,
	[365720]: TJfnwejSDMQA,
	[367520]: XJzdknzzalbW,
	[375950]: KCiSAlVtAoWz,
	[377160]: wzlVBcHRTZGK,
	[384190]: cWXwZfwfmeRk,
	[391540]: sYiRyMHQziSw,
	[392110]: WMXBYsPpAQuf,
	[393380]: ogeVKrODVCty,
	[413150]: ScHmczdUKlUs,
	[225540]: NQxWUWAcuVjc,
	[417860]: olCpWEWYrqmB,
	[208650]: JByDstLiutnf,
	[420530]: HTyKbnZqrNaH,
	[391220]: ISnzzapyyIgW,
	[427520]: HTrUZzVKNjVL,
	[210970]: oZvwUgBzIfHl,
	[359550]: kwuhIuyxdWOT,
	[623990]: KaVPUfilfEct,
	[239140]: UPnAtEVSCAbd,
	[431960]: VGeVewoJIdMO,
	[434260]: SKRqMivQGpdg,
	[434570]: YxRCMrNgQVtu,
	[374320]: CSybvHVNugZh,
	[275850]: aFvIRVlCeAfu,
	[457550]: gDrBYQsOAMaY,
	[403640]: wdgmkKjuTXgK,
	[501300]: fctYphLKNYBl,
	[518790]: tlHXKMOHAlwm,
	[289070]: mUkgCDdUmsJA,
	[534380]: afLbvFNNSWxN,
	[546560]: NRzWBZpHdLlT,
	[548430]: ehItnOliZqqB,
	[489830]: CqNgEFxiPVVl,
	[553850]: VdauRkoAUzSR,
	[555160]: QAwxVKxUSmvK,
	[447040]: NAiMrujqFHLD,
	[460920]: EAxhkGvNeARU,
	[564710]: OFiomUMlRgES,
	[578080]: iqHLrvtFmMWN,
	[578620]: McqWDwAueFmO,
	[582660]: ONhbqgFrJRCc,
	[588650]: nbcBDUDSrGGx,
	[460930]: ouHBWCmcFEOx,
	[611670]: BoxbGIIRGgBP,
	[617830]: APliuIeqpctw,
	[619910]: horBBEBcaxVd,
	[620980]: CDeNiRRijqwC,
	[629730]: krsTaiIxWKUD,
	[632360]: rTeYjHIMNdDc,
	[671860]: XutytwXSVlVx,
	[683320]: WVvVZgllZqxl,
	[414340]: ONeuLiawEeEP,
	[240720]: dIVebfVqFqgm,
	[582160]: isQafooJfXyf,
	[739630]: aOPXtfhrGGxE,
	[418370]: aQEryddzlZCY,
	[812140]: BHGBSFYmjteX,
	[552500]: RwEhLbaFqVAf,
	[750920]: wQCaMQhociCI,
	[858260]: MwXsgEjCKOcr,
	[892970]: QuaJEQhgdgIs,
	[899770]: MKGidVxiUopb,
	[814380]: rgXKsQxmHxND,
	[993090]: uKbBFifYqcGk,
	[1063730]: TXLYmUjiaOec,
	[1079800]: kYEkvQtLGdzL,
	[1091500]: GaqagDuAVGyU,
	[1145360]: kyIdWMMNPBGP,
	[1151640]: HJgCNBLMjtTp,
	[1172620]: TiyjcqEIVPfK,
	[1174180]: GYeBGIlakjNj,
	[397540]: GUFxklKmCOez,
	[582010]: hggRQaPDxvSk,
	[1222670]: BAmWHudsqdMa,
	[1238840]: vkYKvcyWoBer,
	[1237950]: HzLUpxNvBxRQ,
	[1245620]: VkOqrwhZpKyz,
	[1151340]: wATogcMVQpeA,
	[1349230]: puoaSzcVmULc,
	[1403370]: VTllOwicgfhA,
	[1454400]: tsUpwFyjjjxw,
	[1468260]: unOZlkZSHdVl,
	[1475810]: xBapCxAQNzDT,
	[1476970]: yyGJMyUnazdc,
	[1562420]: oGnfYXCScdwp,
	[1593500]: FLmrmWrVmhpK,
	[1599340]: RHXyXwsxOcvA,
	[1353300]: kjtOcURwmusv,
	[1240440]: OhVDJGnQfvzy,
	[1794680]: ZCZhCkCINxnr,
	[1446780]: RLfaLYMkbhlk,
	[1817070]: TfyUwjPJSGQA,
	[1943950]: DTYWqLLeauAr,
	[1966720]: PYhqGRiGOGxJ,
	[1999360]: zjUKSLMEvNce,
	[2012840]: hmMlFnGfcoiu,
	[1286680]: NdzyekzRyjRa,
	[1313140]: NFfXshqfSxip,
	[990080]: ChAbamhAMTEG,
	[2399830]: cTriOGtUXIij,
	[2420110]: yDrQvNQrlFcP,
	[1086940]: tnLdEdZkACfe,
	[1361210]: kcdaQHbZeowq,
	[2840770]: BbRoIQpGitZR,
	[2561580]: koMvyVqxAzqQ,
	[2694490]: jilLgANooGOH,
	[440]: QEFbdkDrlaLK,
	[570]: LJeyCfEvmCHY
};

const getGameHero = (appId: number) => {
	if (gameHeroDict[appId]) {
		return gameHeroDict[appId]
	}
	return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`
}
export { getGameHero }
import stltxRWGdPSJ from '../assets/icons/220.jpg?enhanced&format=webp'
import SJbKCUxcrqWB from '../assets/icons/4000.jpg?enhanced&format=webp'
import QycUHokMRUEh from '../assets/icons/2300.jpg?enhanced&format=webp'
import KMhzUXhWIkQD from '../assets/icons/20900.jpg?enhanced&format=webp'
import DepxfajaEsOI from '../assets/icons/22300.jpg?enhanced&format=webp'
import FMYXfATILtzr from '../assets/icons/12210.jpg?enhanced&format=webp'
import UnZzyFBlrEXP from '../assets/icons/17390.jpg?enhanced&format=webp'
import cKnHhRrxKbzn from '../assets/icons/29800.jpg?enhanced&format=webp'
import dpaxKVUdwKGJ from '../assets/icons/6060.jpg?enhanced&format=webp'
import vqmglrGALixe from '../assets/icons/550.jpg?enhanced&format=webp'
import EamODnnjlveV from '../assets/icons/8190.jpg?enhanced&format=webp'
import LUVSXZcYlvdx from '../assets/icons/57300.jpg?enhanced&format=webp'
import YakrtyyOegri from '../assets/icons/8930.jpg?enhanced&format=webp'
import rfYBHdmHJwhs from '../assets/icons/40800.jpg?enhanced&format=webp'
import DbTnHyqjeAKB from '../assets/icons/48190.jpg?enhanced&format=webp'
import aErNEpDKZKWC from '../assets/icons/620.jpg?enhanced&format=webp'
import nEngaPLEmFoq from '../assets/icons/105600.jpg?enhanced&format=webp'
import yPPbJfJVLXPS from '../assets/icons/20920.jpg?enhanced&format=webp'
import yLLvUcVGrqfd from '../assets/icons/92100.jpg?enhanced&format=webp'
import NkdHsXLtLlXi from '../assets/icons/22230.jpg?enhanced&format=webp'
import ctQjewpUzzyt from '../assets/icons/3830.jpg?enhanced&format=webp'
import ngUjgTIsPQoq from '../assets/icons/204030.jpg?enhanced&format=webp'
import uKrOUiKEZnuB from '../assets/icons/207610.jpg?enhanced&format=webp'
import eVhTvnCXSnxY from '../assets/icons/206440.jpg?enhanced&format=webp'
import eDnjXfuAJMIF from '../assets/icons/730.jpg?enhanced&format=webp'
import PNyydhBiZfOV from '../assets/icons/200260.jpg?enhanced&format=webp'
import tlLzUEQQWsQX from '../assets/icons/212680.jpg?enhanced&format=webp'
import VxWVriSmmXQd from '../assets/icons/204360.jpg?enhanced&format=webp'
import wqAZyCYswPLD from '../assets/icons/49520.jpg?enhanced&format=webp'
import bKXVszFqOrZg from '../assets/icons/200710.jpg?enhanced&format=webp'
import YpgUbsxAPDCD from '../assets/icons/205100.jpg?enhanced&format=webp'
import BGLQFCZhdocR from '../assets/icons/223470.jpg?enhanced&format=webp'
import dpTVgZphartv from '../assets/icons/55230.jpg?enhanced&format=webp'
import VoibfpcribZs from '../assets/icons/220700.jpg?enhanced&format=webp'
import aglKDKoiwUln from '../assets/icons/224540.jpg?enhanced&format=webp'
import TppjwOQcuTJS from '../assets/icons/200210.jpg?enhanced&format=webp'
import HiZjZTVkdxoS from '../assets/icons/208090.jpg?enhanced&format=webp'
import adFxxTRqjFRl from '../assets/icons/230410.jpg?enhanced&format=webp'
import NoOVyspwECsa from '../assets/icons/236390.jpg?enhanced&format=webp'
import jIFNYwrdtmwo from '../assets/icons/39000.jpg?enhanced&format=webp'
import OCkzhexfEZFR from '../assets/icons/251670.jpg?enhanced&format=webp'
import ixYMxhBohmLo from '../assets/icons/221040.jpg?enhanced&format=webp'
import PuDixZDMcDwG from '../assets/icons/203160.jpg?enhanced&format=webp'
import crmQuNYoxYGi from '../assets/icons/47890.jpg?enhanced&format=webp'
import gqzQGTReIMEQ from '../assets/icons/233450.jpg?enhanced&format=webp'
import pAthKAyBxFMb from '../assets/icons/233720.jpg?enhanced&format=webp'
import LSncikBtLeni from '../assets/icons/224760.jpg?enhanced&format=webp'
import WicwUarrPYSB from '../assets/icons/219740.jpg?enhanced&format=webp'
import RANyBemwVuuh from '../assets/icons/322330.jpg?enhanced&format=webp'
import VEoukkfPkLqc from '../assets/icons/234710.jpg?enhanced&format=webp'
import TgFoUASbOGxx from '../assets/icons/72850.jpg?enhanced&format=webp'
import kZPdnIAKnSbB from '../assets/icons/35720.jpg?enhanced&format=webp'
import zyQZICycJHsc from '../assets/icons/242760.jpg?enhanced&format=webp'
import RiDjzhpWnRJy from '../assets/icons/242860.jpg?enhanced&format=webp'
import FXGcfcXlGuQV from '../assets/icons/242920.jpg?enhanced&format=webp'
import PBpuiTSsZQee from '../assets/icons/244850.jpg?enhanced&format=webp'
import bwPlZACGBrJI from '../assets/icons/218620.jpg?enhanced&format=webp'
import eHiaCeGUKveE from '../assets/icons/239820.jpg?enhanced&format=webp'
import yMEiHcRATBTD from '../assets/icons/252950.jpg?enhanced&format=webp'
import ZxBCxdVHZYQH from '../assets/icons/242050.jpg?enhanced&format=webp'
import qxyemiWOEmuY from '../assets/icons/219990.jpg?enhanced&format=webp'
import nXmygmylwxYj from '../assets/icons/257750.jpg?enhanced&format=webp'
import YXbLSFsGDJxI from '../assets/icons/221910.jpg?enhanced&format=webp'
import xXjyTpWPgXqZ from '../assets/icons/209170.jpg?enhanced&format=webp'
import EtolBWXmfjbe from '../assets/icons/264140.jpg?enhanced&format=webp'
import VDWCEyxwYNVc from '../assets/icons/264710.jpg?enhanced&format=webp'
import HDhxQlrtXeBa from '../assets/icons/265930.jpg?enhanced&format=webp'
import ltvOmReiCWjZ from '../assets/icons/266010.jpg?enhanced&format=webp'
import WhpdXzskOgJx from '../assets/icons/211820.jpg?enhanced&format=webp'
import SqMwvLdsJUPd from '../assets/icons/221100.jpg?enhanced&format=webp'
import gtlvtYwxEBMk from '../assets/icons/268910.jpg?enhanced&format=webp'
import SdbICWzsTHno from '../assets/icons/237870.jpg?enhanced&format=webp'
import jXBvqvqbzGlN from '../assets/icons/225840.jpg?enhanced&format=webp'
import etMGTkeaYLoV from '../assets/icons/282140.jpg?enhanced&format=webp'
import BrLosuhVKCEk from '../assets/icons/287700.jpg?enhanced&format=webp'
import fFKjahQmMgmJ from '../assets/icons/292030.jpg?enhanced&format=webp'
import jiPOAONDFPtj from '../assets/icons/286160.jpg?enhanced&format=webp'
import haAwjdBVWtiV from '../assets/icons/289130.jpg?enhanced&format=webp'
import AdeifcJcLGhW from '../assets/icons/238460.jpg?enhanced&format=webp'
import jRzUbBDtsCcK from '../assets/icons/299460.jpg?enhanced&format=webp'
import MrXdvdAlDSPH from '../assets/icons/243470.jpg?enhanced&format=webp'
import plmnGrgSBNwR from '../assets/icons/304930.jpg?enhanced&format=webp'
import sGrSVEUqugPK from '../assets/icons/306020.jpg?enhanced&format=webp'
import gWPvFqOIMwYd from '../assets/icons/9900.jpg?enhanced&format=webp'
import eBnHVFNMWHcE from '../assets/icons/311690.jpg?enhanced&format=webp'
import TtCnNLHeJTAI from '../assets/icons/206420.jpg?enhanced&format=webp'
import TeYQViXeCCAZ from '../assets/icons/314650.jpg?enhanced&format=webp'
import IATcYmHnOfAi from '../assets/icons/241930.jpg?enhanced&format=webp'
import AjslOjleYuip from '../assets/icons/322170.jpg?enhanced&format=webp'
import wEJZdYwqTkOw from '../assets/icons/214490.jpg?enhanced&format=webp'
import xzbYngCChzSc from '../assets/icons/238320.jpg?enhanced&format=webp'
import URYIQMLgpyLg from '../assets/icons/327140.jpg?enhanced&format=webp'
import kGLflEGBIQjD from '../assets/icons/327890.jpg?enhanced&format=webp'
import oqoRIeaHKEGl from '../assets/icons/261640.jpg?enhanced&format=webp'
import cvOdRFMYNHZz from '../assets/icons/211420.jpg?enhanced&format=webp'
import reVWTTDawTKG from '../assets/icons/330350.jpg?enhanced&format=webp'
import NOlFQUqjIfZh from '../assets/icons/298110.jpg?enhanced&format=webp'
import UxCGkXmGMeMj from '../assets/icons/305620.jpg?enhanced&format=webp'
import wxcEFIcmWrIA from '../assets/icons/252490.jpg?enhanced&format=webp'
import TZjKHnnaaZLN from '../assets/icons/250900.jpg?enhanced&format=webp'
import XKnCNtBbOvft from '../assets/icons/319630.jpg?enhanced&format=webp'
import XZTvOjIxUSUf from '../assets/icons/219150.jpg?enhanced&format=webp'
import nkOkhHhTsGVy from '../assets/icons/274170.jpg?enhanced&format=webp'
import PeiMMYlINdIa from '../assets/icons/346010.jpg?enhanced&format=webp'
import BnslktNaBhIu from '../assets/icons/346110.jpg?enhanced&format=webp'
import vsdiUoGZUfXi from '../assets/icons/346900.jpg?enhanced&format=webp'
import pTTrAxalZgqK from '../assets/icons/298630.jpg?enhanced&format=webp'
import yMhBjRaFUVdY from '../assets/icons/255710.jpg?enhanced&format=webp'
import vlNGdbOSZoCA from '../assets/icons/306130.jpg?enhanced&format=webp'
import JTFTTnNkGJIY from '../assets/icons/271590.jpg?enhanced&format=webp'
import qWvxooFcjidw from '../assets/icons/359050.jpg?enhanced&format=webp'
import YEQkeOasOKZZ from '../assets/icons/363970.jpg?enhanced&format=webp'
import cFuOvHsJMECo from '../assets/icons/365720.jpg?enhanced&format=webp'
import oFYvlSLPZUZv from '../assets/icons/367520.jpg?enhanced&format=webp'
import oYMnthsjEPrg from '../assets/icons/375950.jpg?enhanced&format=webp'
import PSRxBveFgXsE from '../assets/icons/377160.jpg?enhanced&format=webp'
import RgxrlBkuKmSZ from '../assets/icons/384190.jpg?enhanced&format=webp'
import NyNEWWxGhdRg from '../assets/icons/391540.jpg?enhanced&format=webp'
import eipJemVRPxLo from '../assets/icons/392110.jpg?enhanced&format=webp'
import wnOaYXmsZgJu from '../assets/icons/393380.jpg?enhanced&format=webp'
import thOZQUWQWlOi from '../assets/icons/413150.jpg?enhanced&format=webp'
import lKVVTOADkDUs from '../assets/icons/225540.jpg?enhanced&format=webp'
import aicpuqHRzmbI from '../assets/icons/417860.jpg?enhanced&format=webp'
import sCHKZDDaWnMJ from '../assets/icons/208650.jpg?enhanced&format=webp'
import xyxSTTlxyBzH from '../assets/icons/420530.jpg?enhanced&format=webp'
import vrMfBKnXzeLy from '../assets/icons/391220.jpg?enhanced&format=webp'
import jXlufdjzgnAV from '../assets/icons/427520.jpg?enhanced&format=webp'
import GBjXuvDiJMHu from '../assets/icons/210970.jpg?enhanced&format=webp'
import PiVIKBQsaZhw from '../assets/icons/359550.jpg?enhanced&format=webp'
import zejkdAUZOONS from '../assets/icons/623990.jpg?enhanced&format=webp'
import tUmFSTmwfFAw from '../assets/icons/239140.jpg?enhanced&format=webp'
import EDLyCJWcRCrD from '../assets/icons/431960.jpg?enhanced&format=webp'
import THLDzIoudmlM from '../assets/icons/434260.jpg?enhanced&format=webp'
import TAJOBnhlWKXu from '../assets/icons/434570.jpg?enhanced&format=webp'
import gOzzYWImmLHv from '../assets/icons/374320.jpg?enhanced&format=webp'
import IiwssJydjYWv from '../assets/icons/275850.jpg?enhanced&format=webp'
import dSUYGAIOGQjz from '../assets/icons/457550.jpg?enhanced&format=webp'
import EZBQEoCNutdM from '../assets/icons/403640.jpg?enhanced&format=webp'
import rbldshevrGTU from '../assets/icons/501300.jpg?enhanced&format=webp'
import JcjkfOZaGWgG from '../assets/icons/518790.jpg?enhanced&format=webp'
import BghndzymxBbg from '../assets/icons/289070.jpg?enhanced&format=webp'
import iLNUnYGXByjD from '../assets/icons/534380.jpg?enhanced&format=webp'
import JNAwNgqswaCr from '../assets/icons/546560.jpg?enhanced&format=webp'
import VGcBszVJceHQ from '../assets/icons/548430.jpg?enhanced&format=webp'
import NKCURcjwjlhS from '../assets/icons/489830.jpg?enhanced&format=webp'
import iFhnxxDZnfqL from '../assets/icons/553850.jpg?enhanced&format=webp'
import ZVyRmPGnKJDa from '../assets/icons/555160.jpg?enhanced&format=webp'
import pofeapiSRxLJ from '../assets/icons/447040.jpg?enhanced&format=webp'
import BdwORWtCbPBY from '../assets/icons/460920.jpg?enhanced&format=webp'
import ScFbzCjUjoej from '../assets/icons/564710.jpg?enhanced&format=webp'
import zHLYGkMlnMdR from '../assets/icons/578080.jpg?enhanced&format=webp'
import amWQmTGLKonQ from '../assets/icons/578620.jpg?enhanced&format=webp'
import ozfdpKUfmRop from '../assets/icons/582660.jpg?enhanced&format=webp'
import pLCsiMSwguzM from '../assets/icons/588650.jpg?enhanced&format=webp'
import vyMrIKjmZnqy from '../assets/icons/460930.jpg?enhanced&format=webp'
import GJfFCkgbnwGX from '../assets/icons/611670.jpg?enhanced&format=webp'
import DkMqupCmUtsN from '../assets/icons/617830.jpg?enhanced&format=webp'
import CQmzgKJjhOaA from '../assets/icons/619910.jpg?enhanced&format=webp'
import GcUynTZhJqXe from '../assets/icons/620980.jpg?enhanced&format=webp'
import ASmwlPuXXJXL from '../assets/icons/629730.jpg?enhanced&format=webp'
import GubqHdldgoEp from '../assets/icons/632360.jpg?enhanced&format=webp'
import GAbQslZGqcTV from '../assets/icons/671860.jpg?enhanced&format=webp'
import YdmqxKJIgtQg from '../assets/icons/683320.jpg?enhanced&format=webp'
import eEZyCIzsXijE from '../assets/icons/414340.jpg?enhanced&format=webp'
import nqRkAVTjulSD from '../assets/icons/240720.jpg?enhanced&format=webp'
import TuOqBZAwnTPh from '../assets/icons/582160.jpg?enhanced&format=webp'
import thYWtDIOANjw from '../assets/icons/739630.jpg?enhanced&format=webp'
import OHdkZGpdJlRz from '../assets/icons/418370.jpg?enhanced&format=webp'
import RLGnZIGxWrBI from '../assets/icons/812140.jpg?enhanced&format=webp'
import RIMyTrWNvgCp from '../assets/icons/552500.jpg?enhanced&format=webp'
import ApcJRULbHFgO from '../assets/icons/750920.jpg?enhanced&format=webp'
import MVbodcyfVLNr from '../assets/icons/858260.jpg?enhanced&format=webp'
import QbAExJkzOxRh from '../assets/icons/892970.jpg?enhanced&format=webp'
import LXezHJzfJxOi from '../assets/icons/899770.jpg?enhanced&format=webp'
import QBQEWDclPsQF from '../assets/icons/814380.jpg?enhanced&format=webp'
import MvfonGKvkYab from '../assets/icons/993090.jpg?enhanced&format=webp'
import foXanRmTNLbU from '../assets/icons/1063730.jpg?enhanced&format=webp'
import fuYazSfMkrJB from '../assets/icons/1079800.jpg?enhanced&format=webp'
import UdtMhYpsiGZT from '../assets/icons/1091500.jpg?enhanced&format=webp'
import slSrhPcufbjm from '../assets/icons/1145360.jpg?enhanced&format=webp'
import kdDMcpMWutkq from '../assets/icons/1151640.jpg?enhanced&format=webp'
import NKmqjZrwYChX from '../assets/icons/1172620.jpg?enhanced&format=webp'
import XMovhYyXqYAa from '../assets/icons/1174180.jpg?enhanced&format=webp'
import mKExsuVlpsxl from '../assets/icons/397540.jpg?enhanced&format=webp'
import hwyHJeSedkcB from '../assets/icons/582010.jpg?enhanced&format=webp'
import CIsbBylFcsHU from '../assets/icons/1222670.jpg?enhanced&format=webp'
import NUNctkZcVLpy from '../assets/icons/1238840.jpg?enhanced&format=webp'
import xXwtjleDHtlA from '../assets/icons/1237950.jpg?enhanced&format=webp'
import FwaWXzkjyavw from '../assets/icons/1245620.jpg?enhanced&format=webp'
import vFPBZIIbOerq from '../assets/icons/1151340.jpg?enhanced&format=webp'
import xrNCFiJaHtyM from '../assets/icons/1349230.jpg?enhanced&format=webp'
import VuiRSAicoGmG from '../assets/icons/1403370.jpg?enhanced&format=webp'
import zoCTrhtxIUQJ from '../assets/icons/1454400.jpg?enhanced&format=webp'
import adaqnMyuMrIi from '../assets/icons/1468260.jpg?enhanced&format=webp'
import ctAzSifqsafo from '../assets/icons/1475810.jpg?enhanced&format=webp'
import TXXITFOLqTgd from '../assets/icons/1476970.jpg?enhanced&format=webp'
import qzinECgdzrot from '../assets/icons/1562420.jpg?enhanced&format=webp'
import AUepxgGmMMYD from '../assets/icons/1593500.jpg?enhanced&format=webp'
import hrwxsRjXDfhK from '../assets/icons/1599340.jpg?enhanced&format=webp'
import ahDEeCFRzfmc from '../assets/icons/1353300.jpg?enhanced&format=webp'
import LBGeLDHfMQUu from '../assets/icons/1240440.jpg?enhanced&format=webp'
import XTveUusVjgvA from '../assets/icons/1794680.jpg?enhanced&format=webp'
import qKBlwNFwtzKy from '../assets/icons/1446780.jpg?enhanced&format=webp'
import SRLZJvDmXFnQ from '../assets/icons/1817070.jpg?enhanced&format=webp'
import DKxvJCygheBK from '../assets/icons/1943950.jpg?enhanced&format=webp'
import pQxItjozlhmb from '../assets/icons/1966720.jpg?enhanced&format=webp'
import ghoHbEZFUMHd from '../assets/icons/1999360.jpg?enhanced&format=webp'
import CsQiyqyJFCOa from '../assets/icons/2012840.jpg?enhanced&format=webp'
import ZpboJrSxZPxP from '../assets/icons/1286680.jpg?enhanced&format=webp'
import LjvjjuyxTGIt from '../assets/icons/1313140.jpg?enhanced&format=webp'
import oAMyvKWGmtod from '../assets/icons/990080.jpg?enhanced&format=webp'
import acpJLgqoodVl from '../assets/icons/2399830.jpg?enhanced&format=webp'
import hOptpTMMBrIy from '../assets/icons/2420110.jpg?enhanced&format=webp'
import JZDamzJUtZiu from '../assets/icons/1086940.jpg?enhanced&format=webp'
import SNsdwSLOBlOU from '../assets/icons/1361210.jpg?enhanced&format=webp'
import WFXvumBPqdgD from '../assets/icons/2840770.jpg?enhanced&format=webp'
import OJBIWKsBpyOA from '../assets/icons/2561580.jpg?enhanced&format=webp'
import NaijCqiRpgNv from '../assets/icons/2694490.jpg?enhanced&format=webp'
import ReYGlveOhybf from '../assets/icons/440.jpg?enhanced&format=webp'
import EUKYHcMFViYl from '../assets/icons/570.jpg?enhanced&format=webp'

const gameIconDict: Record<string, Picture> = {
	[220]: stltxRWGdPSJ,
	[4000]: SJbKCUxcrqWB,
	[2300]: QycUHokMRUEh,
	[20900]: KMhzUXhWIkQD,
	[22300]: DepxfajaEsOI,
	[12210]: FMYXfATILtzr,
	[17390]: UnZzyFBlrEXP,
	[29800]: cKnHhRrxKbzn,
	[6060]: dpaxKVUdwKGJ,
	[550]: vqmglrGALixe,
	[8190]: EamODnnjlveV,
	[57300]: LUVSXZcYlvdx,
	[8930]: YakrtyyOegri,
	[40800]: rfYBHdmHJwhs,
	[48190]: DbTnHyqjeAKB,
	[620]: aErNEpDKZKWC,
	[105600]: nEngaPLEmFoq,
	[20920]: yPPbJfJVLXPS,
	[92100]: yLLvUcVGrqfd,
	[22230]: NkdHsXLtLlXi,
	[3830]: ctQjewpUzzyt,
	[204030]: ngUjgTIsPQoq,
	[207610]: uKrOUiKEZnuB,
	[206440]: eVhTvnCXSnxY,
	[730]: eDnjXfuAJMIF,
	[200260]: PNyydhBiZfOV,
	[212680]: tlLzUEQQWsQX,
	[204360]: VxWVriSmmXQd,
	[49520]: wqAZyCYswPLD,
	[200710]: bKXVszFqOrZg,
	[205100]: YpgUbsxAPDCD,
	[223470]: BGLQFCZhdocR,
	[55230]: dpTVgZphartv,
	[220700]: VoibfpcribZs,
	[224540]: aglKDKoiwUln,
	[200210]: TppjwOQcuTJS,
	[208090]: HiZjZTVkdxoS,
	[230410]: adFxxTRqjFRl,
	[236390]: NoOVyspwECsa,
	[39000]: jIFNYwrdtmwo,
	[251670]: OCkzhexfEZFR,
	[221040]: ixYMxhBohmLo,
	[203160]: PuDixZDMcDwG,
	[47890]: crmQuNYoxYGi,
	[233450]: gqzQGTReIMEQ,
	[233720]: pAthKAyBxFMb,
	[224760]: LSncikBtLeni,
	[219740]: WicwUarrPYSB,
	[322330]: RANyBemwVuuh,
	[234710]: VEoukkfPkLqc,
	[72850]: TgFoUASbOGxx,
	[35720]: kZPdnIAKnSbB,
	[242760]: zyQZICycJHsc,
	[242860]: RiDjzhpWnRJy,
	[242920]: FXGcfcXlGuQV,
	[244850]: PBpuiTSsZQee,
	[218620]: bwPlZACGBrJI,
	[239820]: eHiaCeGUKveE,
	[252950]: yMEiHcRATBTD,
	[242050]: ZxBCxdVHZYQH,
	[219990]: qxyemiWOEmuY,
	[257750]: nXmygmylwxYj,
	[221910]: YXbLSFsGDJxI,
	[209170]: xXjyTpWPgXqZ,
	[264140]: EtolBWXmfjbe,
	[264710]: VDWCEyxwYNVc,
	[265930]: HDhxQlrtXeBa,
	[266010]: ltvOmReiCWjZ,
	[211820]: WhpdXzskOgJx,
	[221100]: SqMwvLdsJUPd,
	[268910]: gtlvtYwxEBMk,
	[237870]: SdbICWzsTHno,
	[225840]: jXBvqvqbzGlN,
	[282140]: etMGTkeaYLoV,
	[287700]: BrLosuhVKCEk,
	[292030]: fFKjahQmMgmJ,
	[286160]: jiPOAONDFPtj,
	[289130]: haAwjdBVWtiV,
	[238460]: AdeifcJcLGhW,
	[299460]: jRzUbBDtsCcK,
	[243470]: MrXdvdAlDSPH,
	[304930]: plmnGrgSBNwR,
	[306020]: sGrSVEUqugPK,
	[9900]: gWPvFqOIMwYd,
	[311690]: eBnHVFNMWHcE,
	[206420]: TtCnNLHeJTAI,
	[314650]: TeYQViXeCCAZ,
	[241930]: IATcYmHnOfAi,
	[322170]: AjslOjleYuip,
	[214490]: wEJZdYwqTkOw,
	[238320]: xzbYngCChzSc,
	[327140]: URYIQMLgpyLg,
	[327890]: kGLflEGBIQjD,
	[261640]: oqoRIeaHKEGl,
	[211420]: cvOdRFMYNHZz,
	[330350]: reVWTTDawTKG,
	[298110]: NOlFQUqjIfZh,
	[305620]: UxCGkXmGMeMj,
	[252490]: wxcEFIcmWrIA,
	[250900]: TZjKHnnaaZLN,
	[319630]: XKnCNtBbOvft,
	[219150]: XZTvOjIxUSUf,
	[274170]: nkOkhHhTsGVy,
	[346010]: PeiMMYlINdIa,
	[346110]: BnslktNaBhIu,
	[346900]: vsdiUoGZUfXi,
	[298630]: pTTrAxalZgqK,
	[255710]: yMhBjRaFUVdY,
	[306130]: vlNGdbOSZoCA,
	[271590]: JTFTTnNkGJIY,
	[359050]: qWvxooFcjidw,
	[363970]: YEQkeOasOKZZ,
	[365720]: cFuOvHsJMECo,
	[367520]: oFYvlSLPZUZv,
	[375950]: oYMnthsjEPrg,
	[377160]: PSRxBveFgXsE,
	[384190]: RgxrlBkuKmSZ,
	[391540]: NyNEWWxGhdRg,
	[392110]: eipJemVRPxLo,
	[393380]: wnOaYXmsZgJu,
	[413150]: thOZQUWQWlOi,
	[225540]: lKVVTOADkDUs,
	[417860]: aicpuqHRzmbI,
	[208650]: sCHKZDDaWnMJ,
	[420530]: xyxSTTlxyBzH,
	[391220]: vrMfBKnXzeLy,
	[427520]: jXlufdjzgnAV,
	[210970]: GBjXuvDiJMHu,
	[359550]: PiVIKBQsaZhw,
	[623990]: zejkdAUZOONS,
	[239140]: tUmFSTmwfFAw,
	[431960]: EDLyCJWcRCrD,
	[434260]: THLDzIoudmlM,
	[434570]: TAJOBnhlWKXu,
	[374320]: gOzzYWImmLHv,
	[275850]: IiwssJydjYWv,
	[457550]: dSUYGAIOGQjz,
	[403640]: EZBQEoCNutdM,
	[501300]: rbldshevrGTU,
	[518790]: JcjkfOZaGWgG,
	[289070]: BghndzymxBbg,
	[534380]: iLNUnYGXByjD,
	[546560]: JNAwNgqswaCr,
	[548430]: VGcBszVJceHQ,
	[489830]: NKCURcjwjlhS,
	[553850]: iFhnxxDZnfqL,
	[555160]: ZVyRmPGnKJDa,
	[447040]: pofeapiSRxLJ,
	[460920]: BdwORWtCbPBY,
	[564710]: ScFbzCjUjoej,
	[578080]: zHLYGkMlnMdR,
	[578620]: amWQmTGLKonQ,
	[582660]: ozfdpKUfmRop,
	[588650]: pLCsiMSwguzM,
	[460930]: vyMrIKjmZnqy,
	[611670]: GJfFCkgbnwGX,
	[617830]: DkMqupCmUtsN,
	[619910]: CQmzgKJjhOaA,
	[620980]: GcUynTZhJqXe,
	[629730]: ASmwlPuXXJXL,
	[632360]: GubqHdldgoEp,
	[671860]: GAbQslZGqcTV,
	[683320]: YdmqxKJIgtQg,
	[414340]: eEZyCIzsXijE,
	[240720]: nqRkAVTjulSD,
	[582160]: TuOqBZAwnTPh,
	[739630]: thYWtDIOANjw,
	[418370]: OHdkZGpdJlRz,
	[812140]: RLGnZIGxWrBI,
	[552500]: RIMyTrWNvgCp,
	[750920]: ApcJRULbHFgO,
	[858260]: MVbodcyfVLNr,
	[892970]: QbAExJkzOxRh,
	[899770]: LXezHJzfJxOi,
	[814380]: QBQEWDclPsQF,
	[993090]: MvfonGKvkYab,
	[1063730]: foXanRmTNLbU,
	[1079800]: fuYazSfMkrJB,
	[1091500]: UdtMhYpsiGZT,
	[1145360]: slSrhPcufbjm,
	[1151640]: kdDMcpMWutkq,
	[1172620]: NKmqjZrwYChX,
	[1174180]: XMovhYyXqYAa,
	[397540]: mKExsuVlpsxl,
	[582010]: hwyHJeSedkcB,
	[1222670]: CIsbBylFcsHU,
	[1238840]: NUNctkZcVLpy,
	[1237950]: xXwtjleDHtlA,
	[1245620]: FwaWXzkjyavw,
	[1151340]: vFPBZIIbOerq,
	[1349230]: xrNCFiJaHtyM,
	[1403370]: VuiRSAicoGmG,
	[1454400]: zoCTrhtxIUQJ,
	[1468260]: adaqnMyuMrIi,
	[1475810]: ctAzSifqsafo,
	[1476970]: TXXITFOLqTgd,
	[1562420]: qzinECgdzrot,
	[1593500]: AUepxgGmMMYD,
	[1599340]: hrwxsRjXDfhK,
	[1353300]: ahDEeCFRzfmc,
	[1240440]: LBGeLDHfMQUu,
	[1794680]: XTveUusVjgvA,
	[1446780]: qKBlwNFwtzKy,
	[1817070]: SRLZJvDmXFnQ,
	[1943950]: DKxvJCygheBK,
	[1966720]: pQxItjozlhmb,
	[1999360]: ghoHbEZFUMHd,
	[2012840]: CsQiyqyJFCOa,
	[1286680]: ZpboJrSxZPxP,
	[1313140]: LjvjjuyxTGIt,
	[990080]: oAMyvKWGmtod,
	[2399830]: acpJLgqoodVl,
	[2420110]: hOptpTMMBrIy,
	[1086940]: JZDamzJUtZiu,
	[1361210]: SNsdwSLOBlOU,
	[2840770]: WFXvumBPqdgD,
	[2561580]: OJBIWKsBpyOA,
	[2694490]: NaijCqiRpgNv,
	[440]: ReYGlveOhybf,
	[570]: EUKYHcMFViYl
};

const getGameIcon = (appId: number, icon_url: string) => {
	if (gameIconDict[appId]) {
		return gameIconDict[appId]
	}
	return `https://media.steampowered.com/steamcommunity/public/images/apps/${appId}/${icon_url}.jpg`
}
export { getGameIcon }
import KJZfFqJtaYrl from '../assets/profile_pictures/c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg?enhanced&format=webp&w=64;128;200'
import OLQkmZAamBfx from '../assets/profile_pictures/cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg?enhanced&format=webp&w=64;128;200'
import ONKjeAJDCZca from '../assets/profile_pictures/7ed4ace4db81e7c1870f8af8452b4aa51eab39bf_full.jpg?enhanced&format=webp&w=64;128;200'
import LgsrYcIKAsSl from '../assets/profile_pictures/e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg?enhanced&format=webp&w=64;128;200'
import acPsuyezawiq from '../assets/profile_pictures/203dfa2c44bce6446016a7444da7647838544183_full.jpg?enhanced&format=webp&w=64;128;200'
import BrvbHAOxpmMC from '../assets/profile_pictures/9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg?enhanced&format=webp&w=64;128;200'
import gKpHGtlaywpL from '../assets/profile_pictures/7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg?enhanced&format=webp&w=64;128;200'
import EqKiUSLpIvxo from '../assets/profile_pictures/027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg?enhanced&format=webp&w=64;128;200'
import QxsBmUoQrGCK from '../assets/profile_pictures/c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg?enhanced&format=webp&w=64;128;200'
import FrchyAJqSQtU from '../assets/profile_pictures/de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg?enhanced&format=webp&w=64;128;200'
import HdpgfHXuzybE from '../assets/profile_pictures/11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg?enhanced&format=webp&w=64;128;200'
import GjcdoQbcFDBk from '../assets/profile_pictures/2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg?enhanced&format=webp&w=64;128;200'
import xzbdUKdxOUbM from '../assets/profile_pictures/83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg?enhanced&format=webp&w=64;128;200'
import WLVHcUftXrNH from '../assets/profile_pictures/efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg?enhanced&format=webp&w=64;128;200'
import rDqFTXGQMIVn from '../assets/profile_pictures/cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg?enhanced&format=webp&w=64;128;200'
import LLrOEsGbAQUu from '../assets/profile_pictures/81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg?enhanced&format=webp&w=64;128;200'
import CybNZWlbhyQy from '../assets/profile_pictures/a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg?enhanced&format=webp&w=64;128;200'
import PVfsLEhJzaFq from '../assets/profile_pictures/a95b3c96103a59a0dd548f56678b9e10d6c8e4e2_full.jpg?enhanced&format=webp&w=64;128;200'
import eTzOZKoMMGXu from '../assets/profile_pictures/cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg?enhanced&format=webp&w=64;128;200'
import PirghdXPOtdE from '../assets/profile_pictures/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg?enhanced&format=webp&w=64;128;200'
import TIjOqnPOtsLW from '../assets/profile_pictures/2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg?enhanced&format=webp&w=64;128;200'
import lQOfPMuIATpq from '../assets/profile_pictures/543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg?enhanced&format=webp&w=64;128;200'
import FvdXNSUiTLqa from '../assets/profile_pictures/129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg?enhanced&format=webp&w=64;128;200'
import WbHGdFSnfEvX from '../assets/profile_pictures/52bfe6828f7cc88655757907064a1e9533425083_full.jpg?enhanced&format=webp&w=64;128;200'
import ICsUUEDuMwPI from '../assets/profile_pictures/9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg?enhanced&format=webp&w=64;128;200'
import vOzHVRIUwKEk from '../assets/profile_pictures/6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg?enhanced&format=webp&w=64;128;200'
import AdZpWvrRYtVp from '../assets/profile_pictures/7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg?enhanced&format=webp&w=64;128;200'
import YxMafgqcKhBE from '../assets/profile_pictures/4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg?enhanced&format=webp&w=64;128;200'
import xLboOoGuYjEA from '../assets/profile_pictures/c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg?enhanced&format=webp&w=64;128;200'
import AEkSKWuKWDiE from '../assets/profile_pictures/5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg?enhanced&format=webp&w=64;128;200'
import DbptxaDgEQxl from '../assets/profile_pictures/0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg?enhanced&format=webp&w=64;128;200'
import uCxqHdywxwYv from '../assets/profile_pictures/56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg?enhanced&format=webp&w=64;128;200'
import CcwvQRNQUSDZ from '../assets/profile_pictures/360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg?enhanced&format=webp&w=64;128;200'
import UyHYyIfeqOvB from '../assets/profile_pictures/a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg?enhanced&format=webp&w=64;128;200'
import MJpmGxUhjdss from '../assets/profile_pictures/049116dc3827584518d1124b90aa06b7fab8d023_full.jpg?enhanced&format=webp&w=64;128;200'
import qJSNyvxNsvji from '../assets/profile_pictures/834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg?enhanced&format=webp&w=64;128;200'
import uFFTrIGtyyVL from '../assets/profile_pictures/acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg?enhanced&format=webp&w=64;128;200'
import iuMphdOeRJxe from '../assets/profile_pictures/a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg?enhanced&format=webp&w=64;128;200'
import IIGezHhZTqEB from '../assets/profile_pictures/7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg?enhanced&format=webp&w=64;128;200'
import rYZSYWuTbfBg from '../assets/profile_pictures/420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg?enhanced&format=webp&w=64;128;200'
import zvrjOxJVPZkF from '../assets/profile_pictures/f3374dbf1b98756714199c27cd68c21cf76115b3_full.jpg?enhanced&format=webp&w=64;128;200'
import uGZTlUpwdLkY from '../assets/profile_pictures/d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg?enhanced&format=webp&w=64;128;200'
import HSPnYKVAMkEA from '../assets/profile_pictures/70a266321c29018e4f66699399582f240e3235a1_full.jpg?enhanced&format=webp&w=64;128;200'
import nJGOqBfuohOk from '../assets/profile_pictures/8879e59d4428c411c61e108f3d647dd13540d80d_full.jpg?enhanced&format=webp&w=64;128;200'
import mYCRPcIbAqFf from '../assets/profile_pictures/5f6d8e360a7b54658b89fdb0938c3415ba5ebbb4_full.jpg?enhanced&format=webp&w=64;128;200'
import FCQZhZCwfvYy from '../assets/profile_pictures/26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg?enhanced&format=webp&w=64;128;200'
import UhTwspxiqlCj from '../assets/profile_pictures/f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg?enhanced&format=webp&w=64;128;200'
import zFGBVlzeyduW from '../assets/profile_pictures/0828e6eb804f312f914c446070331a35630b5d60_full.jpg?enhanced&format=webp&w=64;128;200'
import hvrIGfsbzRWM from '../assets/profile_pictures/bb056dd750e1444aee38309fc04c139a5948c077_full.jpg?enhanced&format=webp&w=64;128;200'
import bMQSnlcOhOqk from '../assets/profile_pictures/f4f2fc58620a769dfcc51defda89ed5cb8fa7d75_full.jpg?enhanced&format=webp&w=64;128;200'
import QLdhlTgXxuMS from '../assets/profile_pictures/52a9de1668a398d4dc400b8f225c5374034e9d82_full.jpg?enhanced&format=webp&w=64;128;200'
import eyTZZxxOOdtV from '../assets/profile_pictures/7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg?enhanced&format=webp&w=64;128;200'
import WyALMXzCuDjP from '../assets/profile_pictures/e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg?enhanced&format=webp&w=64;128;200'
import GgbDNRGBITfV from '../assets/profile_pictures/c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg?enhanced&format=webp&w=64;128;200'
import nluraYJANcMo from '../assets/profile_pictures/79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg?enhanced&format=webp&w=64;128;200'
import zeGoRhSMGDqz from '../assets/profile_pictures/a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg?enhanced&format=webp&w=64;128;200'
import QjoliOygxlwP from '../assets/profile_pictures/b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg?enhanced&format=webp&w=64;128;200'
import YJQtUyqNsEXA from '../assets/profile_pictures/fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg?enhanced&format=webp&w=64;128;200'
import IAXZJMzDJFMr from '../assets/profile_pictures/9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg?enhanced&format=webp&w=64;128;200'
import ftBQofgnEQvT from '../assets/profile_pictures/943df69df7a93f95109bac568dcd20e416622838_full.jpg?enhanced&format=webp&w=64;128;200'
import NFiayRoAAJix from '../assets/profile_pictures/576a072e6da81175e6b47f000010d843bca92fd7_full.jpg?enhanced&format=webp&w=64;128;200'
import rsoVedPkKwjA from '../assets/profile_pictures/ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg?enhanced&format=webp&w=64;128;200'
import CSZIUmDkTONZ from '../assets/profile_pictures/330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg?enhanced&format=webp&w=64;128;200'
import bejgLyuepvjn from '../assets/profile_pictures/9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg?enhanced&format=webp&w=64;128;200'
import wDyJlUyrcrCR from '../assets/profile_pictures/cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg?enhanced&format=webp&w=64;128;200'
import nQAsniVZqACs from '../assets/profile_pictures/6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg?enhanced&format=webp&w=64;128;200'
import zrFePopYEuhW from '../assets/profile_pictures/f924231652dc74192753cb3aea5ba883e9a843ff_full.jpg?enhanced&format=webp&w=64;128;200'
import cYMuJIyZfjDs from '../assets/profile_pictures/56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg?enhanced&format=webp&w=64;128;200'
import QqjBnoAsaezU from '../assets/profile_pictures/618bfa7e8477cee17e56637af632fef4e31724b2_full.jpg?enhanced&format=webp&w=64;128;200'
import gaqHMjvXprBg from '../assets/profile_pictures/7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg?enhanced&format=webp&w=64;128;200'
import npgmBZUvJfYM from '../assets/profile_pictures/65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg?enhanced&format=webp&w=64;128;200'
import rAVZvxKnEyZJ from '../assets/profile_pictures/49acdd7acab28c9344ec286e4dae713098043b02_full.jpg?enhanced&format=webp&w=64;128;200'
import yvRCylhlVuFB from '../assets/profile_pictures/83764e067f3ee3bc0be68d65f4169c80d142b7af_full.jpg?enhanced&format=webp&w=64;128;200'
import XVPhbmpAkCqX from '../assets/profile_pictures/37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg?enhanced&format=webp&w=64;128;200'
import IUzKKlNHjzEX from '../assets/profile_pictures/1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg?enhanced&format=webp&w=64;128;200'
import brjUkEtQprju from '../assets/profile_pictures/38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg?enhanced&format=webp&w=64;128;200'
import ydhadEuhXbnx from '../assets/profile_pictures/00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg?enhanced&format=webp&w=64;128;200'
import SRqaNiqnkeuq from '../assets/profile_pictures/b2e5a483f8f2f9e8982be9ccce1012e4baf95dab_full.jpg?enhanced&format=webp&w=64;128;200'
import PtyeemQBnRrj from '../assets/profile_pictures/d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg?enhanced&format=webp&w=64;128;200'
import aMdGdryHOBrG from '../assets/profile_pictures/d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg?enhanced&format=webp&w=64;128;200'
import auTOFWieGuqH from '../assets/profile_pictures/831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg?enhanced&format=webp&w=64;128;200'
import NcSQWieFbucD from '../assets/profile_pictures/b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg?enhanced&format=webp&w=64;128;200'

const pfpDict: Record<string, Picture> = {
	"c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg": KJZfFqJtaYrl,
	"cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg": OLQkmZAamBfx,
	"7ed4ace4db81e7c1870f8af8452b4aa51eab39bf_full.jpg": ONKjeAJDCZca,
	"e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg": LgsrYcIKAsSl,
	"203dfa2c44bce6446016a7444da7647838544183_full.jpg": acPsuyezawiq,
	"9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg": BrvbHAOxpmMC,
	"7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg": gKpHGtlaywpL,
	"027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg": EqKiUSLpIvxo,
	"c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg": QxsBmUoQrGCK,
	"de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg": FrchyAJqSQtU,
	"11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg": HdpgfHXuzybE,
	"2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg": GjcdoQbcFDBk,
	"83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg": xzbdUKdxOUbM,
	"efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg": WLVHcUftXrNH,
	"cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg": rDqFTXGQMIVn,
	"81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg": LLrOEsGbAQUu,
	"a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg": CybNZWlbhyQy,
	"a95b3c96103a59a0dd548f56678b9e10d6c8e4e2_full.jpg": PVfsLEhJzaFq,
	"cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg": eTzOZKoMMGXu,
	"fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg": PirghdXPOtdE,
	"2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg": TIjOqnPOtsLW,
	"543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg": lQOfPMuIATpq,
	"129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg": FvdXNSUiTLqa,
	"52bfe6828f7cc88655757907064a1e9533425083_full.jpg": WbHGdFSnfEvX,
	"9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg": ICsUUEDuMwPI,
	"6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg": vOzHVRIUwKEk,
	"7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg": AdZpWvrRYtVp,
	"4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg": YxMafgqcKhBE,
	"c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg": xLboOoGuYjEA,
	"5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg": AEkSKWuKWDiE,
	"0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg": DbptxaDgEQxl,
	"56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg": uCxqHdywxwYv,
	"360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg": CcwvQRNQUSDZ,
	"a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg": UyHYyIfeqOvB,
	"049116dc3827584518d1124b90aa06b7fab8d023_full.jpg": MJpmGxUhjdss,
	"834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg": qJSNyvxNsvji,
	"acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg": uFFTrIGtyyVL,
	"a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg": iuMphdOeRJxe,
	"7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg": IIGezHhZTqEB,
	"420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg": rYZSYWuTbfBg,
	"f3374dbf1b98756714199c27cd68c21cf76115b3_full.jpg": zvrjOxJVPZkF,
	"d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg": uGZTlUpwdLkY,
	"70a266321c29018e4f66699399582f240e3235a1_full.jpg": HSPnYKVAMkEA,
	"8879e59d4428c411c61e108f3d647dd13540d80d_full.jpg": nJGOqBfuohOk,
	"5f6d8e360a7b54658b89fdb0938c3415ba5ebbb4_full.jpg": mYCRPcIbAqFf,
	"26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg": FCQZhZCwfvYy,
	"f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg": UhTwspxiqlCj,
	"0828e6eb804f312f914c446070331a35630b5d60_full.jpg": zFGBVlzeyduW,
	"bb056dd750e1444aee38309fc04c139a5948c077_full.jpg": hvrIGfsbzRWM,
	"f4f2fc58620a769dfcc51defda89ed5cb8fa7d75_full.jpg": bMQSnlcOhOqk,
	"52a9de1668a398d4dc400b8f225c5374034e9d82_full.jpg": QLdhlTgXxuMS,
	"7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg": eyTZZxxOOdtV,
	"e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg": WyALMXzCuDjP,
	"c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg": GgbDNRGBITfV,
	"79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg": nluraYJANcMo,
	"a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg": zeGoRhSMGDqz,
	"b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg": QjoliOygxlwP,
	"fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg": YJQtUyqNsEXA,
	"9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg": IAXZJMzDJFMr,
	"943df69df7a93f95109bac568dcd20e416622838_full.jpg": ftBQofgnEQvT,
	"576a072e6da81175e6b47f000010d843bca92fd7_full.jpg": NFiayRoAAJix,
	"ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg": rsoVedPkKwjA,
	"330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg": CSZIUmDkTONZ,
	"9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg": bejgLyuepvjn,
	"cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg": wDyJlUyrcrCR,
	"6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg": nQAsniVZqACs,
	"f924231652dc74192753cb3aea5ba883e9a843ff_full.jpg": zrFePopYEuhW,
	"56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg": cYMuJIyZfjDs,
	"618bfa7e8477cee17e56637af632fef4e31724b2_full.jpg": QqjBnoAsaezU,
	"7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg": gaqHMjvXprBg,
	"65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg": npgmBZUvJfYM,
	"49acdd7acab28c9344ec286e4dae713098043b02_full.jpg": rAVZvxKnEyZJ,
	"83764e067f3ee3bc0be68d65f4169c80d142b7af_full.jpg": yvRCylhlVuFB,
	"37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg": XVPhbmpAkCqX,
	"1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg": IUzKKlNHjzEX,
	"38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg": brjUkEtQprju,
	"00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg": ydhadEuhXbnx,
	"b2e5a483f8f2f9e8982be9ccce1012e4baf95dab_full.jpg": SRqaNiqnkeuq,
	"d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg": PtyeemQBnRrj,
	"d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg": aMdGdryHOBrG,
	"831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg": auTOFWieGuqH,
	"b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg": NcSQWieFbucD
};

const getProfilePicture = (profilePic: string) => {
    if (pfpDict[profilePic]) {
		return pfpDict[profilePic]
	}
    return `https://avatars.steamstatic.com/${profilePic}`
}
export { getProfilePicture }
