/**
* NOTE: This file is auto-generated by scripts/prefetch_steam.ts
* DO NOT modify manually
*/
import type { Picture } from 'vite-imagetools';
import hULBhwCeiaLg from '../assets/games/220.jpg?enhanced&format=webp'
import xmeXlAgzvQiy from '../assets/games/4000.jpg?enhanced&format=webp'
import LpDvEgxljiUo from '../assets/games/2300.jpg?enhanced&format=webp'
import wMHlrpfatqtu from '../assets/games/20900.jpg?enhanced&format=webp'
import qbnBXaztXSdP from '../assets/games/22300.jpg?enhanced&format=webp'
import RCdTxTJguIdB from '../assets/games/12210.jpg?enhanced&format=webp'
import nJSsDoBuESUJ from '../assets/games/17390.jpg?enhanced&format=webp'
import XrWvYbtsFIOf from '../assets/games/29800.jpg?enhanced&format=webp'
import RxsRMKhrtXZI from '../assets/games/6060.jpg?enhanced&format=webp'
import tgqaJewecHhk from '../assets/games/550.jpg?enhanced&format=webp'
import lITnsKrFpsBn from '../assets/games/8190.jpg?enhanced&format=webp'
import MjXmBPIkghES from '../assets/games/57300.jpg?enhanced&format=webp'
import uZTAFVkwfcGh from '../assets/games/8930.jpg?enhanced&format=webp'
import PBKGEHJamAoz from '../assets/games/40800.jpg?enhanced&format=webp'
import MglWnORPlfdM from '../assets/games/48190.jpg?enhanced&format=webp'
import vHpUsnrgFnZj from '../assets/games/620.jpg?enhanced&format=webp'
import LWDUfwYOgoaE from '../assets/games/105600.jpg?enhanced&format=webp'
import YwrzVILCtbQe from '../assets/games/20920.jpg?enhanced&format=webp'
import BsbcFOCTfskF from '../assets/games/92100.jpg?enhanced&format=webp'
import TrEgzXiIxisH from '../assets/games/22230.jpg?enhanced&format=webp'
import yvWsDAvbUpNW from '../assets/games/3830.jpg?enhanced&format=webp'
import kiDvetsgnOUs from '../assets/games/204030.jpg?enhanced&format=webp'
import GoERblOKWryI from '../assets/games/207610.jpg?enhanced&format=webp'
import GJrBZRsvFsej from '../assets/games/206440.jpg?enhanced&format=webp'
import bljqsXLzlQmH from '../assets/games/730.jpg?enhanced&format=webp'
import UYtLBSvAVbTq from '../assets/games/200260.jpg?enhanced&format=webp'
import huhOQflxUNPR from '../assets/games/212680.jpg?enhanced&format=webp'
import XRndaVfKAOLy from '../assets/games/204360.jpg?enhanced&format=webp'
import ZzQEfMeuPKBC from '../assets/games/49520.jpg?enhanced&format=webp'
import WUxIUDvvsTwR from '../assets/games/200710.jpg?enhanced&format=webp'
import LZElPbMMPzCF from '../assets/games/205100.jpg?enhanced&format=webp'
import UuRHpcVtTIlr from '../assets/games/223470.jpg?enhanced&format=webp'
import sJsKOvjuLrjR from '../assets/games/55230.jpg?enhanced&format=webp'
import yhJYogeudkVx from '../assets/games/220700.jpg?enhanced&format=webp'
import wpxMVhvnUeEK from '../assets/games/224540.jpg?enhanced&format=webp'
import pwWLwzMNanJR from '../assets/games/200210.jpg?enhanced&format=webp'
import WxWhFUZeOQLh from '../assets/games/208090.jpg?enhanced&format=webp'
import MtcxxhVNqBBV from '../assets/games/230410.jpg?enhanced&format=webp'
import kRdUdLTbLyzH from '../assets/games/236390.jpg?enhanced&format=webp'
import drVmASSoiZcL from '../assets/games/39000.jpg?enhanced&format=webp'
import TxKOGQHqwblW from '../assets/games/251670.jpg?enhanced&format=webp'
import LZqLWwTplzKB from '../assets/games/221040.jpg?enhanced&format=webp'
import jlBlPqQgFcdo from '../assets/games/203160.jpg?enhanced&format=webp'
import VwQdUCzNwZrw from '../assets/games/47890.jpg?enhanced&format=webp'
import KueirqrEStAJ from '../assets/games/233450.jpg?enhanced&format=webp'
import leiqcDXdtxlr from '../assets/games/233720.jpg?enhanced&format=webp'
import RJDEILHntLTG from '../assets/games/224760.jpg?enhanced&format=webp'
import lxeDADOyVVLb from '../assets/games/219740.jpg?enhanced&format=webp'
import ZJcFktDITiWm from '../assets/games/322330.jpg?enhanced&format=webp'
import qzfcCvdlaTDh from '../assets/games/234710.jpg?enhanced&format=webp'
import SZMnQUXkqtDW from '../assets/games/72850.jpg?enhanced&format=webp'
import JReNSbEjOpit from '../assets/games/35720.jpg?enhanced&format=webp'
import HQttKGIfJvvT from '../assets/games/242760.jpg?enhanced&format=webp'
import pTtycgqjjFcG from '../assets/games/242860.jpg?enhanced&format=webp'
import DjACWnVPsBev from '../assets/games/242920.jpg?enhanced&format=webp'
import OZrmHExxzxwm from '../assets/games/244850.jpg?enhanced&format=webp'
import tectnlyORAYV from '../assets/games/218620.jpg?enhanced&format=webp'
import hsNWjuFnQjMw from '../assets/games/239820.jpg?enhanced&format=webp'
import jrOnbrozRmEX from '../assets/games/252950.jpg?enhanced&format=webp'
import qGQCCRFQhFTz from '../assets/games/242050.jpg?enhanced&format=webp'
import RJfXZLoFSZXR from '../assets/games/219990.jpg?enhanced&format=webp'
import LdircFVubRGq from '../assets/games/257750.jpg?enhanced&format=webp'
import VgrUFhFhiEum from '../assets/games/221910.jpg?enhanced&format=webp'
import sPwGaSexrInr from '../assets/games/209170.jpg?enhanced&format=webp'
import FoJTeUVRzQZg from '../assets/games/264140.jpg?enhanced&format=webp'
import KNXfOpzdPoAK from '../assets/games/264710.jpg?enhanced&format=webp'
import ihDFZzZmaCHr from '../assets/games/265930.jpg?enhanced&format=webp'
import CrZxDXoGYJPz from '../assets/games/266010.jpg?enhanced&format=webp'
import lEEMxMkbKBgx from '../assets/games/211820.jpg?enhanced&format=webp'
import UszeOFJOlzuD from '../assets/games/221100.jpg?enhanced&format=webp'
import VFdrAVuDunql from '../assets/games/268910.jpg?enhanced&format=webp'
import bGGvAyciKfRM from '../assets/games/237870.jpg?enhanced&format=webp'
import BsDtAknhLlCC from '../assets/games/225840.jpg?enhanced&format=webp'
import AGCkTblgeWXt from '../assets/games/282140.jpg?enhanced&format=webp'
import WjrXcapBcVrD from '../assets/games/287700.jpg?enhanced&format=webp'
import LJPlkxTxdlKt from '../assets/games/292030.jpg?enhanced&format=webp'
import uFCKoAYrWhcl from '../assets/games/286160.jpg?enhanced&format=webp'
import cwPimGqWjTZm from '../assets/games/289130.jpg?enhanced&format=webp'
import AokjnvAJVXxQ from '../assets/games/238460.jpg?enhanced&format=webp'
import VnAuVaUKGbHw from '../assets/games/299460.jpg?enhanced&format=webp'
import fGtUNSdOqgKs from '../assets/games/243470.jpg?enhanced&format=webp'
import GAupQqmtfWTx from '../assets/games/304930.jpg?enhanced&format=webp'
import uipuLPMdyqkT from '../assets/games/306020.jpg?enhanced&format=webp'
import JdqPnPOgSLJI from '../assets/games/9900.jpg?enhanced&format=webp'
import HvBHVAfZGDkC from '../assets/games/311690.jpg?enhanced&format=webp'
import FVKNbghvpyKq from '../assets/games/206420.jpg?enhanced&format=webp'
import gykNGbdAyttQ from '../assets/games/314650.jpg?enhanced&format=webp'
import ttEJpeMiJDTO from '../assets/games/241930.jpg?enhanced&format=webp'
import RbxiCJqHnZhc from '../assets/games/322170.jpg?enhanced&format=webp'
import buVIXbNsGLJe from '../assets/games/214490.jpg?enhanced&format=webp'
import TuJCqzDFYDRw from '../assets/games/238320.jpg?enhanced&format=webp'
import wrUTEIZiaLvr from '../assets/games/327140.jpg?enhanced&format=webp'
import jtvxoIIVVoMV from '../assets/games/327890.jpg?enhanced&format=webp'
import yttcYqoezfHk from '../assets/games/261640.jpg?enhanced&format=webp'
import mtSIKHGuuWSg from '../assets/games/211420.jpg?enhanced&format=webp'
import hDcySinuzLJr from '../assets/games/330350.jpg?enhanced&format=webp'
import qSsUikSRzAyl from '../assets/games/298110.jpg?enhanced&format=webp'
import qnIAXbnzmOMe from '../assets/games/305620.jpg?enhanced&format=webp'
import etOrOrSnPlNc from '../assets/games/252490.jpg?enhanced&format=webp'
import sPiaQuhFzoiO from '../assets/games/250900.jpg?enhanced&format=webp'
import wxHobcfCNQsF from '../assets/games/319630.jpg?enhanced&format=webp'
import wIAvDnScGBse from '../assets/games/219150.jpg?enhanced&format=webp'
import iEjwYqVQRCEe from '../assets/games/274170.jpg?enhanced&format=webp'
import zkDfPRmiGJaG from '../assets/games/346010.jpg?enhanced&format=webp'
import lhuJADwJbYbw from '../assets/games/346110.jpg?enhanced&format=webp'
import vfjVaDEwvXad from '../assets/games/346900.jpg?enhanced&format=webp'
import uMjZPqWsHLOz from '../assets/games/298630.jpg?enhanced&format=webp'
import lYVkmDjjJfYm from '../assets/games/255710.jpg?enhanced&format=webp'
import XZKFPffOEYfS from '../assets/games/306130.jpg?enhanced&format=webp'
import nmxzCznjLSON from '../assets/games/271590.jpg?enhanced&format=webp'
import CfSYCKJeXUEZ from '../assets/games/359050.jpg?enhanced&format=webp'
import QjBerwcoVgxa from '../assets/games/363970.jpg?enhanced&format=webp'
import oEtVIjCkqKPE from '../assets/games/365720.jpg?enhanced&format=webp'
import vqXhYZRnbIsF from '../assets/games/365670.jpg?enhanced&format=webp'
import AaqrZxZSBomI from '../assets/games/367520.jpg?enhanced&format=webp'
import DJENUDLfCGmv from '../assets/games/375950.jpg?enhanced&format=webp'
import EOWykbLqAIBJ from '../assets/games/377160.jpg?enhanced&format=webp'
import zuOVqtKSnbpG from '../assets/games/384190.jpg?enhanced&format=webp'
import LckBZigmskjw from '../assets/games/391540.jpg?enhanced&format=webp'
import eSSxdQBcTEuG from '../assets/games/392110.jpg?enhanced&format=webp'
import WzfVUCXPpoQo from '../assets/games/393380.jpg?enhanced&format=webp'
import LYdVGprIExBq from '../assets/games/413150.jpg?enhanced&format=webp'
import gslcOtYoaLWi from '../assets/games/225540.jpg?enhanced&format=webp'
import GNWBDMUJSjyA from '../assets/games/417860.jpg?enhanced&format=webp'
import oUnyaoRFHxhF from '../assets/games/208650.jpg?enhanced&format=webp'
import EjZCMOizGRby from '../assets/games/420530.jpg?enhanced&format=webp'
import fdDYpAdvBdGp from '../assets/games/391220.jpg?enhanced&format=webp'
import yjzbPrdZvFzO from '../assets/games/427520.jpg?enhanced&format=webp'
import mLDxQYZloqXs from '../assets/games/210970.jpg?enhanced&format=webp'
import xXFLVRXnzLHd from '../assets/games/359550.jpg?enhanced&format=webp'
import kxgGLCUYJOrb from '../assets/games/623990.jpg?enhanced&format=webp'
import TpncfCCkZGKY from '../assets/games/239140.jpg?enhanced&format=webp'
import igPRiLVhogHM from '../assets/games/431960.jpg?enhanced&format=webp'
import IKPDXjhHSBDd from '../assets/games/434260.jpg?enhanced&format=webp'
import IdTPffqwBVOJ from '../assets/games/434570.jpg?enhanced&format=webp'
import zVmPlRAnGwxr from '../assets/games/374320.jpg?enhanced&format=webp'
import fRvaMiDVNUzd from '../assets/games/275850.jpg?enhanced&format=webp'
import GQYKwPeBEcfI from '../assets/games/457550.jpg?enhanced&format=webp'
import mEumzyzuydDE from '../assets/games/403640.jpg?enhanced&format=webp'
import ZScDaPFQjtmj from '../assets/games/501300.jpg?enhanced&format=webp'
import yVKmaVqQfttb from '../assets/games/518790.jpg?enhanced&format=webp'
import WOABWIkSARTc from '../assets/games/289070.jpg?enhanced&format=webp'
import obYwcISsZzdC from '../assets/games/534380.jpg?enhanced&format=webp'
import dUYvPErHGAsD from '../assets/games/546560.jpg?enhanced&format=webp'
import TaiEltzOtiil from '../assets/games/548430.jpg?enhanced&format=webp'
import JBiLzJuvIkvy from '../assets/games/489830.jpg?enhanced&format=webp'
import wRPegBRzxCkF from '../assets/games/553850.jpg?enhanced&format=webp'
import VbjcBEYnuoJp from '../assets/games/555160.jpg?enhanced&format=webp'
import ZbPtBDXXzBHl from '../assets/games/447040.jpg?enhanced&format=webp'
import vpMWJYYcNscx from '../assets/games/460920.jpg?enhanced&format=webp'
import jITXZPXimXKs from '../assets/games/564710.jpg?enhanced&format=webp'
import KHQUjfwuiufe from '../assets/games/578080.jpg?enhanced&format=webp'
import TPwrkiPylbjM from '../assets/games/578620.jpg?enhanced&format=webp'
import wSaSEekcoZze from '../assets/games/582660.jpg?enhanced&format=webp'
import WanZTnYCilMZ from '../assets/games/588650.jpg?enhanced&format=webp'
import QZBcGwPZnQAv from '../assets/games/460930.jpg?enhanced&format=webp'
import mtCyUyCXemxu from '../assets/games/611670.jpg?enhanced&format=webp'
import SoZkfyTmhMrK from '../assets/games/617830.jpg?enhanced&format=webp'
import dpieGxwHVRcE from '../assets/games/619910.jpg?enhanced&format=webp'
import DAhjXKokFTkO from '../assets/games/620980.jpg?enhanced&format=webp'
import SjNBGifIuwuH from '../assets/games/629730.jpg?enhanced&format=webp'
import eHrjaiOeDTiw from '../assets/games/632360.jpg?enhanced&format=webp'
import AJJwxmckkAsW from '../assets/games/671860.jpg?enhanced&format=webp'
import nTKAljAFPGAp from '../assets/games/683320.jpg?enhanced&format=webp'
import cNLInFrnrPBT from '../assets/games/414340.jpg?enhanced&format=webp'
import xJtJAszVHSec from '../assets/games/240720.jpg?enhanced&format=webp'
import SyGotXsqBaXZ from '../assets/games/582160.jpg?enhanced&format=webp'
import sjXOkzhjJhRo from '../assets/games/739630.jpg?enhanced&format=webp'
import olWsVrxYHgSv from '../assets/games/418370.jpg?enhanced&format=webp'
import YDcjdRMuyqFQ from '../assets/games/812140.jpg?enhanced&format=webp'
import rjbpeUozBiws from '../assets/games/552500.jpg?enhanced&format=webp'
import yppYchzJODee from '../assets/games/750920.jpg?enhanced&format=webp'
import YtxHmxYelkDI from '../assets/games/440900.jpg?enhanced&format=webp'
import ColsXDBwuxpW from '../assets/games/858260.jpg?enhanced&format=webp'
import HRVOUGSxxudu from '../assets/games/892970.jpg?enhanced&format=webp'
import MCkmAMCVfnrN from '../assets/games/899770.jpg?enhanced&format=webp'
import NJbEfZihaWZB from '../assets/games/814380.jpg?enhanced&format=webp'
import zySCPTanZoHa from '../assets/games/993090.jpg?enhanced&format=webp'
import nyfwdYzuMGEI from '../assets/games/524220.jpg?enhanced&format=webp'
import rhhKIZsDQDLT from '../assets/games/1030300.jpg?enhanced&format=webp'
import MsurYtvtXwdd from '../assets/games/1063730.jpg?enhanced&format=webp'
import pwSGymyCQkfC from '../assets/games/1079800.jpg?enhanced&format=webp'
import rxOFNmRItGyh from '../assets/games/1091500.jpg?enhanced&format=webp'
import OtkAEfrCQopz from '../assets/games/1145360.jpg?enhanced&format=webp'
import ZMkuBCumsGca from '../assets/games/1151640.jpg?enhanced&format=webp'
import FdqrFqbAOOFW from '../assets/games/1172620.jpg?enhanced&format=webp'
import HeRsofasWXWx from '../assets/games/1174180.jpg?enhanced&format=webp'
import zzwEFRxcYgBO from '../assets/games/397540.jpg?enhanced&format=webp'
import WFONQozNWHWW from '../assets/games/582010.jpg?enhanced&format=webp'
import TpGuCzfPqXoc from '../assets/games/1222670.jpg?enhanced&format=webp'
import tzlWAIAxtoYq from '../assets/games/1238840.jpg?enhanced&format=webp'
import mEXHfqTjVZVY from '../assets/games/1237950.jpg?enhanced&format=webp'
import ktfyzgWsKgxK from '../assets/games/1245620.jpg?enhanced&format=webp'
import WJdPcHXgeqSs from '../assets/games/1151340.jpg?enhanced&format=webp'
import KLIicbOmLZGC from '../assets/games/1326470.jpg?enhanced&format=webp'
import hVaehEYyISzY from '../assets/games/1349230.jpg?enhanced&format=webp'
import yqgJvGfDhnNf from '../assets/games/1403370.jpg?enhanced&format=webp'
import sGqqprAzoVFV from '../assets/games/1454400.jpg?enhanced&format=webp'
import WnFTfrrdLlss from '../assets/games/1468260.jpg?enhanced&format=webp'
import NLUbRcXGbkMY from '../assets/games/1475810.jpg?enhanced&format=webp'
import ziwqejefkMES from '../assets/games/1476970.jpg?enhanced&format=webp'
import XBeEZkAYPGgn from '../assets/games/1562420.jpg?enhanced&format=webp'
import HHFNyLJRvRKV from '../assets/games/1593500.jpg?enhanced&format=webp'
import zcWFBEtZbgFI from '../assets/games/1599340.jpg?enhanced&format=webp'
import BttyOXkJtphX from '../assets/games/1353300.jpg?enhanced&format=webp'
import mQMUecItuGnO from '../assets/games/1240440.jpg?enhanced&format=webp'
import ccCyUIomuGJE from '../assets/games/1794680.jpg?enhanced&format=webp'
import cFNDSRhCTsMC from '../assets/games/1446780.jpg?enhanced&format=webp'
import RLRYvEllldMw from '../assets/games/1817070.jpg?enhanced&format=webp'
import DgqzwbLyoTHH from '../assets/games/1943950.jpg?enhanced&format=webp'
import efonglNJjNgs from '../assets/games/1966720.jpg?enhanced&format=webp'
import dLMMZwUpokpS from '../assets/games/1999360.jpg?enhanced&format=webp'
import PQgQbUoMluJC from '../assets/games/2012840.jpg?enhanced&format=webp'
import CjlnpcIOOLTu from '../assets/games/1286680.jpg?enhanced&format=webp'
import GSuZwdGswqKO from '../assets/games/1313140.jpg?enhanced&format=webp'
import MmhgDwxqXNNB from '../assets/games/990080.jpg?enhanced&format=webp'
import ARsDqYIYkOAk from '../assets/games/2215430.jpg?enhanced&format=webp'
import ikUIYFIWlqwR from '../assets/games/2399830.jpg?enhanced&format=webp'
import WpLgZahVRRYD from '../assets/games/2420110.jpg?enhanced&format=webp'
import mlwrPSSAfOUy from '../assets/games/1086940.jpg?enhanced&format=webp'
import QpZDVGMyXrhB from '../assets/games/1361210.jpg?enhanced&format=webp'
import XStPEMccDdTO from '../assets/games/2767030.jpg?enhanced&format=webp'
import kXdXNTibgcZs from '../assets/games/2840770.jpg?enhanced&format=webp'
import QtejEkBCfZcd from '../assets/games/3065170.jpg?enhanced&format=webp'
import WfGQhPbHZvVw from '../assets/games/3159330.jpg?enhanced&format=webp'
import TmFgvMiGYCsA from '../assets/games/2246340.jpg?enhanced&format=webp'
import CkEVYXWGjGBQ from '../assets/games/2124490.jpg?enhanced&format=webp'
import lSePqqPBAboe from '../assets/games/2561580.jpg?enhanced&format=webp'
import SXaZypTVuBfF from '../assets/games/2694490.jpg?enhanced&format=webp'
import dyDbKqtZLNwa from '../assets/games/440.jpg?enhanced&format=webp'
import TyTYipkCKlpi from '../assets/games/570.jpg?enhanced&format=webp'
import iQPvPepyPpkq from '../assets/games/genshin.jpg?enhanced&format=webp'
import OYiJwPhiexDl from '../assets/games/wow.jpg?enhanced&format=webp'

const gameHeroDict: Record<string, Picture> = {
	[220]: hULBhwCeiaLg,
	[4000]: xmeXlAgzvQiy,
	[2300]: LpDvEgxljiUo,
	[20900]: wMHlrpfatqtu,
	[22300]: qbnBXaztXSdP,
	[12210]: RCdTxTJguIdB,
	[17390]: nJSsDoBuESUJ,
	[29800]: XrWvYbtsFIOf,
	[6060]: RxsRMKhrtXZI,
	[550]: tgqaJewecHhk,
	[8190]: lITnsKrFpsBn,
	[57300]: MjXmBPIkghES,
	[8930]: uZTAFVkwfcGh,
	[40800]: PBKGEHJamAoz,
	[48190]: MglWnORPlfdM,
	[620]: vHpUsnrgFnZj,
	[105600]: LWDUfwYOgoaE,
	[20920]: YwrzVILCtbQe,
	[92100]: BsbcFOCTfskF,
	[22230]: TrEgzXiIxisH,
	[3830]: yvWsDAvbUpNW,
	[204030]: kiDvetsgnOUs,
	[207610]: GoERblOKWryI,
	[206440]: GJrBZRsvFsej,
	[730]: bljqsXLzlQmH,
	[200260]: UYtLBSvAVbTq,
	[212680]: huhOQflxUNPR,
	[204360]: XRndaVfKAOLy,
	[49520]: ZzQEfMeuPKBC,
	[200710]: WUxIUDvvsTwR,
	[205100]: LZElPbMMPzCF,
	[223470]: UuRHpcVtTIlr,
	[55230]: sJsKOvjuLrjR,
	[220700]: yhJYogeudkVx,
	[224540]: wpxMVhvnUeEK,
	[200210]: pwWLwzMNanJR,
	[208090]: WxWhFUZeOQLh,
	[230410]: MtcxxhVNqBBV,
	[236390]: kRdUdLTbLyzH,
	[39000]: drVmASSoiZcL,
	[251670]: TxKOGQHqwblW,
	[221040]: LZqLWwTplzKB,
	[203160]: jlBlPqQgFcdo,
	[47890]: VwQdUCzNwZrw,
	[233450]: KueirqrEStAJ,
	[233720]: leiqcDXdtxlr,
	[224760]: RJDEILHntLTG,
	[219740]: lxeDADOyVVLb,
	[322330]: ZJcFktDITiWm,
	[234710]: qzfcCvdlaTDh,
	[72850]: SZMnQUXkqtDW,
	[35720]: JReNSbEjOpit,
	[242760]: HQttKGIfJvvT,
	[242860]: pTtycgqjjFcG,
	[242920]: DjACWnVPsBev,
	[244850]: OZrmHExxzxwm,
	[218620]: tectnlyORAYV,
	[239820]: hsNWjuFnQjMw,
	[252950]: jrOnbrozRmEX,
	[242050]: qGQCCRFQhFTz,
	[219990]: RJfXZLoFSZXR,
	[257750]: LdircFVubRGq,
	[221910]: VgrUFhFhiEum,
	[209170]: sPwGaSexrInr,
	[264140]: FoJTeUVRzQZg,
	[264710]: KNXfOpzdPoAK,
	[265930]: ihDFZzZmaCHr,
	[266010]: CrZxDXoGYJPz,
	[211820]: lEEMxMkbKBgx,
	[221100]: UszeOFJOlzuD,
	[268910]: VFdrAVuDunql,
	[237870]: bGGvAyciKfRM,
	[225840]: BsDtAknhLlCC,
	[282140]: AGCkTblgeWXt,
	[287700]: WjrXcapBcVrD,
	[292030]: LJPlkxTxdlKt,
	[286160]: uFCKoAYrWhcl,
	[289130]: cwPimGqWjTZm,
	[238460]: AokjnvAJVXxQ,
	[299460]: VnAuVaUKGbHw,
	[243470]: fGtUNSdOqgKs,
	[304930]: GAupQqmtfWTx,
	[306020]: uipuLPMdyqkT,
	[9900]: JdqPnPOgSLJI,
	[311690]: HvBHVAfZGDkC,
	[206420]: FVKNbghvpyKq,
	[314650]: gykNGbdAyttQ,
	[241930]: ttEJpeMiJDTO,
	[322170]: RbxiCJqHnZhc,
	[214490]: buVIXbNsGLJe,
	[238320]: TuJCqzDFYDRw,
	[327140]: wrUTEIZiaLvr,
	[327890]: jtvxoIIVVoMV,
	[261640]: yttcYqoezfHk,
	[211420]: mtSIKHGuuWSg,
	[330350]: hDcySinuzLJr,
	[298110]: qSsUikSRzAyl,
	[305620]: qnIAXbnzmOMe,
	[252490]: etOrOrSnPlNc,
	[250900]: sPiaQuhFzoiO,
	[319630]: wxHobcfCNQsF,
	[219150]: wIAvDnScGBse,
	[274170]: iEjwYqVQRCEe,
	[346010]: zkDfPRmiGJaG,
	[346110]: lhuJADwJbYbw,
	[346900]: vfjVaDEwvXad,
	[298630]: uMjZPqWsHLOz,
	[255710]: lYVkmDjjJfYm,
	[306130]: XZKFPffOEYfS,
	[271590]: nmxzCznjLSON,
	[359050]: CfSYCKJeXUEZ,
	[363970]: QjBerwcoVgxa,
	[365720]: oEtVIjCkqKPE,
	[365670]: vqXhYZRnbIsF,
	[367520]: AaqrZxZSBomI,
	[375950]: DJENUDLfCGmv,
	[377160]: EOWykbLqAIBJ,
	[384190]: zuOVqtKSnbpG,
	[391540]: LckBZigmskjw,
	[392110]: eSSxdQBcTEuG,
	[393380]: WzfVUCXPpoQo,
	[413150]: LYdVGprIExBq,
	[225540]: gslcOtYoaLWi,
	[417860]: GNWBDMUJSjyA,
	[208650]: oUnyaoRFHxhF,
	[420530]: EjZCMOizGRby,
	[391220]: fdDYpAdvBdGp,
	[427520]: yjzbPrdZvFzO,
	[210970]: mLDxQYZloqXs,
	[359550]: xXFLVRXnzLHd,
	[623990]: kxgGLCUYJOrb,
	[239140]: TpncfCCkZGKY,
	[431960]: igPRiLVhogHM,
	[434260]: IKPDXjhHSBDd,
	[434570]: IdTPffqwBVOJ,
	[374320]: zVmPlRAnGwxr,
	[275850]: fRvaMiDVNUzd,
	[457550]: GQYKwPeBEcfI,
	[403640]: mEumzyzuydDE,
	[501300]: ZScDaPFQjtmj,
	[518790]: yVKmaVqQfttb,
	[289070]: WOABWIkSARTc,
	[534380]: obYwcISsZzdC,
	[546560]: dUYvPErHGAsD,
	[548430]: TaiEltzOtiil,
	[489830]: JBiLzJuvIkvy,
	[553850]: wRPegBRzxCkF,
	[555160]: VbjcBEYnuoJp,
	[447040]: ZbPtBDXXzBHl,
	[460920]: vpMWJYYcNscx,
	[564710]: jITXZPXimXKs,
	[578080]: KHQUjfwuiufe,
	[578620]: TPwrkiPylbjM,
	[582660]: wSaSEekcoZze,
	[588650]: WanZTnYCilMZ,
	[460930]: QZBcGwPZnQAv,
	[611670]: mtCyUyCXemxu,
	[617830]: SoZkfyTmhMrK,
	[619910]: dpieGxwHVRcE,
	[620980]: DAhjXKokFTkO,
	[629730]: SjNBGifIuwuH,
	[632360]: eHrjaiOeDTiw,
	[671860]: AJJwxmckkAsW,
	[683320]: nTKAljAFPGAp,
	[414340]: cNLInFrnrPBT,
	[240720]: xJtJAszVHSec,
	[582160]: SyGotXsqBaXZ,
	[739630]: sjXOkzhjJhRo,
	[418370]: olWsVrxYHgSv,
	[812140]: YDcjdRMuyqFQ,
	[552500]: rjbpeUozBiws,
	[750920]: yppYchzJODee,
	[440900]: YtxHmxYelkDI,
	[858260]: ColsXDBwuxpW,
	[892970]: HRVOUGSxxudu,
	[899770]: MCkmAMCVfnrN,
	[814380]: NJbEfZihaWZB,
	[993090]: zySCPTanZoHa,
	[524220]: nyfwdYzuMGEI,
	[1030300]: rhhKIZsDQDLT,
	[1063730]: MsurYtvtXwdd,
	[1079800]: pwSGymyCQkfC,
	[1091500]: rxOFNmRItGyh,
	[1145360]: OtkAEfrCQopz,
	[1151640]: ZMkuBCumsGca,
	[1172620]: FdqrFqbAOOFW,
	[1174180]: HeRsofasWXWx,
	[397540]: zzwEFRxcYgBO,
	[582010]: WFONQozNWHWW,
	[1222670]: TpGuCzfPqXoc,
	[1238840]: tzlWAIAxtoYq,
	[1237950]: mEXHfqTjVZVY,
	[1245620]: ktfyzgWsKgxK,
	[1151340]: WJdPcHXgeqSs,
	[1326470]: KLIicbOmLZGC,
	[1349230]: hVaehEYyISzY,
	[1403370]: yqgJvGfDhnNf,
	[1454400]: sGqqprAzoVFV,
	[1468260]: WnFTfrrdLlss,
	[1475810]: NLUbRcXGbkMY,
	[1476970]: ziwqejefkMES,
	[1562420]: XBeEZkAYPGgn,
	[1593500]: HHFNyLJRvRKV,
	[1599340]: zcWFBEtZbgFI,
	[1353300]: BttyOXkJtphX,
	[1240440]: mQMUecItuGnO,
	[1794680]: ccCyUIomuGJE,
	[1446780]: cFNDSRhCTsMC,
	[1817070]: RLRYvEllldMw,
	[1943950]: DgqzwbLyoTHH,
	[1966720]: efonglNJjNgs,
	[1999360]: dLMMZwUpokpS,
	[2012840]: PQgQbUoMluJC,
	[1286680]: CjlnpcIOOLTu,
	[1313140]: GSuZwdGswqKO,
	[990080]: MmhgDwxqXNNB,
	[2215430]: ARsDqYIYkOAk,
	[2399830]: ikUIYFIWlqwR,
	[2420110]: WpLgZahVRRYD,
	[1086940]: mlwrPSSAfOUy,
	[1361210]: QpZDVGMyXrhB,
	[2767030]: XStPEMccDdTO,
	[2840770]: kXdXNTibgcZs,
	[3065170]: QtejEkBCfZcd,
	[3159330]: WfGQhPbHZvVw,
	[2246340]: TmFgvMiGYCsA,
	[2124490]: CkEVYXWGjGBQ,
	[2561580]: lSePqqPBAboe,
	[2694490]: SXaZypTVuBfF,
	[440]: dyDbKqtZLNwa,
	[570]: TyTYipkCKlpi,
	"genshin": iQPvPepyPpkq,
	"wow": OYiJwPhiexDl
};

const getGameHero = (appId: number | string) => {
	if (gameHeroDict[appId]) {
		return gameHeroDict[appId]
	}
	return `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`
}
export { getGameHero }
import kUGqvnVIRnew from '../assets/icons/220.jpg?enhanced&format=webp'
import BHRoGVJrwWXL from '../assets/icons/4000.jpg?enhanced&format=webp'
import HkmKhyGNWOwd from '../assets/icons/2300.jpg?enhanced&format=webp'
import ZYQOtnwZieMC from '../assets/icons/20900.jpg?enhanced&format=webp'
import fVUgavumJJau from '../assets/icons/22300.jpg?enhanced&format=webp'
import hDvRggboyqXc from '../assets/icons/12210.jpg?enhanced&format=webp'
import RDtbcwRyogyO from '../assets/icons/17390.jpg?enhanced&format=webp'
import tdPfILZZedrA from '../assets/icons/29800.jpg?enhanced&format=webp'
import jqQSRsMKegMO from '../assets/icons/6060.jpg?enhanced&format=webp'
import VcslYGwxxioR from '../assets/icons/550.jpg?enhanced&format=webp'
import mKmIDAVjfTiC from '../assets/icons/8190.jpg?enhanced&format=webp'
import qNbNXWbsCyWO from '../assets/icons/57300.jpg?enhanced&format=webp'
import oqMZSElQaQPW from '../assets/icons/8930.jpg?enhanced&format=webp'
import OruSeaNmMCOb from '../assets/icons/40800.jpg?enhanced&format=webp'
import ahtesFocegrR from '../assets/icons/48190.jpg?enhanced&format=webp'
import DvmITcphzFUv from '../assets/icons/620.jpg?enhanced&format=webp'
import iChVzLuyZoVb from '../assets/icons/105600.jpg?enhanced&format=webp'
import MymyuoOGtENb from '../assets/icons/20920.jpg?enhanced&format=webp'
import cvidOHgHYKSo from '../assets/icons/92100.jpg?enhanced&format=webp'
import ipFZknkfrFaD from '../assets/icons/22230.jpg?enhanced&format=webp'
import SnJEvnVBhyRU from '../assets/icons/3830.jpg?enhanced&format=webp'
import LqqEIJjyJdsh from '../assets/icons/204030.jpg?enhanced&format=webp'
import MLvxycJmCJIF from '../assets/icons/207610.jpg?enhanced&format=webp'
import NdXvylWuBiMT from '../assets/icons/206440.jpg?enhanced&format=webp'
import fQZthhrptjyW from '../assets/icons/730.jpg?enhanced&format=webp'
import dQIJAjUqBoCa from '../assets/icons/200260.jpg?enhanced&format=webp'
import jfQoEDCyGwIR from '../assets/icons/212680.jpg?enhanced&format=webp'
import upSHNDHQsKfi from '../assets/icons/204360.jpg?enhanced&format=webp'
import CLkjpXqjnQCe from '../assets/icons/49520.jpg?enhanced&format=webp'
import URXzddbfSivL from '../assets/icons/200710.jpg?enhanced&format=webp'
import UrhbVcRckVno from '../assets/icons/205100.jpg?enhanced&format=webp'
import FaUFcAXgIFrr from '../assets/icons/223470.jpg?enhanced&format=webp'
import YssnUzkrDmGK from '../assets/icons/55230.jpg?enhanced&format=webp'
import eWeSwAeHKZKw from '../assets/icons/220700.jpg?enhanced&format=webp'
import FbpMZIImUgEc from '../assets/icons/224540.jpg?enhanced&format=webp'
import ZWCYpvWhVDIg from '../assets/icons/200210.jpg?enhanced&format=webp'
import FsrBHlnkhzqT from '../assets/icons/208090.jpg?enhanced&format=webp'
import HVImGrZcfOaj from '../assets/icons/230410.jpg?enhanced&format=webp'
import YLGCdEkjoPLS from '../assets/icons/236390.jpg?enhanced&format=webp'
import IdpvBIojBRid from '../assets/icons/39000.jpg?enhanced&format=webp'
import pKfxPUkcPsfG from '../assets/icons/251670.jpg?enhanced&format=webp'
import QbkznKuBryrT from '../assets/icons/221040.jpg?enhanced&format=webp'
import FrbJPkjDFkUQ from '../assets/icons/203160.jpg?enhanced&format=webp'
import vvdcLKqSwaiB from '../assets/icons/47890.jpg?enhanced&format=webp'
import dNUmHtstAfzv from '../assets/icons/233450.jpg?enhanced&format=webp'
import AUpxAJUzuuFF from '../assets/icons/233720.jpg?enhanced&format=webp'
import qCERxNBjTYYl from '../assets/icons/224760.jpg?enhanced&format=webp'
import YHyZfCWGUusZ from '../assets/icons/219740.jpg?enhanced&format=webp'
import eburiMLRaGdQ from '../assets/icons/322330.jpg?enhanced&format=webp'
import SPVHeCtFKetz from '../assets/icons/234710.jpg?enhanced&format=webp'
import fJsrepoxIUdm from '../assets/icons/72850.jpg?enhanced&format=webp'
import kyYNdIKJykzN from '../assets/icons/35720.jpg?enhanced&format=webp'
import ICtvQyfcAdrb from '../assets/icons/242760.jpg?enhanced&format=webp'
import zlSASurrUiUF from '../assets/icons/242860.jpg?enhanced&format=webp'
import pblCPvIhBRcu from '../assets/icons/242920.jpg?enhanced&format=webp'
import RTHNMaJEEJcR from '../assets/icons/244850.jpg?enhanced&format=webp'
import aJFhMArhXJEW from '../assets/icons/218620.jpg?enhanced&format=webp'
import lQEVgARdTVno from '../assets/icons/239820.jpg?enhanced&format=webp'
import xZOMoezMKJYw from '../assets/icons/252950.jpg?enhanced&format=webp'
import dRbBcReLtzXh from '../assets/icons/242050.jpg?enhanced&format=webp'
import vRqIkCzZdUGp from '../assets/icons/219990.jpg?enhanced&format=webp'
import sqhMBeZwITjj from '../assets/icons/257750.jpg?enhanced&format=webp'
import gbkDdjwtSspM from '../assets/icons/221910.jpg?enhanced&format=webp'
import NLONlpmhFUTh from '../assets/icons/209170.jpg?enhanced&format=webp'
import grKpeEUlbmXu from '../assets/icons/264140.jpg?enhanced&format=webp'
import XBSdeOqmRSfw from '../assets/icons/264710.jpg?enhanced&format=webp'
import jsEieCLVzVtq from '../assets/icons/265930.jpg?enhanced&format=webp'
import LsjosKDmgbQE from '../assets/icons/266010.jpg?enhanced&format=webp'
import HjpBTYmflkws from '../assets/icons/211820.jpg?enhanced&format=webp'
import HdSpZXnrQGrP from '../assets/icons/221100.jpg?enhanced&format=webp'
import SiCYnvaWMCNr from '../assets/icons/268910.jpg?enhanced&format=webp'
import WiPBDUlNpngA from '../assets/icons/237870.jpg?enhanced&format=webp'
import ixeXaDyRTkzA from '../assets/icons/225840.jpg?enhanced&format=webp'
import WosdlmRySHbb from '../assets/icons/282140.jpg?enhanced&format=webp'
import qGROVwysTYdN from '../assets/icons/287700.jpg?enhanced&format=webp'
import ZzYCLhxvrdxw from '../assets/icons/292030.jpg?enhanced&format=webp'
import bDCRDpwuuNlO from '../assets/icons/286160.jpg?enhanced&format=webp'
import TMTVbnPYvufU from '../assets/icons/289130.jpg?enhanced&format=webp'
import FUqGGBwpcPqP from '../assets/icons/238460.jpg?enhanced&format=webp'
import HzwOHhNhqAEs from '../assets/icons/299460.jpg?enhanced&format=webp'
import ksQYcLhZMLdL from '../assets/icons/243470.jpg?enhanced&format=webp'
import IEbCVglyidHz from '../assets/icons/304930.jpg?enhanced&format=webp'
import WTqmyFKwdmMZ from '../assets/icons/306020.jpg?enhanced&format=webp'
import ymaxLrRVaUOL from '../assets/icons/9900.jpg?enhanced&format=webp'
import zOctDChdIbnt from '../assets/icons/311690.jpg?enhanced&format=webp'
import SwiRDcyPzhnB from '../assets/icons/206420.jpg?enhanced&format=webp'
import XeGVhNJwbgek from '../assets/icons/314650.jpg?enhanced&format=webp'
import AYJFBPHllwPx from '../assets/icons/241930.jpg?enhanced&format=webp'
import HvusCGtwZLVR from '../assets/icons/322170.jpg?enhanced&format=webp'
import ULJXnyyEKIaZ from '../assets/icons/214490.jpg?enhanced&format=webp'
import wLoaIuusmDHJ from '../assets/icons/238320.jpg?enhanced&format=webp'
import hoUYiAqeJIhc from '../assets/icons/327140.jpg?enhanced&format=webp'
import IdELwubBkvWQ from '../assets/icons/327890.jpg?enhanced&format=webp'
import xxTGHtvlCphV from '../assets/icons/261640.jpg?enhanced&format=webp'
import TXnMDAZLKExA from '../assets/icons/211420.jpg?enhanced&format=webp'
import VfocPdIaOWQK from '../assets/icons/330350.jpg?enhanced&format=webp'
import GfCYlPutWQex from '../assets/icons/298110.jpg?enhanced&format=webp'
import aHFmyyIPTJmS from '../assets/icons/305620.jpg?enhanced&format=webp'
import mjmWRjzzZtsX from '../assets/icons/252490.jpg?enhanced&format=webp'
import lTygFvfbHlqD from '../assets/icons/250900.jpg?enhanced&format=webp'
import ENrDogQwoSQj from '../assets/icons/319630.jpg?enhanced&format=webp'
import REePkCyItSYl from '../assets/icons/219150.jpg?enhanced&format=webp'
import nIIPupMGbUvl from '../assets/icons/274170.jpg?enhanced&format=webp'
import UGAShxEEEYdK from '../assets/icons/346010.jpg?enhanced&format=webp'
import rMSTLDiGDuGt from '../assets/icons/346110.jpg?enhanced&format=webp'
import mLxEarDnWKZQ from '../assets/icons/346900.jpg?enhanced&format=webp'
import uYDWduRLxAsK from '../assets/icons/298630.jpg?enhanced&format=webp'
import hhnVMdpkqNNJ from '../assets/icons/255710.jpg?enhanced&format=webp'
import xmTWeyOnKWLo from '../assets/icons/306130.jpg?enhanced&format=webp'
import IISYBrrUqHrq from '../assets/icons/271590.jpg?enhanced&format=webp'
import vctivbfaAnWq from '../assets/icons/359050.jpg?enhanced&format=webp'
import rOQnAkUecYiZ from '../assets/icons/363970.jpg?enhanced&format=webp'
import MgXxIChXQcIf from '../assets/icons/365720.jpg?enhanced&format=webp'
import mbTVPthoBJxW from '../assets/icons/365670.jpg?enhanced&format=webp'
import aJnyJUjoxoLk from '../assets/icons/367520.jpg?enhanced&format=webp'
import ZIvyanBtDmqk from '../assets/icons/375950.jpg?enhanced&format=webp'
import ijbXKgBqQHzs from '../assets/icons/377160.jpg?enhanced&format=webp'
import wfXGeBWPUiGY from '../assets/icons/384190.jpg?enhanced&format=webp'
import ZRGGemOmCoYO from '../assets/icons/391540.jpg?enhanced&format=webp'
import hclGluQvlPBv from '../assets/icons/392110.jpg?enhanced&format=webp'
import otzyCMugBDcE from '../assets/icons/393380.jpg?enhanced&format=webp'
import MJvYdflvSdJm from '../assets/icons/413150.jpg?enhanced&format=webp'
import KTsEeDYEChuY from '../assets/icons/225540.jpg?enhanced&format=webp'
import UMUPsjTdwUti from '../assets/icons/417860.jpg?enhanced&format=webp'
import nGGUbRBsuxpo from '../assets/icons/208650.jpg?enhanced&format=webp'
import dcoubfGsvssg from '../assets/icons/420530.jpg?enhanced&format=webp'
import fHUlpOipEyIS from '../assets/icons/391220.jpg?enhanced&format=webp'
import KxPjswagoGpF from '../assets/icons/427520.jpg?enhanced&format=webp'
import VgHTcECHeZWE from '../assets/icons/210970.jpg?enhanced&format=webp'
import hcLYuuqsmaJm from '../assets/icons/359550.jpg?enhanced&format=webp'
import ZHrhDWxvJNcu from '../assets/icons/623990.jpg?enhanced&format=webp'
import gBjqDxrvKRIY from '../assets/icons/239140.jpg?enhanced&format=webp'
import HBcHCpAUsyeF from '../assets/icons/431960.jpg?enhanced&format=webp'
import BEPoueZXeQbF from '../assets/icons/434260.jpg?enhanced&format=webp'
import lqufndtboHDV from '../assets/icons/434570.jpg?enhanced&format=webp'
import aFQrHBnMPJAN from '../assets/icons/374320.jpg?enhanced&format=webp'
import xOAdLWkgNwsj from '../assets/icons/275850.jpg?enhanced&format=webp'
import CdujmmLtuXPX from '../assets/icons/457550.jpg?enhanced&format=webp'
import snvqZMneMYPW from '../assets/icons/403640.jpg?enhanced&format=webp'
import OkjByKFXFXEc from '../assets/icons/501300.jpg?enhanced&format=webp'
import wzXveZtoVTxb from '../assets/icons/518790.jpg?enhanced&format=webp'
import dkdoIkgalybg from '../assets/icons/289070.jpg?enhanced&format=webp'
import OPXoLsSevsfQ from '../assets/icons/534380.jpg?enhanced&format=webp'
import SQAGuGzySjNm from '../assets/icons/546560.jpg?enhanced&format=webp'
import ynZvBemzjCOy from '../assets/icons/548430.jpg?enhanced&format=webp'
import ucekVAHybkaf from '../assets/icons/489830.jpg?enhanced&format=webp'
import NRkzoWmQZpkA from '../assets/icons/553850.jpg?enhanced&format=webp'
import hLmjlZtUgRLS from '../assets/icons/555160.jpg?enhanced&format=webp'
import uPEnSnsFYyVY from '../assets/icons/447040.jpg?enhanced&format=webp'
import LRWTrWcHhoFE from '../assets/icons/460920.jpg?enhanced&format=webp'
import uSdlREMgJpqw from '../assets/icons/564710.jpg?enhanced&format=webp'
import MwCpKjoezFxq from '../assets/icons/578080.jpg?enhanced&format=webp'
import HGUzeKqKwxBf from '../assets/icons/578620.jpg?enhanced&format=webp'
import naLSoVGgEwNL from '../assets/icons/582660.jpg?enhanced&format=webp'
import JTnvhtBecLgB from '../assets/icons/588650.jpg?enhanced&format=webp'
import QtKuClQLDMPK from '../assets/icons/460930.jpg?enhanced&format=webp'
import xzigvAqHvTGe from '../assets/icons/611670.jpg?enhanced&format=webp'
import kIiZZozkDYtk from '../assets/icons/617830.jpg?enhanced&format=webp'
import AIHKMkhEqVkF from '../assets/icons/619910.jpg?enhanced&format=webp'
import sSbyXcuoHoDP from '../assets/icons/620980.jpg?enhanced&format=webp'
import SamUkSRFubvc from '../assets/icons/629730.jpg?enhanced&format=webp'
import HqTxTASKPsYG from '../assets/icons/632360.jpg?enhanced&format=webp'
import QKdmdYUQDeSs from '../assets/icons/671860.jpg?enhanced&format=webp'
import GPeMjdOdJRJf from '../assets/icons/683320.jpg?enhanced&format=webp'
import oKxzynknQkuk from '../assets/icons/414340.jpg?enhanced&format=webp'
import rkbXYXgyTBaY from '../assets/icons/240720.jpg?enhanced&format=webp'
import JLlUbjPKeqVH from '../assets/icons/582160.jpg?enhanced&format=webp'
import UKDNMHybKgNi from '../assets/icons/739630.jpg?enhanced&format=webp'
import hbOFNXvGnPEJ from '../assets/icons/418370.jpg?enhanced&format=webp'
import ALUyPUezWwHV from '../assets/icons/812140.jpg?enhanced&format=webp'
import oBEYTDioEPsB from '../assets/icons/552500.jpg?enhanced&format=webp'
import ZlyNkEDZQUZA from '../assets/icons/750920.jpg?enhanced&format=webp'
import MBpUKbKcRURv from '../assets/icons/440900.jpg?enhanced&format=webp'
import SMtkolqDKQMZ from '../assets/icons/858260.jpg?enhanced&format=webp'
import JyEEaCjlHtGi from '../assets/icons/892970.jpg?enhanced&format=webp'
import uCczSVCdnGjC from '../assets/icons/899770.jpg?enhanced&format=webp'
import CQCjaAMXGDgc from '../assets/icons/814380.jpg?enhanced&format=webp'
import SFsvbgBTAQQp from '../assets/icons/993090.jpg?enhanced&format=webp'
import OniITCYArDXK from '../assets/icons/524220.jpg?enhanced&format=webp'
import ewonyNOpYxxu from '../assets/icons/1030300.jpg?enhanced&format=webp'
import szWWrEvbfMeJ from '../assets/icons/1063730.jpg?enhanced&format=webp'
import NNDzBZcldnMU from '../assets/icons/1079800.jpg?enhanced&format=webp'
import SsPsiaYUPURb from '../assets/icons/1091500.jpg?enhanced&format=webp'
import TaAZwcmnaSxm from '../assets/icons/1145360.jpg?enhanced&format=webp'
import ebfoLsXBTXbD from '../assets/icons/1151640.jpg?enhanced&format=webp'
import YsQSbcHqPjZD from '../assets/icons/1172620.jpg?enhanced&format=webp'
import smbdWCRrEPEo from '../assets/icons/1174180.jpg?enhanced&format=webp'
import csNjPknVfpDg from '../assets/icons/397540.jpg?enhanced&format=webp'
import ipDiVietAzPT from '../assets/icons/582010.jpg?enhanced&format=webp'
import ivGxvLwIcrkR from '../assets/icons/1222670.jpg?enhanced&format=webp'
import MlaTWQDWBoMR from '../assets/icons/1238840.jpg?enhanced&format=webp'
import QFAZBrPGumgR from '../assets/icons/1237950.jpg?enhanced&format=webp'
import jAKZpXbFEyam from '../assets/icons/1245620.jpg?enhanced&format=webp'
import nVUuvikSYarK from '../assets/icons/1151340.jpg?enhanced&format=webp'
import mLabAEOOtnib from '../assets/icons/1326470.jpg?enhanced&format=webp'
import fYxFsagxcvvO from '../assets/icons/1349230.jpg?enhanced&format=webp'
import nOpAMIyfhNxl from '../assets/icons/1403370.jpg?enhanced&format=webp'
import UBZAGILgsBxq from '../assets/icons/1454400.jpg?enhanced&format=webp'
import HhdjucwgpvRK from '../assets/icons/1468260.jpg?enhanced&format=webp'
import FCRofCTgJZTg from '../assets/icons/1475810.jpg?enhanced&format=webp'
import zpmQvGSaenhZ from '../assets/icons/1476970.jpg?enhanced&format=webp'
import EupOunFxTMwg from '../assets/icons/1562420.jpg?enhanced&format=webp'
import MKdsvBpfNrpa from '../assets/icons/1593500.jpg?enhanced&format=webp'
import sZmVmTUvCzMl from '../assets/icons/1599340.jpg?enhanced&format=webp'
import mOXRrPYsXQVe from '../assets/icons/1353300.jpg?enhanced&format=webp'
import OozILzOcwcHh from '../assets/icons/1240440.jpg?enhanced&format=webp'
import PalwqskezqXk from '../assets/icons/1794680.jpg?enhanced&format=webp'
import bjRVIpEzTshR from '../assets/icons/1446780.jpg?enhanced&format=webp'
import AAngYfvbnATl from '../assets/icons/1817070.jpg?enhanced&format=webp'
import BjwfWnvcCotg from '../assets/icons/1943950.jpg?enhanced&format=webp'
import ALJIlMIRMsIQ from '../assets/icons/1966720.jpg?enhanced&format=webp'
import gxbztgrqEPRG from '../assets/icons/1999360.jpg?enhanced&format=webp'
import WRhagHouVxIA from '../assets/icons/2012840.jpg?enhanced&format=webp'
import HtOLmfEKsnOm from '../assets/icons/1286680.jpg?enhanced&format=webp'
import oMiCdClktCOM from '../assets/icons/1313140.jpg?enhanced&format=webp'
import qKmYtGWPyNjI from '../assets/icons/990080.jpg?enhanced&format=webp'
import mBXHCiGYAcoX from '../assets/icons/2215430.jpg?enhanced&format=webp'
import AhPXYCziXSjN from '../assets/icons/2399830.jpg?enhanced&format=webp'
import SXLCJKOODRLg from '../assets/icons/2420110.jpg?enhanced&format=webp'
import DLdwqAyYiGOM from '../assets/icons/1086940.jpg?enhanced&format=webp'
import xCdecVCFNoIh from '../assets/icons/1361210.jpg?enhanced&format=webp'
import hNBxkXtVtMvq from '../assets/icons/2767030.jpg?enhanced&format=webp'
import UmNNKJbwVGFh from '../assets/icons/2840770.jpg?enhanced&format=webp'
import DqUMGwEzvUvw from '../assets/icons/3065170.jpg?enhanced&format=webp'
import iwIPCdFBCaDo from '../assets/icons/3159330.jpg?enhanced&format=webp'
import otEkNTVWBFux from '../assets/icons/2246340.jpg?enhanced&format=webp'
import EpkEwabtNdPu from '../assets/icons/2124490.jpg?enhanced&format=webp'
import mxwqANasVSuR from '../assets/icons/2561580.jpg?enhanced&format=webp'
import FhoLQLqqBRJa from '../assets/icons/2694490.jpg?enhanced&format=webp'
import MdhLrbwCoCfB from '../assets/icons/440.jpg?enhanced&format=webp'
import dSaLpjToTBZP from '../assets/icons/570.jpg?enhanced&format=webp'
import kCpqZtqDjgbi from '../assets/icons/genshin.jpg?enhanced&format=webp'
import UVvICHItRryf from '../assets/icons/wow.jpg?enhanced&format=webp'

const gameIconDict: Record<string, Picture> = {
	[220]: kUGqvnVIRnew,
	[4000]: BHRoGVJrwWXL,
	[2300]: HkmKhyGNWOwd,
	[20900]: ZYQOtnwZieMC,
	[22300]: fVUgavumJJau,
	[12210]: hDvRggboyqXc,
	[17390]: RDtbcwRyogyO,
	[29800]: tdPfILZZedrA,
	[6060]: jqQSRsMKegMO,
	[550]: VcslYGwxxioR,
	[8190]: mKmIDAVjfTiC,
	[57300]: qNbNXWbsCyWO,
	[8930]: oqMZSElQaQPW,
	[40800]: OruSeaNmMCOb,
	[48190]: ahtesFocegrR,
	[620]: DvmITcphzFUv,
	[105600]: iChVzLuyZoVb,
	[20920]: MymyuoOGtENb,
	[92100]: cvidOHgHYKSo,
	[22230]: ipFZknkfrFaD,
	[3830]: SnJEvnVBhyRU,
	[204030]: LqqEIJjyJdsh,
	[207610]: MLvxycJmCJIF,
	[206440]: NdXvylWuBiMT,
	[730]: fQZthhrptjyW,
	[200260]: dQIJAjUqBoCa,
	[212680]: jfQoEDCyGwIR,
	[204360]: upSHNDHQsKfi,
	[49520]: CLkjpXqjnQCe,
	[200710]: URXzddbfSivL,
	[205100]: UrhbVcRckVno,
	[223470]: FaUFcAXgIFrr,
	[55230]: YssnUzkrDmGK,
	[220700]: eWeSwAeHKZKw,
	[224540]: FbpMZIImUgEc,
	[200210]: ZWCYpvWhVDIg,
	[208090]: FsrBHlnkhzqT,
	[230410]: HVImGrZcfOaj,
	[236390]: YLGCdEkjoPLS,
	[39000]: IdpvBIojBRid,
	[251670]: pKfxPUkcPsfG,
	[221040]: QbkznKuBryrT,
	[203160]: FrbJPkjDFkUQ,
	[47890]: vvdcLKqSwaiB,
	[233450]: dNUmHtstAfzv,
	[233720]: AUpxAJUzuuFF,
	[224760]: qCERxNBjTYYl,
	[219740]: YHyZfCWGUusZ,
	[322330]: eburiMLRaGdQ,
	[234710]: SPVHeCtFKetz,
	[72850]: fJsrepoxIUdm,
	[35720]: kyYNdIKJykzN,
	[242760]: ICtvQyfcAdrb,
	[242860]: zlSASurrUiUF,
	[242920]: pblCPvIhBRcu,
	[244850]: RTHNMaJEEJcR,
	[218620]: aJFhMArhXJEW,
	[239820]: lQEVgARdTVno,
	[252950]: xZOMoezMKJYw,
	[242050]: dRbBcReLtzXh,
	[219990]: vRqIkCzZdUGp,
	[257750]: sqhMBeZwITjj,
	[221910]: gbkDdjwtSspM,
	[209170]: NLONlpmhFUTh,
	[264140]: grKpeEUlbmXu,
	[264710]: XBSdeOqmRSfw,
	[265930]: jsEieCLVzVtq,
	[266010]: LsjosKDmgbQE,
	[211820]: HjpBTYmflkws,
	[221100]: HdSpZXnrQGrP,
	[268910]: SiCYnvaWMCNr,
	[237870]: WiPBDUlNpngA,
	[225840]: ixeXaDyRTkzA,
	[282140]: WosdlmRySHbb,
	[287700]: qGROVwysTYdN,
	[292030]: ZzYCLhxvrdxw,
	[286160]: bDCRDpwuuNlO,
	[289130]: TMTVbnPYvufU,
	[238460]: FUqGGBwpcPqP,
	[299460]: HzwOHhNhqAEs,
	[243470]: ksQYcLhZMLdL,
	[304930]: IEbCVglyidHz,
	[306020]: WTqmyFKwdmMZ,
	[9900]: ymaxLrRVaUOL,
	[311690]: zOctDChdIbnt,
	[206420]: SwiRDcyPzhnB,
	[314650]: XeGVhNJwbgek,
	[241930]: AYJFBPHllwPx,
	[322170]: HvusCGtwZLVR,
	[214490]: ULJXnyyEKIaZ,
	[238320]: wLoaIuusmDHJ,
	[327140]: hoUYiAqeJIhc,
	[327890]: IdELwubBkvWQ,
	[261640]: xxTGHtvlCphV,
	[211420]: TXnMDAZLKExA,
	[330350]: VfocPdIaOWQK,
	[298110]: GfCYlPutWQex,
	[305620]: aHFmyyIPTJmS,
	[252490]: mjmWRjzzZtsX,
	[250900]: lTygFvfbHlqD,
	[319630]: ENrDogQwoSQj,
	[219150]: REePkCyItSYl,
	[274170]: nIIPupMGbUvl,
	[346010]: UGAShxEEEYdK,
	[346110]: rMSTLDiGDuGt,
	[346900]: mLxEarDnWKZQ,
	[298630]: uYDWduRLxAsK,
	[255710]: hhnVMdpkqNNJ,
	[306130]: xmTWeyOnKWLo,
	[271590]: IISYBrrUqHrq,
	[359050]: vctivbfaAnWq,
	[363970]: rOQnAkUecYiZ,
	[365720]: MgXxIChXQcIf,
	[365670]: mbTVPthoBJxW,
	[367520]: aJnyJUjoxoLk,
	[375950]: ZIvyanBtDmqk,
	[377160]: ijbXKgBqQHzs,
	[384190]: wfXGeBWPUiGY,
	[391540]: ZRGGemOmCoYO,
	[392110]: hclGluQvlPBv,
	[393380]: otzyCMugBDcE,
	[413150]: MJvYdflvSdJm,
	[225540]: KTsEeDYEChuY,
	[417860]: UMUPsjTdwUti,
	[208650]: nGGUbRBsuxpo,
	[420530]: dcoubfGsvssg,
	[391220]: fHUlpOipEyIS,
	[427520]: KxPjswagoGpF,
	[210970]: VgHTcECHeZWE,
	[359550]: hcLYuuqsmaJm,
	[623990]: ZHrhDWxvJNcu,
	[239140]: gBjqDxrvKRIY,
	[431960]: HBcHCpAUsyeF,
	[434260]: BEPoueZXeQbF,
	[434570]: lqufndtboHDV,
	[374320]: aFQrHBnMPJAN,
	[275850]: xOAdLWkgNwsj,
	[457550]: CdujmmLtuXPX,
	[403640]: snvqZMneMYPW,
	[501300]: OkjByKFXFXEc,
	[518790]: wzXveZtoVTxb,
	[289070]: dkdoIkgalybg,
	[534380]: OPXoLsSevsfQ,
	[546560]: SQAGuGzySjNm,
	[548430]: ynZvBemzjCOy,
	[489830]: ucekVAHybkaf,
	[553850]: NRkzoWmQZpkA,
	[555160]: hLmjlZtUgRLS,
	[447040]: uPEnSnsFYyVY,
	[460920]: LRWTrWcHhoFE,
	[564710]: uSdlREMgJpqw,
	[578080]: MwCpKjoezFxq,
	[578620]: HGUzeKqKwxBf,
	[582660]: naLSoVGgEwNL,
	[588650]: JTnvhtBecLgB,
	[460930]: QtKuClQLDMPK,
	[611670]: xzigvAqHvTGe,
	[617830]: kIiZZozkDYtk,
	[619910]: AIHKMkhEqVkF,
	[620980]: sSbyXcuoHoDP,
	[629730]: SamUkSRFubvc,
	[632360]: HqTxTASKPsYG,
	[671860]: QKdmdYUQDeSs,
	[683320]: GPeMjdOdJRJf,
	[414340]: oKxzynknQkuk,
	[240720]: rkbXYXgyTBaY,
	[582160]: JLlUbjPKeqVH,
	[739630]: UKDNMHybKgNi,
	[418370]: hbOFNXvGnPEJ,
	[812140]: ALUyPUezWwHV,
	[552500]: oBEYTDioEPsB,
	[750920]: ZlyNkEDZQUZA,
	[440900]: MBpUKbKcRURv,
	[858260]: SMtkolqDKQMZ,
	[892970]: JyEEaCjlHtGi,
	[899770]: uCczSVCdnGjC,
	[814380]: CQCjaAMXGDgc,
	[993090]: SFsvbgBTAQQp,
	[524220]: OniITCYArDXK,
	[1030300]: ewonyNOpYxxu,
	[1063730]: szWWrEvbfMeJ,
	[1079800]: NNDzBZcldnMU,
	[1091500]: SsPsiaYUPURb,
	[1145360]: TaAZwcmnaSxm,
	[1151640]: ebfoLsXBTXbD,
	[1172620]: YsQSbcHqPjZD,
	[1174180]: smbdWCRrEPEo,
	[397540]: csNjPknVfpDg,
	[582010]: ipDiVietAzPT,
	[1222670]: ivGxvLwIcrkR,
	[1238840]: MlaTWQDWBoMR,
	[1237950]: QFAZBrPGumgR,
	[1245620]: jAKZpXbFEyam,
	[1151340]: nVUuvikSYarK,
	[1326470]: mLabAEOOtnib,
	[1349230]: fYxFsagxcvvO,
	[1403370]: nOpAMIyfhNxl,
	[1454400]: UBZAGILgsBxq,
	[1468260]: HhdjucwgpvRK,
	[1475810]: FCRofCTgJZTg,
	[1476970]: zpmQvGSaenhZ,
	[1562420]: EupOunFxTMwg,
	[1593500]: MKdsvBpfNrpa,
	[1599340]: sZmVmTUvCzMl,
	[1353300]: mOXRrPYsXQVe,
	[1240440]: OozILzOcwcHh,
	[1794680]: PalwqskezqXk,
	[1446780]: bjRVIpEzTshR,
	[1817070]: AAngYfvbnATl,
	[1943950]: BjwfWnvcCotg,
	[1966720]: ALJIlMIRMsIQ,
	[1999360]: gxbztgrqEPRG,
	[2012840]: WRhagHouVxIA,
	[1286680]: HtOLmfEKsnOm,
	[1313140]: oMiCdClktCOM,
	[990080]: qKmYtGWPyNjI,
	[2215430]: mBXHCiGYAcoX,
	[2399830]: AhPXYCziXSjN,
	[2420110]: SXLCJKOODRLg,
	[1086940]: DLdwqAyYiGOM,
	[1361210]: xCdecVCFNoIh,
	[2767030]: hNBxkXtVtMvq,
	[2840770]: UmNNKJbwVGFh,
	[3065170]: DqUMGwEzvUvw,
	[3159330]: iwIPCdFBCaDo,
	[2246340]: otEkNTVWBFux,
	[2124490]: EpkEwabtNdPu,
	[2561580]: mxwqANasVSuR,
	[2694490]: FhoLQLqqBRJa,
	[440]: MdhLrbwCoCfB,
	[570]: dSaLpjToTBZP,
	"genshin": kCpqZtqDjgbi,
	"wow": UVvICHItRryf
};

const getGameIcon = (appId: number | string, icon_url: string | undefined) => {
	if (gameIconDict[appId]) {
		return gameIconDict[appId]
	}
	return `https://media.steampowered.com/steamcommunity/public/images/apps/${appId}/${icon_url}.jpg`
}
export { getGameIcon }
import egVWmNsMqcDd from '../assets/profile_pictures/c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg?enhanced&format=webp&w=64;128;200'
import WqCPqwNPXLhD from '../assets/profile_pictures/dc379dfe299cead29a066037f7f2986678606c1a_full.jpg?enhanced&format=webp&w=64;128;200'
import owOwjgnsXIIs from '../assets/profile_pictures/5a2d4bcf4534f7de4e816105eceb8705084b7571_full.jpg?enhanced&format=webp&w=64;128;200'
import oTtsZuywvTTO from '../assets/profile_pictures/cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg?enhanced&format=webp&w=64;128;200'
import yNsAocuHqLnJ from '../assets/profile_pictures/56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg?enhanced&format=webp&w=64;128;200'
import xJybrcwoRhOv from '../assets/profile_pictures/b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg?enhanced&format=webp&w=64;128;200'
import LpeKUvHauPlI from '../assets/profile_pictures/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg?enhanced&format=webp&w=64;128;200'
import KoMCtXIKwzAa from '../assets/profile_pictures/cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg?enhanced&format=webp&w=64;128;200'
import jWZEYDQcmUFk from '../assets/profile_pictures/56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg?enhanced&format=webp&w=64;128;200'
import HsVmdBSoMJGt from '../assets/profile_pictures/ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg?enhanced&format=webp&w=64;128;200'
import fJKhwOiyBlFx from '../assets/profile_pictures/834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg?enhanced&format=webp&w=64;128;200'
import jwZoUnYAaHoi from '../assets/profile_pictures/aff71f9c1b1c0519b0275e7edd390e0b3f35edbe_full.jpg?enhanced&format=webp&w=64;128;200'
import umrrLWkLXYdk from '../assets/profile_pictures/7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg?enhanced&format=webp&w=64;128;200'
import MJhVVMhterwj from '../assets/profile_pictures/943df69df7a93f95109bac568dcd20e416622838_full.jpg?enhanced&format=webp&w=64;128;200'
import tpmFfqWqXlal from '../assets/profile_pictures/2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg?enhanced&format=webp&w=64;128;200'
import lzpraiyJDmHJ from '../assets/profile_pictures/0828e6eb804f312f914c446070331a35630b5d60_full.jpg?enhanced&format=webp&w=64;128;200'
import nBeWnkUIATvk from '../assets/profile_pictures/bb056dd750e1444aee38309fc04c139a5948c077_full.jpg?enhanced&format=webp&w=64;128;200'
import NKLuhMLkUegB from '../assets/profile_pictures/7968fdfccc01461706b1692ae72852e857eb8c58_full.jpg?enhanced&format=webp&w=64;128;200'
import wVyfvZzZrocu from '../assets/profile_pictures/7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg?enhanced&format=webp&w=64;128;200'
import iXbZYByGAeiZ from '../assets/profile_pictures/a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg?enhanced&format=webp&w=64;128;200'
import XCSsunddQxit from '../assets/profile_pictures/a3a4a9817d678860eeeba71b9f926fdec6a4499c_full.jpg?enhanced&format=webp&w=64;128;200'
import RpeoRGJbTEIa from '../assets/profile_pictures/9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg?enhanced&format=webp&w=64;128;200'
import DERiFzKcXyzn from '../assets/profile_pictures/920a52d890f77ba9320b48bec93d9f0212b180e8_full.jpg?enhanced&format=webp&w=64;128;200'
import hEXQMRpjKTXp from '../assets/profile_pictures/0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg?enhanced&format=webp&w=64;128;200'
import zAYNzJZdhHlB from '../assets/profile_pictures/831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg?enhanced&format=webp&w=64;128;200'
import GdRFSaNDCSJG from '../assets/profile_pictures/49acdd7acab28c9344ec286e4dae713098043b02_full.jpg?enhanced&format=webp&w=64;128;200'
import pebgEUKiptiM from '../assets/profile_pictures/50d417c0cab0a969919bd1ed9b1c2ff63c5b5d62_full.jpg?enhanced&format=webp&w=64;128;200'
import QmZiyjPLENpQ from '../assets/profile_pictures/6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg?enhanced&format=webp&w=64;128;200'
import aoOYEkuGvEca from '../assets/profile_pictures/fc5d8974fd3b0cd4519d382edd70e89172d6da5b_full.jpg?enhanced&format=webp&w=64;128;200'
import oGjwENOBvXdl from '../assets/profile_pictures/576a072e6da81175e6b47f000010d843bca92fd7_full.jpg?enhanced&format=webp&w=64;128;200'
import DtyuJcWLdBYb from '../assets/profile_pictures/7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg?enhanced&format=webp&w=64;128;200'
import wesXbWkNcInQ from '../assets/profile_pictures/9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg?enhanced&format=webp&w=64;128;200'
import fTyLinIopZZY from '../assets/profile_pictures/c5bf2d6c74344f96d3d7f4712a34393da97091b4_full.jpg?enhanced&format=webp&w=64;128;200'
import LRWKSkFUyqVn from '../assets/profile_pictures/d8c33dbc3871e0ea03d5c0f259cf198ae2092f64_full.jpg?enhanced&format=webp&w=64;128;200'
import vWsDkPnAqyAj from '../assets/profile_pictures/cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg?enhanced&format=webp&w=64;128;200'
import NoEFKudKIKtg from '../assets/profile_pictures/38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg?enhanced&format=webp&w=64;128;200'
import KBEXMABLCTIN from '../assets/profile_pictures/e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg?enhanced&format=webp&w=64;128;200'
import mjcpIFqXLVrk from '../assets/profile_pictures/5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg?enhanced&format=webp&w=64;128;200'
import hIyzjNrzsPDY from '../assets/profile_pictures/d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg?enhanced&format=webp&w=64;128;200'
import jktsOAFkKlCE from '../assets/profile_pictures/d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg?enhanced&format=webp&w=64;128;200'
import TgZkseyEumqT from '../assets/profile_pictures/79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg?enhanced&format=webp&w=64;128;200'
import IoigdKtbjpZZ from '../assets/profile_pictures/37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg?enhanced&format=webp&w=64;128;200'
import vcobsbaExcPp from '../assets/profile_pictures/83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg?enhanced&format=webp&w=64;128;200'
import jOTPXkPSkZyw from '../assets/profile_pictures/4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg?enhanced&format=webp&w=64;128;200'
import MOtWBBklQnNt from '../assets/profile_pictures/7bd7b679c5366ab21aa4e22dc10f36102ecf6517_full.jpg?enhanced&format=webp&w=64;128;200'
import PIdJlGeBaUVp from '../assets/profile_pictures/65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg?enhanced&format=webp&w=64;128;200'
import cfMOFodkcxXc from '../assets/profile_pictures/00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg?enhanced&format=webp&w=64;128;200'
import mMSHlzmkcCHC from '../assets/profile_pictures/f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg?enhanced&format=webp&w=64;128;200'
import PecfiDKZJvfT from '../assets/profile_pictures/9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg?enhanced&format=webp&w=64;128;200'
import SXhwcjWXhNhB from '../assets/profile_pictures/129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg?enhanced&format=webp&w=64;128;200'
import BkGcKHPoivrL from '../assets/profile_pictures/a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg?enhanced&format=webp&w=64;128;200'
import xtwhDTIaoEqe from '../assets/profile_pictures/c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg?enhanced&format=webp&w=64;128;200'
import BunqinPjKeUT from '../assets/profile_pictures/cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg?enhanced&format=webp&w=64;128;200'
import zFPPfVbDemTU from '../assets/profile_pictures/d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg?enhanced&format=webp&w=64;128;200'
import bzxiIrcQawTe from '../assets/profile_pictures/f83794456ffdb78206496c2a5186d1e33abe0463_full.jpg?enhanced&format=webp&w=64;128;200'
import vGnIyuLnLJWI from '../assets/profile_pictures/a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg?enhanced&format=webp&w=64;128;200'
import YILcCRTtEScl from '../assets/profile_pictures/70cf57dfeb589a5365e4ca88782f19ec34b918a7_full.jpg?enhanced&format=webp&w=64;128;200'
import VuCXlwvLGJbW from '../assets/profile_pictures/420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg?enhanced&format=webp&w=64;128;200'
import uuCDZKteulNT from '../assets/profile_pictures/1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg?enhanced&format=webp&w=64;128;200'
import CPyfqAaXqbrh from '../assets/profile_pictures/6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg?enhanced&format=webp&w=64;128;200'
import qaLvDStlwbjC from '../assets/profile_pictures/330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg?enhanced&format=webp&w=64;128;200'
import zcatwGCgCaTe from '../assets/profile_pictures/81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg?enhanced&format=webp&w=64;128;200'
import YZaxvJbjcxuM from '../assets/profile_pictures/a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg?enhanced&format=webp&w=64;128;200'
import mpgRswpRTrFT from '../assets/profile_pictures/543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg?enhanced&format=webp&w=64;128;200'
import kuvDgYlBIkVS from '../assets/profile_pictures/11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg?enhanced&format=webp&w=64;128;200'
import KyXYpWnuHKJr from '../assets/profile_pictures/2f4df64d0c63f30934fbe052f79e789d4138022c_full.jpg?enhanced&format=webp&w=64;128;200'
import xyptbJmPFNWw from '../assets/profile_pictures/203dfa2c44bce6446016a7444da7647838544183_full.jpg?enhanced&format=webp&w=64;128;200'
import plRRDnjxuGkY from '../assets/profile_pictures/efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg?enhanced&format=webp&w=64;128;200'
import QYEoYZJPOFZd from '../assets/profile_pictures/7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg?enhanced&format=webp&w=64;128;200'
import ltsSplmCXsWi from '../assets/profile_pictures/c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg?enhanced&format=webp&w=64;128;200'
import edVMBHkDVtmP from '../assets/profile_pictures/3afdedb1c5a0010111c7d96e213a1f363fe239c4_full.jpg?enhanced&format=webp&w=64;128;200'
import sCadzvbscRcb from '../assets/profile_pictures/7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg?enhanced&format=webp&w=64;128;200'
import gpFcamvfiqZk from '../assets/profile_pictures/b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg?enhanced&format=webp&w=64;128;200'
import rluiSihhrNOL from '../assets/profile_pictures/9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg?enhanced&format=webp&w=64;128;200'
import aHMJdjXhIunT from '../assets/profile_pictures/027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg?enhanced&format=webp&w=64;128;200'
import UmsqwMQbJcJh from '../assets/profile_pictures/2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg?enhanced&format=webp&w=64;128;200'
import LRNtYExlRpya from '../assets/profile_pictures/65ce13d92f99d88363a95212154eb4fb5cfbdbc2_full.jpg?enhanced&format=webp&w=64;128;200'
import WIpesxwcquze from '../assets/profile_pictures/360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg?enhanced&format=webp&w=64;128;200'
import KaEStKVLApvb from '../assets/profile_pictures/c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg?enhanced&format=webp&w=64;128;200'
import fkWqWRvxnExW from '../assets/profile_pictures/26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg?enhanced&format=webp&w=64;128;200'
import GPwORHwkQvgq from '../assets/profile_pictures/e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg?enhanced&format=webp&w=64;128;200'
import SNQpcNRGHEza from '../assets/profile_pictures/de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg?enhanced&format=webp&w=64;128;200'
import QqqKgXzNobYy from '../assets/profile_pictures/fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg?enhanced&format=webp&w=64;128;200'
import ZxZyvkWnLSYq from '../assets/profile_pictures/acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg?enhanced&format=webp&w=64;128;200'

const pfpDict: Record<string, Picture> = {
	"c6066ff51517dd60bf42a0898e7e3b1aca55684e_full.jpg": egVWmNsMqcDd,
	"dc379dfe299cead29a066037f7f2986678606c1a_full.jpg": WqCPqwNPXLhD,
	"5a2d4bcf4534f7de4e816105eceb8705084b7571_full.jpg": owOwjgnsXIIs,
	"cab15d241ec5a53395910c47fd61d12c1e282d30_full.jpg": oTtsZuywvTTO,
	"56ce84c9b37ec6f48f875cc31f215e8547f27cf1_full.jpg": yNsAocuHqLnJ,
	"b6123a945d84f07d6c8ae5809bad2ee5dc9d09a7_full.jpg": xJybrcwoRhOv,
	"fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg": LpeKUvHauPlI,
	"cd6340159dbaf0e6ed59ba5b3e71099d8eff37df_full.jpg": KoMCtXIKwzAa,
	"56267b8002808b3dfd5cacf8146d1468b95bd193_full.jpg": jWZEYDQcmUFk,
	"ebfc075b3ebedaf71215906e30326d70cf246808_full.jpg": HsVmdBSoMJGt,
	"834d1dbadc3fdcb156d591695007f0b96543d7ea_full.jpg": fJKhwOiyBlFx,
	"aff71f9c1b1c0519b0275e7edd390e0b3f35edbe_full.jpg": jwZoUnYAaHoi,
	"7d124790ae75927f8776264a947a7e08ab23eebb_full.jpg": umrrLWkLXYdk,
	"943df69df7a93f95109bac568dcd20e416622838_full.jpg": MJhVVMhterwj,
	"2f4d7ca817e9f8cbcd95b7ff2e42c77802b52927_full.jpg": tpmFfqWqXlal,
	"0828e6eb804f312f914c446070331a35630b5d60_full.jpg": lzpraiyJDmHJ,
	"bb056dd750e1444aee38309fc04c139a5948c077_full.jpg": nBeWnkUIATvk,
	"7968fdfccc01461706b1692ae72852e857eb8c58_full.jpg": NKLuhMLkUegB,
	"7ae537b6b7b7b09e68f52e76cdb8f0727f5cb270_full.jpg": wVyfvZzZrocu,
	"a0d8630658f59dd10fa494e4b0c38fcc1d2dca26_full.jpg": iXbZYByGAeiZ,
	"a3a4a9817d678860eeeba71b9f926fdec6a4499c_full.jpg": XCSsunddQxit,
	"9dbb9a46128345cdaa686acf6b60ec65ea772d44_full.jpg": RpeoRGJbTEIa,
	"920a52d890f77ba9320b48bec93d9f0212b180e8_full.jpg": DERiFzKcXyzn,
	"0ae2f2985b97dbd8b77ded6f94e5c71bbd2719a4_full.jpg": hEXQMRpjKTXp,
	"831e42f2636d4041b0a2b319bf4b984a74eb7ee2_full.jpg": zAYNzJZdhHlB,
	"49acdd7acab28c9344ec286e4dae713098043b02_full.jpg": GdRFSaNDCSJG,
	"50d417c0cab0a969919bd1ed9b1c2ff63c5b5d62_full.jpg": pebgEUKiptiM,
	"6d02661dde1719fe79a21ea63d11e95801aff997_full.jpg": QmZiyjPLENpQ,
	"fc5d8974fd3b0cd4519d382edd70e89172d6da5b_full.jpg": aoOYEkuGvEca,
	"576a072e6da81175e6b47f000010d843bca92fd7_full.jpg": oGjwENOBvXdl,
	"7fd76314aabba2d677b9d164f8085a47d3d427e8_full.jpg": DtyuJcWLdBYb,
	"9b066c0a81b28d9397d83803a5584b52c2137f4a_full.jpg": wesXbWkNcInQ,
	"c5bf2d6c74344f96d3d7f4712a34393da97091b4_full.jpg": fTyLinIopZZY,
	"d8c33dbc3871e0ea03d5c0f259cf198ae2092f64_full.jpg": LRWKSkFUyqVn,
	"cb8f081e9ca114170ea3f2013a29f89a27977a2e_full.jpg": vWsDkPnAqyAj,
	"38d97eed5cdceb06a6f1cd7ee5c53e0077a0d9dd_full.jpg": NoEFKudKIKtg,
	"e6ad6992c074e70a88d52d2efa9a0081f9209a30_full.jpg": KBEXMABLCTIN,
	"5da239ee2a26bf20694027b9731ab8e8bfff3488_full.jpg": mjcpIFqXLVrk,
	"d0b3ab6860d69415d854cdb837f53f4dba22c852_full.jpg": hIyzjNrzsPDY,
	"d31a6d26a3e10efca76b7a5acc036a5a84d7841a_full.jpg": jktsOAFkKlCE,
	"79ca8b1991335ed0b67e76b2d8d1a171616b2fba_full.jpg": TgZkseyEumqT,
	"37ad75c34c1fa2b00fea90c3445c2cbe337f901d_full.jpg": IoigdKtbjpZZ,
	"83a40ec73950db3fbb3fcf2ac5faab54d3fa14e1_full.jpg": vcobsbaExcPp,
	"4bb177d824e30f5644d8ab04b75c8d2f9345f726_full.jpg": jOTPXkPSkZyw,
	"7bd7b679c5366ab21aa4e22dc10f36102ecf6517_full.jpg": MOtWBBklQnNt,
	"65d72f8d21444977bffccad43e4c73c1399ca540_full.jpg": PIdJlGeBaUVp,
	"00b6c61cf58f01f3a2ba0c638f1935bdbd7c3ac3_full.jpg": cfMOFodkcxXc,
	"f1c5bd7f8eacbb6f8bf43bb30eac4cc5346b8b48_full.jpg": mMSHlzmkcCHC,
	"9ded280200d670ab4e76672c7c8bf7f343840e73_full.jpg": PecfiDKZJvfT,
	"129237d8bef9aab15da458a7ddc3826afdcc7e8d_full.jpg": SXhwcjWXhNhB,
	"a07a24da2a351d3729d41bfe91cdfd4f2f7c190c_full.jpg": BkGcKHPoivrL,
	"c333fd735ef0c673962312ab15a3e748839f43a3_full.jpg": xtwhDTIaoEqe,
	"cf390578eeb6d553e5dec5a3be61f2cc6a91e5d1_full.jpg": BunqinPjKeUT,
	"d4e36c18dbe43d0e21bba359c4c5e4e2480dba72_full.jpg": zFPPfVbDemTU,
	"f83794456ffdb78206496c2a5186d1e33abe0463_full.jpg": bzxiIrcQawTe,
	"a73955f5d746e6e266b5170c2eed3047928ff0b7_full.jpg": vGnIyuLnLJWI,
	"70cf57dfeb589a5365e4ca88782f19ec34b918a7_full.jpg": YILcCRTtEScl,
	"420b20d92277c688e1b1a06c17f01c0ed17f17e0_full.jpg": VuCXlwvLGJbW,
	"1058a71f3ba7ca2766ce85ededf377aa6cc2e5b1_full.jpg": uuCDZKteulNT,
	"6f38a802ed94b71d45ab9cd1700f58ff2e5b8380_full.jpg": CPyfqAaXqbrh,
	"330dbec9a70024d03cd15c72e264a5083fdafa42_full.jpg": qaLvDStlwbjC,
	"81ca4d9d7664210814097f72d3a0acab9dadff37_full.jpg": zcatwGCgCaTe,
	"a4dd0693177d0c56a04923bd0ce73c7007a29095_full.jpg": YZaxvJbjcxuM,
	"543bb32f9249e6738288c0d3ac6987ee25983c41_full.jpg": mpgRswpRTrFT,
	"11bca5d9349ac04b30d035dda045cfd77a1e0514_full.jpg": kuvDgYlBIkVS,
	"2f4df64d0c63f30934fbe052f79e789d4138022c_full.jpg": KyXYpWnuHKJr,
	"203dfa2c44bce6446016a7444da7647838544183_full.jpg": xyptbJmPFNWw,
	"efdb2e700df320cbc5920fcb78fa78b9d0d0db65_full.jpg": plRRDnjxuGkY,
	"7b1ad003ea8eb9d788de9dc7c77e5bfe64d42d7b_full.jpg": QYEoYZJPOFZd,
	"c14e98f3b50b6a4b9b6eef3b3f8f349b4c6d32f1_full.jpg": ltsSplmCXsWi,
	"3afdedb1c5a0010111c7d96e213a1f363fe239c4_full.jpg": edVMBHkDVtmP,
	"7df5b1d0f072d9b2e67bc3db5d1b78b787353b35_full.jpg": sCadzvbscRcb,
	"b1fdd40e9f8ffe7ea144734ac5e1fc0822ae1f04_full.jpg": gpFcamvfiqZk,
	"9822bd54e09e05a4410d38f46df2041f49f639f8_full.jpg": rluiSihhrNOL,
	"027710dfe5b50c36062d6da0bce8306fcc19f5e2_full.jpg": aHMJdjXhIunT,
	"2df5870951ac5a54cb81223fb469680db44c4dd4_full.jpg": UmsqwMQbJcJh,
	"65ce13d92f99d88363a95212154eb4fb5cfbdbc2_full.jpg": LRNtYExlRpya,
	"360246921050fb1677811ac0cc711e8ad088b3e3_full.jpg": WIpesxwcquze,
	"c947036a639b8b5a9ec3958ff66292014fe2f615_full.jpg": KaEStKVLApvb,
	"26458ac0a9e4a290b2edc09801b09e92ab74a747_full.jpg": fkWqWRvxnExW,
	"e3131558abb3aa1d7b8a582deff6679c1ef5f799_full.jpg": GPwORHwkQvgq,
	"de236bd8a84b137877f3f6caec80a7c0b98992e2_full.jpg": SNQpcNRGHEza,
	"fe5737d9c434682f9bc3eb425404dce233555eb8_full.jpg": QqqKgXzNobYy,
	"acf67207768cdc5be5f09aca6a9f7830bf27d6f7_full.jpg": ZxZyvkWnLSYq
};

const getProfilePicture = (profilePic: string) => {
    if (pfpDict[profilePic]) {
		return pfpDict[profilePic]
	}
    return `https://avatars.steamstatic.com/${profilePic}`
}
export { getProfilePicture }
