/**
 * NOTE: This file is auto-generated by scripts/prefetch_steam.ts
 * DO NOT modify manually
 */
import type { Picture } from 'vite-imagetools';

import AnemoBG from '../assets/genshin/misc/Anemo-bg.jpg?enhanced&format=webp';
import DendroBG from '../assets/genshin/misc/Dendro-bg.jpg?enhanced&format=webp';
import ElectroBG from '../assets/genshin/misc/Electro-bg.jpg?enhanced&format=webp';
import GeoBG from '../assets/genshin/misc/Geo-bg.jpg?enhanced&format=webp';
import CryoBG from '../assets/genshin/misc/Cryo-bg.jpg?enhanced&format=webp';
import PyroBG from '../assets/genshin/misc/Pyro-bg.jpg?enhanced&format=webp';
import HydroBG from '../assets/genshin/misc/Hydro-bg.jpg?enhanced&format=webp';

const elementBGs: Record<Element, Picture> = {
	Anemo: AnemoBG,
	Cryo: CryoBG,
	Dendro: DendroBG,
	Electro: ElectroBG,
	Geo: GeoBG,
	Hydro: HydroBG,
	Pyro: PyroBG
};
export { elementBGs };

import aijJOFEnwMpW from '../assets/genshin/characters/Arlecchino/UI_AvatarIcon_Side.png?enhanced&format=webp';
import OqhxXEeutAjb from '../assets/genshin/characters/Arlecchino/UI_Talent_S_01.png?enhanced&format=webp';
import ioSURyTsNdoZ from '../assets/genshin/characters/Arlecchino/UI_Talent_S_02.png?enhanced&format=webp';
import usNFKJmNJbDm from '../assets/genshin/characters/Arlecchino/UI_Talent_U_01.png?enhanced&format=webp';
import paFwLyoYheEE from '../assets/genshin/characters/Arlecchino/UI_Talent_S_03.png?enhanced&format=webp';
import eKBJEXsfGtSs from '../assets/genshin/characters/Arlecchino/UI_Talent_U_02.png?enhanced&format=webp';
import LjYFcTvAxtsi from '../assets/genshin/characters/Arlecchino/UI_Talent_S_04.png?enhanced&format=webp';
import NIZUvgdQmFsr from '../assets/genshin/characters/Arlecchino/Skill_E_01.png?enhanced&format=webp';
import xoTVeHcxeBXA from '../assets/genshin/characters/Arlecchino/Skill_S_01.png?enhanced&format=webp';
import mgFyCdRkTztg from '../assets/genshin/characters/Arlecchino/UI_AvatarIcon.png?enhanced&format=webp';
import lFFelWgzxQFa from '../assets/genshin/characters/Arlecchino/Skill_A_03.png?enhanced&format=webp';
import FoGEvaFOjsBg from '../assets/genshin/characters/Arlecchino/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import KpabavrUQhjP from '../assets/genshin/characters/Arlecchino/UI_Talent_S_05.png?enhanced&format=webp';
import QVszEsywjgSp from '../assets/genshin/characters/Arlecchino/UI_Talent_S_06.png?enhanced&format=webp';
import XXpsdmmAOcML from '../assets/genshin/characters/Arlecchino/UI_Talent_S_07.png?enhanced&format=webp';
import UiZZSBwgPCNj from '../assets/genshin/characters/Zhongli/UI_AvatarIcon_Side.png?enhanced&format=webp';
import BQCMWQytPqtV from '../assets/genshin/characters/Zhongli/UI_Talent_S_01.png?enhanced&format=webp';
import vlPafyQoIAar from '../assets/genshin/characters/Zhongli/UI_Talent_S_02.png?enhanced&format=webp';
import RGMQmjffOmFB from '../assets/genshin/characters/Zhongli/UI_Talent_U_01.png?enhanced&format=webp';
import UIlyTfdDwsyl from '../assets/genshin/characters/Zhongli/UI_Talent_S_03.png?enhanced&format=webp';
import ZuWlPBsnpnyb from '../assets/genshin/characters/Zhongli/UI_Talent_U_02.png?enhanced&format=webp';
import JAjZCUSHyrHM from '../assets/genshin/characters/Zhongli/UI_Talent_S_04.png?enhanced&format=webp';
import NEWczBeIrdvk from '../assets/genshin/characters/Zhongli/Skill_E_01.png?enhanced&format=webp';
import KhMJfzumvomJ from '../assets/genshin/characters/Zhongli/Skill_S_01.png?enhanced&format=webp';
import PazwIhQwQMJB from '../assets/genshin/characters/Zhongli/UI_AvatarIcon.png?enhanced&format=webp';
import oLrfHcmWUfbY from '../assets/genshin/characters/Zhongli/Skill_A_03.png?enhanced&format=webp';
import gzKgLJzgIdln from '../assets/genshin/characters/Zhongli/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import TbVEKbuVgUDc from '../assets/genshin/characters/Zhongli/UI_Talent_S_05.png?enhanced&format=webp';
import kxdnqbsuSWil from '../assets/genshin/characters/Zhongli/UI_Talent_S_06.png?enhanced&format=webp';
import IGTbOzmGEwIi from '../assets/genshin/characters/Zhongli/UI_Talent_Forge_Pole.png?enhanced&format=webp';
import EMSjreeAwNkc from '../assets/genshin/characters/Yelan/UI_AvatarIcon_Side.png?enhanced&format=webp';
import fnlVJTvsUBom from '../assets/genshin/characters/Yelan/UI_Talent_S_01.png?enhanced&format=webp';
import TwjAUkKXvnpf from '../assets/genshin/characters/Yelan/UI_Talent_S_02.png?enhanced&format=webp';
import mMmSeTmvSHWX from '../assets/genshin/characters/Yelan/UI_Talent_U_01.png?enhanced&format=webp';
import WkpEkajrXeaw from '../assets/genshin/characters/Yelan/UI_Talent_S_03.png?enhanced&format=webp';
import cQlEyPDWWpkI from '../assets/genshin/characters/Yelan/UI_Talent_U_02.png?enhanced&format=webp';
import uTRdYrigSkBe from '../assets/genshin/characters/Yelan/UI_Talent_S_04.png?enhanced&format=webp';
import fNVKetKHKidm from '../assets/genshin/characters/Yelan/Skill_E_01.png?enhanced&format=webp';
import vyZlTlfDpAjQ from '../assets/genshin/characters/Yelan/Skill_S_01.png?enhanced&format=webp';
import mzeKFolaKWwT from '../assets/genshin/characters/Yelan/UI_AvatarIcon.png?enhanced&format=webp';
import vslfXCYZkqzZ from '../assets/genshin/characters/Yelan/Skill_A_02.png?enhanced&format=webp';
import JeVWABXPcLdi from '../assets/genshin/characters/Yelan/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import luSXDXrZEldj from '../assets/genshin/characters/Yelan/UI_Talent_S_05.png?enhanced&format=webp';
import DXbBLWtQhYVJ from '../assets/genshin/characters/Yelan/UI_Talent_S_06.png?enhanced&format=webp';
import uSeLPimfQAdT from '../assets/genshin/characters/Yelan/UI_Talent_Expedition_Liyue.png?enhanced&format=webp';
import jNDhsmkGrfOD from '../assets/genshin/characters/Xingqiu/UI_AvatarIcon_Side.png?enhanced&format=webp';
import JFpbFZHPpXaY from '../assets/genshin/characters/Xingqiu/UI_Talent_S_01.png?enhanced&format=webp';
import lSoFUmmktCnj from '../assets/genshin/characters/Xingqiu/UI_Talent_S_02.png?enhanced&format=webp';
import LuqtzTznxhhV from '../assets/genshin/characters/Xingqiu/UI_Talent_U_01.png?enhanced&format=webp';
import EOQKtvlCdJGU from '../assets/genshin/characters/Xingqiu/UI_Talent_S_03.png?enhanced&format=webp';
import UJkkvAPqsakp from '../assets/genshin/characters/Xingqiu/UI_Talent_U_02.png?enhanced&format=webp';
import kVTYGpeRLliO from '../assets/genshin/characters/Xingqiu/UI_Talent_S_04.png?enhanced&format=webp';
import KukCGDHfpyjz from '../assets/genshin/characters/Xingqiu/Skill_E_01.png?enhanced&format=webp';
import wiESmLVHHSEF from '../assets/genshin/characters/Xingqiu/Skill_S_01.png?enhanced&format=webp';
import brLWislAysgX from '../assets/genshin/characters/Xingqiu/UI_AvatarIcon.png?enhanced&format=webp';
import whzcuWjEBeDM from '../assets/genshin/characters/Xingqiu/Skill_A_01.png?enhanced&format=webp';
import AXnRLyXXRTbw from '../assets/genshin/characters/Xingqiu/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import BQErGFWAEvAh from '../assets/genshin/characters/Xingqiu/UI_Talent_S_05.png?enhanced&format=webp';
import aTCiEzQWOgNe from '../assets/genshin/characters/Xingqiu/UI_Talent_S_06.png?enhanced&format=webp';
import ocyQjyBkYmlX from '../assets/genshin/characters/Xingqiu/UI_Talent_Combine_Talent.png?enhanced&format=webp';
import zlvglxFHlxhX from '../assets/genshin/characters/Xiao/UI_AvatarIcon_Side.png?enhanced&format=webp';
import HWLQJWZmLKCz from '../assets/genshin/characters/Xiao/UI_Talent_S_01.png?enhanced&format=webp';
import HZMaOCsFegjI from '../assets/genshin/characters/Xiao/UI_Talent_S_02.png?enhanced&format=webp';
import GayDlulpBCOl from '../assets/genshin/characters/Xiao/UI_Talent_U_01.png?enhanced&format=webp';
import CWZvBzGxZpeR from '../assets/genshin/characters/Xiao/UI_Talent_S_03.png?enhanced&format=webp';
import wrUnvHLDNFZR from '../assets/genshin/characters/Xiao/UI_Talent_U_02.png?enhanced&format=webp';
import JkJVlunyaLSw from '../assets/genshin/characters/Xiao/UI_Talent_S_04.png?enhanced&format=webp';
import GCElakeBDMDi from '../assets/genshin/characters/Xiao/Skill_E_01.png?enhanced&format=webp';
import YgQngpsAMnMp from '../assets/genshin/characters/Xiao/Skill_S_01.png?enhanced&format=webp';
import sFtnldNpTgHX from '../assets/genshin/characters/Xiao/UI_AvatarIcon.png?enhanced&format=webp';
import LPdszIDyUKSw from '../assets/genshin/characters/Xiao/Skill_A_03.png?enhanced&format=webp';
import qAPJcadoMtVu from '../assets/genshin/characters/Xiao/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import iwvmbtubfeTf from '../assets/genshin/characters/Xiao/UI_Talent_S_05.png?enhanced&format=webp';
import ZiFTuODGnhlD from '../assets/genshin/characters/Xiao/UI_Talent_S_06.png?enhanced&format=webp';
import qrgmahaJxpJf from '../assets/genshin/characters/Xiao/UI_Talent_Explosion_Climb.png?enhanced&format=webp';
import bNaJFqaTenxG from '../assets/genshin/characters/Xianyun/UI_AvatarIcon_Side_Liuyun.png?enhanced&format=webp';
import ykLiCNiebVzf from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_01.png?enhanced&format=webp';
import lgKUDIOhRTYh from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_02.png?enhanced&format=webp';
import xoQtsoFkUoTW from '../assets/genshin/characters/Xianyun/UI_Talent_U_Liuyun_02.png?enhanced&format=webp';
import nUthIgyrEGdb from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_03.png?enhanced&format=webp';
import QhUoHfdnaVRY from '../assets/genshin/characters/Xianyun/UI_Talent_U_Liuyun_01.png?enhanced&format=webp';
import oIRYpxpgZKuc from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_04.png?enhanced&format=webp';
import boWETFFOPpeX from '../assets/genshin/characters/Xianyun/Skill_E_Liuyun_01.png?enhanced&format=webp';
import WRmDdiWKyBFm from '../assets/genshin/characters/Xianyun/Skill_S_Liuyun_01.png?enhanced&format=webp';
import xtjhYPzxBAXa from '../assets/genshin/characters/Xianyun/UI_AvatarIcon_Liuyun.png?enhanced&format=webp';
import WqAotZxiBSjL from '../assets/genshin/characters/Xianyun/Skill_A_Catalyst_MD.png?enhanced&format=webp';
import UKhgYKerZTUK from '../assets/genshin/characters/Xianyun/UI_Gacha_AvatarImg_Liuyun.png?enhanced&format=webp';
import WTkpCcNtDPrQ from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_05.png?enhanced&format=webp';
import RbPBeiiGkGWM from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_06.png?enhanced&format=webp';
import FhCYWRvuBikT from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_07.png?enhanced&format=webp';
import rLKPkWIsDslB from '../assets/genshin/characters/Faruzan/UI_AvatarIcon_Side.png?enhanced&format=webp';
import qiLXBjlqFgej from '../assets/genshin/characters/Faruzan/UI_Talent_S_01.png?enhanced&format=webp';
import aqLecDCoYbCc from '../assets/genshin/characters/Faruzan/UI_Talent_S_02.png?enhanced&format=webp';
import pbIurTukHasf from '../assets/genshin/characters/Faruzan/UI_Talent_U_01.png?enhanced&format=webp';
import KmJDZxOUaOhz from '../assets/genshin/characters/Faruzan/UI_Talent_S_03.png?enhanced&format=webp';
import XmYoFPSzpuLV from '../assets/genshin/characters/Faruzan/UI_Talent_U_02.png?enhanced&format=webp';
import AIgUbrStntNa from '../assets/genshin/characters/Faruzan/UI_Talent_S_04.png?enhanced&format=webp';
import OrJkcTrYbKUm from '../assets/genshin/characters/Faruzan/Skill_E_01.png?enhanced&format=webp';
import FSKklVuQHTKw from '../assets/genshin/characters/Faruzan/Skill_S_01.png?enhanced&format=webp';
import JatCVBPRiyVp from '../assets/genshin/characters/Faruzan/UI_AvatarIcon.png?enhanced&format=webp';
import YXpiXTjrByQE from '../assets/genshin/characters/Faruzan/Skill_A_02.png?enhanced&format=webp';
import qXKSLMQSEtWB from '../assets/genshin/characters/Faruzan/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import zhJGqhGEQsxp from '../assets/genshin/characters/Faruzan/UI_Talent_S_05.png?enhanced&format=webp';
import pNibnxGkdcfU from '../assets/genshin/characters/Faruzan/UI_Talent_S_06.png?enhanced&format=webp';
import OxTrUPAgYbZu from '../assets/genshin/characters/Faruzan/UI_Talent_S_Cyno_07.png?enhanced&format=webp';
import iVVWdbOwexfW from '../assets/genshin/characters/Furina/UI_AvatarIcon_Side.png?enhanced&format=webp';
import JjPFcccmlXYS from '../assets/genshin/characters/Furina/UI_Talent_S_01.png?enhanced&format=webp';
import xoPEPiDaFzUx from '../assets/genshin/characters/Furina/UI_Talent_S_04.png?enhanced&format=webp';
import upgwhxYAoHCp from '../assets/genshin/characters/Furina/UI_Talent_U_02.png?enhanced&format=webp';
import YidvkhVmgjyg from '../assets/genshin/characters/Furina/UI_Talent_S_03.png?enhanced&format=webp';
import LnXYiEyakVbM from '../assets/genshin/characters/Furina/UI_Talent_U_01.png?enhanced&format=webp';
import KSMuzYxTYtFd from '../assets/genshin/characters/Furina/UI_Talent_S_02.png?enhanced&format=webp';
import yCxwlRBsDQvB from '../assets/genshin/characters/Furina/Skill_E_01.png?enhanced&format=webp';
import QrJdTsoQUNLz from '../assets/genshin/characters/Furina/Skill_S_01.png?enhanced&format=webp';
import FsFqTlqcBbbt from '../assets/genshin/characters/Furina/UI_AvatarIcon.png?enhanced&format=webp';
import tWzbgyRSzRBx from '../assets/genshin/characters/Furina/Skill_A_01.png?enhanced&format=webp';
import ewXfqOarNsTt from '../assets/genshin/characters/Furina/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import LZfynIKHMmsR from '../assets/genshin/characters/Furina/UI_Talent_S_05.png?enhanced&format=webp';
import HRhUAqxHJVnj from '../assets/genshin/characters/Furina/UI_Talent_S_06.png?enhanced&format=webp';
import QmTLxixLWMRd from '../assets/genshin/characters/Furina/UI_Talent_S_07.png?enhanced&format=webp';
import NHVGejRbwzsX from '../assets/genshin/characters/Nahida/UI_AvatarIcon_Side.png?enhanced&format=webp';
import YwsFyesOtRjy from '../assets/genshin/characters/Nahida/UI_Talent_S_01.png?enhanced&format=webp';
import gRHvAIZjViTA from '../assets/genshin/characters/Nahida/UI_Talent_S_02.png?enhanced&format=webp';
import EkYEnWjNEHTs from '../assets/genshin/characters/Nahida/UI_Talent_U_01.png?enhanced&format=webp';
import ikOQpcrYBLxy from '../assets/genshin/characters/Nahida/UI_Talent_S_03.png?enhanced&format=webp';
import VnpPiCKXRugr from '../assets/genshin/characters/Nahida/UI_Talent_U_02.png?enhanced&format=webp';
import PHOxSiwGKEGC from '../assets/genshin/characters/Nahida/UI_Talent_S_04.png?enhanced&format=webp';
import aFzZRFuuCzzB from '../assets/genshin/characters/Nahida/Skill_E_01.png?enhanced&format=webp';
import azfwZtgrUsnQ from '../assets/genshin/characters/Nahida/Skill_S_01.png?enhanced&format=webp';
import UiYlgIRTZfgk from '../assets/genshin/characters/Nahida/UI_AvatarIcon.png?enhanced&format=webp';
import YXFXfuILReus from '../assets/genshin/characters/Nahida/Skill_A_Catalyst_MD.png?enhanced&format=webp';
import wYtwRlinXeyD from '../assets/genshin/characters/Nahida/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import EzzHqoaORPWc from '../assets/genshin/characters/Nahida/UI_Talent_S_05.png?enhanced&format=webp';
import aLZONyluFtXx from '../assets/genshin/characters/Nahida/UI_Talent_S_06.png?enhanced&format=webp';
import nMyibttJNcPC from '../assets/genshin/characters/Nahida/UI_Talent_S_07.png?enhanced&format=webp';
import QGidpLwCxpST from '../assets/genshin/characters/RaidenShogun/UI_AvatarIcon_Side_Shougun.png?enhanced&format=webp';
import xZUTzqRbwYpJ from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_01.png?enhanced&format=webp';
import hEiPHlgWaKVU from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_03.png?enhanced&format=webp';
import icQoCxFSUXND from '../assets/genshin/characters/RaidenShogun/UI_Talent_U_Shougun_02.png?enhanced&format=webp';
import jbfaUOjIjDmF from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_02.png?enhanced&format=webp';
import lVSkTaDVmVuN from '../assets/genshin/characters/RaidenShogun/UI_Talent_U_Shougun_01.png?enhanced&format=webp';
import jcAcJANBoCDt from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_04.png?enhanced&format=webp';
import MMKVOsZpqRYP from '../assets/genshin/characters/RaidenShogun/Skill_E_Shougun_01.png?enhanced&format=webp';
import QLfaKHWCjRUX from '../assets/genshin/characters/RaidenShogun/Skill_S_Shougun_01.png?enhanced&format=webp';
import XwrhFDFLCLvi from '../assets/genshin/characters/RaidenShogun/UI_AvatarIcon_Shougun.png?enhanced&format=webp';
import MVNDjVAMJNtL from '../assets/genshin/characters/RaidenShogun/Skill_A_03.png?enhanced&format=webp';
import JrnKvPUlzXdq from '../assets/genshin/characters/RaidenShogun/UI_Gacha_AvatarImg_Shougun.png?enhanced&format=webp';
import TeKwCYamaQkl from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_05.png?enhanced&format=webp';
import UBAzNptLnbjW from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_06.png?enhanced&format=webp';
import CkJZuecuwwJq from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_07.png?enhanced&format=webp';
import ZJJPzlnAKtLR from '../assets/genshin/characters/KaedeharaKazuha/UI_AvatarIcon_Side_Kazuha.png?enhanced&format=webp';
import meVjYwqGsiKG from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_01.png?enhanced&format=webp';
import JKKPXRqxgKNu from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_02.png?enhanced&format=webp';
import aIrLmDatzkMi from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_U_Kazuha_01.png?enhanced&format=webp';
import DSbEPSyGINnd from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_03.png?enhanced&format=webp';
import OJegXUYfNgSg from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_U_Kazuha_02.png?enhanced&format=webp';
import APeGxqXTvQTY from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_04.png?enhanced&format=webp';
import xulWFzAZxJwS from '../assets/genshin/characters/KaedeharaKazuha/Skill_E_Kazuha_01.png?enhanced&format=webp';
import JbdrpCNgIwjh from '../assets/genshin/characters/KaedeharaKazuha/Skill_S_Kazuha_01.png?enhanced&format=webp';
import mIacsJaJhHAW from '../assets/genshin/characters/KaedeharaKazuha/UI_AvatarIcon_Kazuha.png?enhanced&format=webp';
import DLzMPjTLrPEx from '../assets/genshin/characters/KaedeharaKazuha/Skill_A_01.png?enhanced&format=webp';
import nkVriimvcvtE from '../assets/genshin/characters/KaedeharaKazuha/UI_Gacha_AvatarImg_Kazuha.png?enhanced&format=webp';
import wGzwLhCKAYfB from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_05.png?enhanced&format=webp';
import eFuILmXDwduJ from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_06.png?enhanced&format=webp';
import lrJrEqywwVlK from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_Explosion_Sprint.png?enhanced&format=webp';
import bziGnnxmzYKT from '../assets/genshin/characters/HuTao/UI_AvatarIcon_Side_Hutao.png?enhanced&format=webp';
import OQxxprkmVouo from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_03.png?enhanced&format=webp';
import WVNqVUVfOzVD from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_01.png?enhanced&format=webp';
import OGdHwGNdrmbr from '../assets/genshin/characters/HuTao/UI_Talent_U_Hutao_01.png?enhanced&format=webp';
import wAGnREPEoXlu from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_02.png?enhanced&format=webp';
import mUJtJjToYOUj from '../assets/genshin/characters/HuTao/UI_Talent_U_Hutao_02.png?enhanced&format=webp';
import lgbBKaUuXPCA from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_04.png?enhanced&format=webp';
import uPtJsFzqrEkp from '../assets/genshin/characters/HuTao/Skill_E_Hutao_01.png?enhanced&format=webp';
import oUhBneRvZFjK from '../assets/genshin/characters/HuTao/Skill_S_Hutao_01.png?enhanced&format=webp';
import GiFnZOfLUQxQ from '../assets/genshin/characters/HuTao/UI_AvatarIcon_Hutao.png?enhanced&format=webp';
import BLkDmaIRdKtp from '../assets/genshin/characters/HuTao/Skill_A_03.png?enhanced&format=webp';
import bzfGChmhVRbS from '../assets/genshin/characters/HuTao/UI_Gacha_AvatarImg_Hutao.png?enhanced&format=webp';
import iYhafVFqdAgN from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_05.png?enhanced&format=webp';
import rWvIqIOtSQvG from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_06.png?enhanced&format=webp';
import QjktNfIekpzd from '../assets/genshin/characters/HuTao/UI_Talent_Cook_ExtraFailedItem.png?enhanced&format=webp';

type CharacterImageKey =
	| 'sideIcon'
	| 'con_0'
	| 'con_1'
	| 'con_2'
	| 'con_3'
	| 'con_4'
	| 'con_5'
	| 'burst'
	| 'skill'
	| 'characterIcon'
	| 'normal'
	| 'splashImage'
	| 'talent_0'
	| 'talent_1'
	| 'talent_2';

type CharacterCacheKey =
	| 'Arlecchino'
	| 'Zhongli'
	| 'Yelan'
	| 'Xingqiu'
	| 'Xiao'
	| 'Xianyun'
	| 'Faruzan'
	| 'Furina'
	| 'Nahida'
	| 'RaidenShogun'
	| 'KaedeharaKazuha'
	| 'HuTao';

const characterImageDict: Record<CharacterCacheKey, Record<CharacterImageKey, Picture>> = {
	Arlecchino: {
		sideIcon: aijJOFEnwMpW,
		con_0: OqhxXEeutAjb,
		con_1: ioSURyTsNdoZ,
		con_2: usNFKJmNJbDm,
		con_3: paFwLyoYheEE,
		con_4: eKBJEXsfGtSs,
		con_5: LjYFcTvAxtsi,
		burst: NIZUvgdQmFsr,
		skill: xoTVeHcxeBXA,
		characterIcon: mgFyCdRkTztg,
		normal: lFFelWgzxQFa,
		splashImage: FoGEvaFOjsBg,
		talent_0: KpabavrUQhjP,
		talent_1: QVszEsywjgSp,
		talent_2: XXpsdmmAOcML
	},
	Zhongli: {
		sideIcon: UiZZSBwgPCNj,
		con_0: BQCMWQytPqtV,
		con_1: vlPafyQoIAar,
		con_2: RGMQmjffOmFB,
		con_3: UIlyTfdDwsyl,
		con_4: ZuWlPBsnpnyb,
		con_5: JAjZCUSHyrHM,
		burst: NEWczBeIrdvk,
		skill: KhMJfzumvomJ,
		characterIcon: PazwIhQwQMJB,
		normal: oLrfHcmWUfbY,
		splashImage: gzKgLJzgIdln,
		talent_0: TbVEKbuVgUDc,
		talent_1: kxdnqbsuSWil,
		talent_2: IGTbOzmGEwIi
	},
	Yelan: {
		sideIcon: EMSjreeAwNkc,
		con_0: fnlVJTvsUBom,
		con_1: TwjAUkKXvnpf,
		con_2: mMmSeTmvSHWX,
		con_3: WkpEkajrXeaw,
		con_4: cQlEyPDWWpkI,
		con_5: uTRdYrigSkBe,
		burst: fNVKetKHKidm,
		skill: vyZlTlfDpAjQ,
		characterIcon: mzeKFolaKWwT,
		normal: vslfXCYZkqzZ,
		splashImage: JeVWABXPcLdi,
		talent_0: luSXDXrZEldj,
		talent_1: DXbBLWtQhYVJ,
		talent_2: uSeLPimfQAdT
	},
	Xingqiu: {
		sideIcon: jNDhsmkGrfOD,
		con_0: JFpbFZHPpXaY,
		con_1: lSoFUmmktCnj,
		con_2: LuqtzTznxhhV,
		con_3: EOQKtvlCdJGU,
		con_4: UJkkvAPqsakp,
		con_5: kVTYGpeRLliO,
		burst: KukCGDHfpyjz,
		skill: wiESmLVHHSEF,
		characterIcon: brLWislAysgX,
		normal: whzcuWjEBeDM,
		splashImage: AXnRLyXXRTbw,
		talent_0: BQErGFWAEvAh,
		talent_1: aTCiEzQWOgNe,
		talent_2: ocyQjyBkYmlX
	},
	Xiao: {
		sideIcon: zlvglxFHlxhX,
		con_0: HWLQJWZmLKCz,
		con_1: HZMaOCsFegjI,
		con_2: GayDlulpBCOl,
		con_3: CWZvBzGxZpeR,
		con_4: wrUnvHLDNFZR,
		con_5: JkJVlunyaLSw,
		burst: GCElakeBDMDi,
		skill: YgQngpsAMnMp,
		characterIcon: sFtnldNpTgHX,
		normal: LPdszIDyUKSw,
		splashImage: qAPJcadoMtVu,
		talent_0: iwvmbtubfeTf,
		talent_1: ZiFTuODGnhlD,
		talent_2: qrgmahaJxpJf
	},
	Xianyun: {
		sideIcon: bNaJFqaTenxG,
		con_0: ykLiCNiebVzf,
		con_1: lgKUDIOhRTYh,
		con_2: xoQtsoFkUoTW,
		con_3: nUthIgyrEGdb,
		con_4: QhUoHfdnaVRY,
		con_5: oIRYpxpgZKuc,
		burst: boWETFFOPpeX,
		skill: WRmDdiWKyBFm,
		characterIcon: xtjhYPzxBAXa,
		normal: WqAotZxiBSjL,
		splashImage: UKhgYKerZTUK,
		talent_0: WTkpCcNtDPrQ,
		talent_1: RbPBeiiGkGWM,
		talent_2: FhCYWRvuBikT
	},
	Faruzan: {
		sideIcon: rLKPkWIsDslB,
		con_0: qiLXBjlqFgej,
		con_1: aqLecDCoYbCc,
		con_2: pbIurTukHasf,
		con_3: KmJDZxOUaOhz,
		con_4: XmYoFPSzpuLV,
		con_5: AIgUbrStntNa,
		burst: OrJkcTrYbKUm,
		skill: FSKklVuQHTKw,
		characterIcon: JatCVBPRiyVp,
		normal: YXpiXTjrByQE,
		splashImage: qXKSLMQSEtWB,
		talent_0: zhJGqhGEQsxp,
		talent_1: pNibnxGkdcfU,
		talent_2: OxTrUPAgYbZu
	},
	Furina: {
		sideIcon: iVVWdbOwexfW,
		con_0: JjPFcccmlXYS,
		con_1: xoPEPiDaFzUx,
		con_2: upgwhxYAoHCp,
		con_3: YidvkhVmgjyg,
		con_4: LnXYiEyakVbM,
		con_5: KSMuzYxTYtFd,
		burst: yCxwlRBsDQvB,
		skill: QrJdTsoQUNLz,
		characterIcon: FsFqTlqcBbbt,
		normal: tWzbgyRSzRBx,
		splashImage: ewXfqOarNsTt,
		talent_0: LZfynIKHMmsR,
		talent_1: HRhUAqxHJVnj,
		talent_2: QmTLxixLWMRd
	},
	Nahida: {
		sideIcon: NHVGejRbwzsX,
		con_0: YwsFyesOtRjy,
		con_1: gRHvAIZjViTA,
		con_2: EkYEnWjNEHTs,
		con_3: ikOQpcrYBLxy,
		con_4: VnpPiCKXRugr,
		con_5: PHOxSiwGKEGC,
		burst: aFzZRFuuCzzB,
		skill: azfwZtgrUsnQ,
		characterIcon: UiYlgIRTZfgk,
		normal: YXFXfuILReus,
		splashImage: wYtwRlinXeyD,
		talent_0: EzzHqoaORPWc,
		talent_1: aLZONyluFtXx,
		talent_2: nMyibttJNcPC
	},
	RaidenShogun: {
		sideIcon: QGidpLwCxpST,
		con_0: xZUTzqRbwYpJ,
		con_1: hEiPHlgWaKVU,
		con_2: icQoCxFSUXND,
		con_3: jbfaUOjIjDmF,
		con_4: lVSkTaDVmVuN,
		con_5: jcAcJANBoCDt,
		burst: MMKVOsZpqRYP,
		skill: QLfaKHWCjRUX,
		characterIcon: XwrhFDFLCLvi,
		normal: MVNDjVAMJNtL,
		splashImage: JrnKvPUlzXdq,
		talent_0: TeKwCYamaQkl,
		talent_1: UBAzNptLnbjW,
		talent_2: CkJZuecuwwJq
	},
	KaedeharaKazuha: {
		sideIcon: ZJJPzlnAKtLR,
		con_0: meVjYwqGsiKG,
		con_1: JKKPXRqxgKNu,
		con_2: aIrLmDatzkMi,
		con_3: DSbEPSyGINnd,
		con_4: OJegXUYfNgSg,
		con_5: APeGxqXTvQTY,
		burst: xulWFzAZxJwS,
		skill: JbdrpCNgIwjh,
		characterIcon: mIacsJaJhHAW,
		normal: DLzMPjTLrPEx,
		splashImage: nkVriimvcvtE,
		talent_0: wGzwLhCKAYfB,
		talent_1: eFuILmXDwduJ,
		talent_2: lrJrEqywwVlK
	},
	HuTao: {
		sideIcon: bziGnnxmzYKT,
		con_0: OQxxprkmVouo,
		con_1: WVNqVUVfOzVD,
		con_2: OGdHwGNdrmbr,
		con_3: wAGnREPEoXlu,
		con_4: mUJtJjToYOUj,
		con_5: lgbBKaUuXPCA,
		burst: uPtJsFzqrEkp,
		skill: oUhBneRvZFjK,
		characterIcon: GiFnZOfLUQxQ,
		normal: BLkDmaIRdKtp,
		splashImage: bzfGChmhVRbS,
		talent_0: iYhafVFqdAgN,
		talent_1: rWvIqIOtSQvG,
		talent_2: QjktNfIekpzd
	}
};
const getCharacterImage = (character: CharacterCacheKey, image: CharacterImageKey) => {
	return characterImageDict[character][image];
};

export { getCharacterImage };
export type { CharacterCacheKey };

import SIBuwMtPbDfc from '../assets/genshin/weapons/StaffOfHoma/UI_EquipIcon_Pole_Homa.png?enhanced&format=webp';
import XfnpRutGWVmJ from '../assets/genshin/weapons/StaffOfHoma/UI_EquipIcon_Pole_Homa_Awaken.png?enhanced&format=webp';
import JByFNyhaPyVb from '../assets/genshin/weapons/StaffOfHoma/UI_Gacha_EquipIcon_Pole_Homa.png?enhanced&format=webp';
import QbnxSwXsqHlm from '../assets/genshin/weapons/BlackTassel/UI_EquipIcon_Pole_Noire.png?enhanced&format=webp';
import tXbIgfeWVDWJ from '../assets/genshin/weapons/BlackTassel/UI_EquipIcon_Pole_Noire_Awaken.png?enhanced&format=webp';
import pjLclRFHVOKN from '../assets/genshin/weapons/BlackTassel/UI_Gacha_EquipIcon_Pole_Noire.png?enhanced&format=webp';
import bWzXRKuHDPDY from '../assets/genshin/weapons/AquaSimulacra/UI_EquipIcon_Bow_Kirin.png?enhanced&format=webp';
import MdIcZbjMpSPL from '../assets/genshin/weapons/AquaSimulacra/UI_EquipIcon_Bow_Kirin_Awaken.png?enhanced&format=webp';
import csuOIoqHdQMl from '../assets/genshin/weapons/AquaSimulacra/UI_Gacha_EquipIcon_Bow_Kirin.png?enhanced&format=webp';
import yVbeJmbYAUBG from '../assets/genshin/weapons/SkywardBlade/UI_EquipIcon_Sword_Dvalin.png?enhanced&format=webp';
import DRNiOdnoTXLl from '../assets/genshin/weapons/SkywardBlade/UI_EquipIcon_Sword_Dvalin_Awaken.png?enhanced&format=webp';
import YfiYfpZbubbq from '../assets/genshin/weapons/SkywardBlade/UI_Gacha_EquipIcon_Sword_Dvalin.png?enhanced&format=webp';
import UAvrSnJNDDfK from '../assets/genshin/weapons/OathswornEye/UI_EquipIcon_Catalyst_Jyanome.png?enhanced&format=webp';
import uAxOUIwYKIqx from '../assets/genshin/weapons/OathswornEye/UI_EquipIcon_Catalyst_Jyanome_Awaken.png?enhanced&format=webp';
import bqzzrhhYskrx from '../assets/genshin/weapons/OathswornEye/UI_Gacha_EquipIcon_Catalyst_Jyanome.png?enhanced&format=webp';
import OfmcAJSFXZOI from '../assets/genshin/weapons/FavoniusWarbow/UI_EquipIcon_Bow_Zephyrus.png?enhanced&format=webp';
import amuLIQmQkiZJ from '../assets/genshin/weapons/FavoniusWarbow/UI_EquipIcon_Bow_Zephyrus_Awaken.png?enhanced&format=webp';
import xeWuJqsGuXND from '../assets/genshin/weapons/FavoniusWarbow/UI_Gacha_EquipIcon_Bow_Zephyrus.png?enhanced&format=webp';
import pHzQoTsCFdVm from '../assets/genshin/weapons/FleuveCendreFerryman/UI_EquipIcon_Sword_Machination.png?enhanced&format=webp';
import LTJhgITSqBQY from '../assets/genshin/weapons/FleuveCendreFerryman/UI_EquipIcon_Sword_Machination_Awaken.png?enhanced&format=webp';
import GShNNbacgzlG from '../assets/genshin/weapons/FleuveCendreFerryman/UI_Gacha_EquipIcon_Sword_Machination.png?enhanced&format=webp';
import hkiyFbGOIazx from '../assets/genshin/weapons/SacrificialFragments/UI_EquipIcon_Catalyst_Fossil.png?enhanced&format=webp';
import igcEezFElToO from '../assets/genshin/weapons/SacrificialFragments/UI_EquipIcon_Catalyst_Fossil_Awaken.png?enhanced&format=webp';
import nClbSqKgVEHG from '../assets/genshin/weapons/SacrificialFragments/UI_Gacha_EquipIcon_Catalyst_Fossil.png?enhanced&format=webp';
import YkrcHohBonpG from '../assets/genshin/weapons/DragonsBane/UI_EquipIcon_Pole_Stardust.png?enhanced&format=webp';
import NVIECvbToIho from '../assets/genshin/weapons/DragonsBane/UI_EquipIcon_Pole_Stardust_Awaken.png?enhanced&format=webp';
import JWdigXeSaIxS from '../assets/genshin/weapons/DragonsBane/UI_Gacha_EquipIcon_Pole_Stardust.png?enhanced&format=webp';
import XpAAPjrnvLqC from '../assets/genshin/weapons/FavoniusSword/UI_EquipIcon_Sword_Zephyrus.png?enhanced&format=webp';
import VlXksFyNbxLC from '../assets/genshin/weapons/FavoniusSword/UI_EquipIcon_Sword_Zephyrus_Awaken.png?enhanced&format=webp';
import RAEppvaFxbQB from '../assets/genshin/weapons/FavoniusSword/UI_Gacha_EquipIcon_Sword_Zephyrus.png?enhanced&format=webp';
import izjnnJlCYkow from '../assets/genshin/weapons/CalamityQueller/UI_EquipIcon_Pole_Santika.png?enhanced&format=webp';
import xjkwAgcffklh from '../assets/genshin/weapons/CalamityQueller/UI_EquipIcon_Pole_Santika_Awaken.png?enhanced&format=webp';
import tConBiujVrMA from '../assets/genshin/weapons/CalamityQueller/UI_Gacha_EquipIcon_Pole_Santika.png?enhanced&format=webp';

type WeaponImageKey = 'baseIocn' | 'awakenIcon' | 'splashImage';

type WeaponCacheKey =
	| 'StaffOfHoma'
	| 'BlackTassel'
	| 'AquaSimulacra'
	| 'SkywardBlade'
	| 'OathswornEye'
	| 'FavoniusWarbow'
	| 'FleuveCendreFerryman'
	| 'SacrificialFragments'
	| 'DragonsBane'
	| 'FavoniusSword'
	| 'CalamityQueller';

const weaponImageDict: Record<WeaponCacheKey, Record<WeaponImageKey, Picture>> = {
	StaffOfHoma: {
		baseIocn: SIBuwMtPbDfc,
		awakenIcon: XfnpRutGWVmJ,
		splashImage: JByFNyhaPyVb
	},
	BlackTassel: {
		baseIocn: QbnxSwXsqHlm,
		awakenIcon: tXbIgfeWVDWJ,
		splashImage: pjLclRFHVOKN
	},
	AquaSimulacra: {
		baseIocn: bWzXRKuHDPDY,
		awakenIcon: MdIcZbjMpSPL,
		splashImage: csuOIoqHdQMl
	},
	SkywardBlade: {
		baseIocn: yVbeJmbYAUBG,
		awakenIcon: DRNiOdnoTXLl,
		splashImage: YfiYfpZbubbq
	},
	OathswornEye: {
		baseIocn: UAvrSnJNDDfK,
		awakenIcon: uAxOUIwYKIqx,
		splashImage: bqzzrhhYskrx
	},
	FavoniusWarbow: {
		baseIocn: OfmcAJSFXZOI,
		awakenIcon: amuLIQmQkiZJ,
		splashImage: xeWuJqsGuXND
	},
	FleuveCendreFerryman: {
		baseIocn: pHzQoTsCFdVm,
		awakenIcon: LTJhgITSqBQY,
		splashImage: GShNNbacgzlG
	},
	SacrificialFragments: {
		baseIocn: hkiyFbGOIazx,
		awakenIcon: igcEezFElToO,
		splashImage: nClbSqKgVEHG
	},
	DragonsBane: {
		baseIocn: YkrcHohBonpG,
		awakenIcon: NVIECvbToIho,
		splashImage: JWdigXeSaIxS
	},
	FavoniusSword: {
		baseIocn: XpAAPjrnvLqC,
		awakenIcon: VlXksFyNbxLC,
		splashImage: RAEppvaFxbQB
	},
	CalamityQueller: {
		baseIocn: izjnnJlCYkow,
		awakenIcon: xjkwAgcffklh,
		splashImage: tConBiujVrMA
	}
};
const getWeaponImage = (weapon: WeaponCacheKey, image: WeaponImageKey) => {
	return weaponImageDict[weapon][image];
};

export { getWeaponImage };
export type { WeaponCacheKey };

import NRVqSIlxbJvy from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_1.png?enhanced&format=webp';
import GMSyEBmsjKUF from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_2.png?enhanced&format=webp';
import pyKflARworXs from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_3.png?enhanced&format=webp';
import MXjjSdrAjnbF from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_4.png?enhanced&format=webp';
import qsNJhnTdpvcS from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_5.png?enhanced&format=webp';
import RIlTNqOEFvuN from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_1.png?enhanced&format=webp';
import ToCxbMJbRulY from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_2.png?enhanced&format=webp';
import MReIayhFLHyi from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_3.png?enhanced&format=webp';
import NgLKnHjBklES from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_4.png?enhanced&format=webp';
import UrPXUcPBMEtb from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_5.png?enhanced&format=webp';
import rwJiykHSLTbm from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_1.png?enhanced&format=webp';
import KwTOTglBGAVm from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_2.png?enhanced&format=webp';
import KtZCYxVBiCxp from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_3.png?enhanced&format=webp';
import jISrgiOGCRqm from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_4.png?enhanced&format=webp';
import wBKeagzfETiW from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_5.png?enhanced&format=webp';
import SeTbLyILZCFl from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_1.png?enhanced&format=webp';
import krQooRRPLuUZ from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_2.png?enhanced&format=webp';
import uZytKGwsEFYG from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_3.png?enhanced&format=webp';
import OloLTTeWgJGk from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_4.png?enhanced&format=webp';
import xBoLAcQkeOHb from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_5.png?enhanced&format=webp';
import FCbAEaNwEOVv from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_1.png?enhanced&format=webp';
import LkAsUPRCBEQz from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_2.png?enhanced&format=webp';
import qnKSPBFKgmCg from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_3.png?enhanced&format=webp';
import BvmhUVqfrzlA from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_4.png?enhanced&format=webp';
import yBHaEAprbvhh from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_5.png?enhanced&format=webp';
import VKGikUcREBbV from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_1.png?enhanced&format=webp';
import AdxTbVeqkpkj from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_2.png?enhanced&format=webp';
import zgBgZqMqwJZH from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_3.png?enhanced&format=webp';
import gXrgkAANztXf from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_4.png?enhanced&format=webp';
import eGSlGLHCHXVe from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_5.png?enhanced&format=webp';
import JsDlMRGXWhmG from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_1.png?enhanced&format=webp';
import WhoCfkWMUdkz from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_2.png?enhanced&format=webp';
import iGAzYvDXfEGT from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_3.png?enhanced&format=webp';
import sKYwzudgBvzK from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_4.png?enhanced&format=webp';
import eLzfOUpbyihm from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_5.png?enhanced&format=webp';
import dCCQuzXfDVMS from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_1.png?enhanced&format=webp';
import UgxNBvdxPCtW from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_2.png?enhanced&format=webp';
import fhMBUfgLGRHj from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_3.png?enhanced&format=webp';
import PJBjEfekNRWH from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_4.png?enhanced&format=webp';
import FPyHUEeFIEwk from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_5.png?enhanced&format=webp';
import jFHhdMvwnKXy from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_1.png?enhanced&format=webp';
import YrNSTgniuJsH from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_2.png?enhanced&format=webp';
import kGdsRuLVTyxH from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_3.png?enhanced&format=webp';
import LnKSaWKdWREl from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_4.png?enhanced&format=webp';
import KbUemcUQMOqQ from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_5.png?enhanced&format=webp';
import RRAAGbylGCih from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_1.png?enhanced&format=webp';
import MKNYWzsuOCWQ from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_2.png?enhanced&format=webp';
import ONgNugrgGLYA from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_3.png?enhanced&format=webp';
import BBcLaMxiafaI from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_4.png?enhanced&format=webp';
import RbuXaFiWyUwu from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_5.png?enhanced&format=webp';
import SWjEwcOXKtfm from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_1.png?enhanced&format=webp';
import zuquYTGnTRhS from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_2.png?enhanced&format=webp';
import dXqeYcnENalI from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_3.png?enhanced&format=webp';
import pEhOudDmEPNY from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_4.png?enhanced&format=webp';
import eedkXbEgWUQN from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_5.png?enhanced&format=webp';
import LHxSYwxpgmAq from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_1.png?enhanced&format=webp';
import wePQldEMXxiv from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_2.png?enhanced&format=webp';
import sIMHZAqfPLmR from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_3.png?enhanced&format=webp';
import zURsbgqhduBX from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_4.png?enhanced&format=webp';
import ioSPJwTSNMaS from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_5.png?enhanced&format=webp';
import IsPRZFviJIlU from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_1.png?enhanced&format=webp';
import cURMhOKNMwAm from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_2.png?enhanced&format=webp';
import LNtzBNMmYgzG from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_3.png?enhanced&format=webp';
import fSUngLFDKphK from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_4.png?enhanced&format=webp';
import uxMhzGpNIfrd from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_5.png?enhanced&format=webp';
import tXfVegdNQSiu from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_1.png?enhanced&format=webp';
import ezDqIreCGkhP from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_2.png?enhanced&format=webp';
import DujnlMqzgENf from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_3.png?enhanced&format=webp';
import ZriUpRgdNkuF from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_4.png?enhanced&format=webp';
import WmscqzkvlNhu from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_5.png?enhanced&format=webp';
import type { Element } from './genshin_agg';

type ArtifactImageKey = 'goblet' | 'plume' | 'circlet' | 'flower' | 'sands';

type ArtifactCacheKey =
	| 'FragmentOfHarmonicWhimsy'
	| 'GladiatorsFinale'
	| 'TenacityOfTheMillelith'
	| 'EmblemOfSeveredFate'
	| 'ThunderingFury'
	| 'ViridescentVenerer'
	| 'MarechausseeHunter'
	| 'UnfinishedReverie'
	| 'ShimenawasReminiscence'
	| 'GoldenTroupe'
	| 'CrimsonWitchOfFlames'
	| 'DeepwoodMemories'
	| 'GildedDreams'
	| 'MaidenBeloved';

const artifactImageDict: Record<ArtifactCacheKey, Record<ArtifactImageKey, Picture>> = {
	FragmentOfHarmonicWhimsy: {
		goblet: NRVqSIlxbJvy,
		plume: GMSyEBmsjKUF,
		circlet: pyKflARworXs,
		flower: MXjjSdrAjnbF,
		sands: qsNJhnTdpvcS
	},
	GladiatorsFinale: {
		goblet: RIlTNqOEFvuN,
		plume: ToCxbMJbRulY,
		circlet: MReIayhFLHyi,
		flower: NgLKnHjBklES,
		sands: UrPXUcPBMEtb
	},
	TenacityOfTheMillelith: {
		goblet: rwJiykHSLTbm,
		plume: KwTOTglBGAVm,
		circlet: KtZCYxVBiCxp,
		flower: jISrgiOGCRqm,
		sands: wBKeagzfETiW
	},
	EmblemOfSeveredFate: {
		goblet: SeTbLyILZCFl,
		plume: krQooRRPLuUZ,
		circlet: uZytKGwsEFYG,
		flower: OloLTTeWgJGk,
		sands: xBoLAcQkeOHb
	},
	ThunderingFury: {
		goblet: FCbAEaNwEOVv,
		plume: LkAsUPRCBEQz,
		circlet: qnKSPBFKgmCg,
		flower: BvmhUVqfrzlA,
		sands: yBHaEAprbvhh
	},
	ViridescentVenerer: {
		goblet: VKGikUcREBbV,
		plume: AdxTbVeqkpkj,
		circlet: zgBgZqMqwJZH,
		flower: gXrgkAANztXf,
		sands: eGSlGLHCHXVe
	},
	MarechausseeHunter: {
		goblet: JsDlMRGXWhmG,
		plume: WhoCfkWMUdkz,
		circlet: iGAzYvDXfEGT,
		flower: sKYwzudgBvzK,
		sands: eLzfOUpbyihm
	},
	UnfinishedReverie: {
		goblet: dCCQuzXfDVMS,
		plume: UgxNBvdxPCtW,
		circlet: fhMBUfgLGRHj,
		flower: PJBjEfekNRWH,
		sands: FPyHUEeFIEwk
	},
	ShimenawasReminiscence: {
		goblet: jFHhdMvwnKXy,
		plume: YrNSTgniuJsH,
		circlet: kGdsRuLVTyxH,
		flower: LnKSaWKdWREl,
		sands: KbUemcUQMOqQ
	},
	GoldenTroupe: {
		goblet: RRAAGbylGCih,
		plume: MKNYWzsuOCWQ,
		circlet: ONgNugrgGLYA,
		flower: BBcLaMxiafaI,
		sands: RbuXaFiWyUwu
	},
	CrimsonWitchOfFlames: {
		goblet: SWjEwcOXKtfm,
		plume: zuquYTGnTRhS,
		circlet: dXqeYcnENalI,
		flower: pEhOudDmEPNY,
		sands: eedkXbEgWUQN
	},
	DeepwoodMemories: {
		goblet: LHxSYwxpgmAq,
		plume: wePQldEMXxiv,
		circlet: sIMHZAqfPLmR,
		flower: zURsbgqhduBX,
		sands: ioSPJwTSNMaS
	},
	GildedDreams: {
		goblet: IsPRZFviJIlU,
		plume: cURMhOKNMwAm,
		circlet: LNtzBNMmYgzG,
		flower: fSUngLFDKphK,
		sands: uxMhzGpNIfrd
	},
	MaidenBeloved: {
		goblet: tXfVegdNQSiu,
		plume: ezDqIreCGkhP,
		circlet: DujnlMqzgENf,
		flower: ZriUpRgdNkuF,
		sands: WmscqzkvlNhu
	}
};
const getArtifactImage = (weapon: ArtifactCacheKey, image: ArtifactImageKey) => {
	return artifactImageDict[weapon][image];
};

export { getArtifactImage };
export type { ArtifactCacheKey };
