/**
 * NOTE: This file is auto-generated by scripts/prefetch_steam.ts
 * DO NOT modify manually
 */
import type { Picture } from 'vite-imagetools';
import kVbUhCHSxPgg from '../assets/genshin/characters/Arlecchino/UI_AvatarIcon_Side.png?enhanced&format=webp';
import XBqfvsguGJAD from '../assets/genshin/characters/Arlecchino/UI_Talent_S_01.png?enhanced&format=webp';
import lNtwZetXJqzB from '../assets/genshin/characters/Arlecchino/UI_Talent_S_02.png?enhanced&format=webp';
import aybjEmLxwfJJ from '../assets/genshin/characters/Arlecchino/UI_Talent_U_01.png?enhanced&format=webp';
import YrdJAUenBpsK from '../assets/genshin/characters/Arlecchino/UI_Talent_S_03.png?enhanced&format=webp';
import wSDJCoIrwhDQ from '../assets/genshin/characters/Arlecchino/UI_Talent_U_02.png?enhanced&format=webp';
import jKypIxjPagxb from '../assets/genshin/characters/Arlecchino/UI_Talent_S_04.png?enhanced&format=webp';
import MNQsRStLUUOp from '../assets/genshin/characters/Arlecchino/Skill_E_01.png?enhanced&format=webp';
import nyXDspjqiXJR from '../assets/genshin/characters/Arlecchino/Skill_S_01.png?enhanced&format=webp';
import YFJQvzMBeDEH from '../assets/genshin/characters/Arlecchino/UI_AvatarIcon.png?enhanced&format=webp';
import azwNxFLDmRXm from '../assets/genshin/characters/Arlecchino/Skill_A_03.png?enhanced&format=webp';
import GrvYtKMTBAUu from '../assets/genshin/characters/Arlecchino/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import ZgBlurqrTRBi from '../assets/genshin/characters/Arlecchino/UI_Talent_S_05.png?enhanced&format=webp';
import hZUUQLfNNWEY from '../assets/genshin/characters/Arlecchino/UI_Talent_S_06.png?enhanced&format=webp';
import rAVfWFDWILsm from '../assets/genshin/characters/Arlecchino/UI_Talent_S_07.png?enhanced&format=webp';
import VPKoqGyKbXyd from '../assets/genshin/characters/Zhongli/UI_AvatarIcon_Side.png?enhanced&format=webp';
import PkleNQSAWoCJ from '../assets/genshin/characters/Zhongli/UI_Talent_S_01.png?enhanced&format=webp';
import uYDUwtUGeRuJ from '../assets/genshin/characters/Zhongli/UI_Talent_S_02.png?enhanced&format=webp';
import lvyiJAEWpvit from '../assets/genshin/characters/Zhongli/UI_Talent_U_01.png?enhanced&format=webp';
import OkuZwnvsfZNR from '../assets/genshin/characters/Zhongli/UI_Talent_S_03.png?enhanced&format=webp';
import lyekYrYeKPLJ from '../assets/genshin/characters/Zhongli/UI_Talent_U_02.png?enhanced&format=webp';
import DEppRgmLaxNT from '../assets/genshin/characters/Zhongli/UI_Talent_S_04.png?enhanced&format=webp';
import EjoVpnhVIFXZ from '../assets/genshin/characters/Zhongli/Skill_E_01.png?enhanced&format=webp';
import jeOxcAGvWGiI from '../assets/genshin/characters/Zhongli/Skill_S_01.png?enhanced&format=webp';
import UiiCWOInErFj from '../assets/genshin/characters/Zhongli/UI_AvatarIcon.png?enhanced&format=webp';
import WxFMrmRiHGDg from '../assets/genshin/characters/Zhongli/Skill_A_03.png?enhanced&format=webp';
import CLxzeObTDszJ from '../assets/genshin/characters/Zhongli/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import tmKEuRgrDSUp from '../assets/genshin/characters/Zhongli/UI_Talent_S_05.png?enhanced&format=webp';
import BlvKNxgRspNI from '../assets/genshin/characters/Zhongli/UI_Talent_S_06.png?enhanced&format=webp';
import KoStHujvFZML from '../assets/genshin/characters/Zhongli/UI_Talent_Forge_Pole.png?enhanced&format=webp';
import WIjnXLcNSJMU from '../assets/genshin/characters/Yelan/UI_AvatarIcon_Side.png?enhanced&format=webp';
import GEfPgZQPVdqj from '../assets/genshin/characters/Yelan/UI_Talent_S_01.png?enhanced&format=webp';
import FOXmhggijJSl from '../assets/genshin/characters/Yelan/UI_Talent_S_02.png?enhanced&format=webp';
import gFlOYAsKOySY from '../assets/genshin/characters/Yelan/UI_Talent_U_01.png?enhanced&format=webp';
import lVmrIJlTTyPF from '../assets/genshin/characters/Yelan/UI_Talent_S_03.png?enhanced&format=webp';
import lxLUkeRyrxsz from '../assets/genshin/characters/Yelan/UI_Talent_U_02.png?enhanced&format=webp';
import nUEgWbRThele from '../assets/genshin/characters/Yelan/UI_Talent_S_04.png?enhanced&format=webp';
import PPwfmMPautyz from '../assets/genshin/characters/Yelan/Skill_E_01.png?enhanced&format=webp';
import eJTULYddxqkM from '../assets/genshin/characters/Yelan/Skill_S_01.png?enhanced&format=webp';
import WsyKdaOfOCBF from '../assets/genshin/characters/Yelan/UI_AvatarIcon.png?enhanced&format=webp';
import iIaGsZquvcQx from '../assets/genshin/characters/Yelan/Skill_A_02.png?enhanced&format=webp';
import sgoGcCQRyjyD from '../assets/genshin/characters/Yelan/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import FzIyGepPBgGV from '../assets/genshin/characters/Yelan/UI_Talent_S_05.png?enhanced&format=webp';
import yzDNFXZxxMMl from '../assets/genshin/characters/Yelan/UI_Talent_S_06.png?enhanced&format=webp';
import oBBSkkwUQLxn from '../assets/genshin/characters/Yelan/UI_Talent_Expedition_Liyue.png?enhanced&format=webp';
import GSNkSzhKvqaV from '../assets/genshin/characters/Xingqiu/UI_AvatarIcon_Side.png?enhanced&format=webp';
import vIQtvRBHSzkp from '../assets/genshin/characters/Xingqiu/UI_Talent_S_01.png?enhanced&format=webp';
import zVMLyMrmGvWc from '../assets/genshin/characters/Xingqiu/UI_Talent_S_02.png?enhanced&format=webp';
import ULAfCTTKaymk from '../assets/genshin/characters/Xingqiu/UI_Talent_U_01.png?enhanced&format=webp';
import IFIXTgDtLKCt from '../assets/genshin/characters/Xingqiu/UI_Talent_S_03.png?enhanced&format=webp';
import PQEldfxZgsIJ from '../assets/genshin/characters/Xingqiu/UI_Talent_U_02.png?enhanced&format=webp';
import AFmVIazeOBRE from '../assets/genshin/characters/Xingqiu/UI_Talent_S_04.png?enhanced&format=webp';
import XepVZMepYeEn from '../assets/genshin/characters/Xingqiu/Skill_E_01.png?enhanced&format=webp';
import eYSwDMJwUITX from '../assets/genshin/characters/Xingqiu/Skill_S_01.png?enhanced&format=webp';
import ludKHEUCVYjJ from '../assets/genshin/characters/Xingqiu/UI_AvatarIcon.png?enhanced&format=webp';
import rPpbzfGAgyDf from '../assets/genshin/characters/Xingqiu/Skill_A_01.png?enhanced&format=webp';
import IDnVbKoMlrio from '../assets/genshin/characters/Xingqiu/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import FnbAWsVxhXFz from '../assets/genshin/characters/Xingqiu/UI_Talent_S_05.png?enhanced&format=webp';
import cinyZXRcbOFl from '../assets/genshin/characters/Xingqiu/UI_Talent_S_06.png?enhanced&format=webp';
import qIHfzUnQrLvZ from '../assets/genshin/characters/Xingqiu/UI_Talent_Combine_Talent.png?enhanced&format=webp';
import zZziQHwSMdrL from '../assets/genshin/characters/Xiao/UI_AvatarIcon_Side.png?enhanced&format=webp';
import xGTwopVZeHbU from '../assets/genshin/characters/Xiao/UI_Talent_S_01.png?enhanced&format=webp';
import haiNGllppGBT from '../assets/genshin/characters/Xiao/UI_Talent_S_02.png?enhanced&format=webp';
import ebasusAkRCTg from '../assets/genshin/characters/Xiao/UI_Talent_U_01.png?enhanced&format=webp';
import LFjcAimCTzOu from '../assets/genshin/characters/Xiao/UI_Talent_S_03.png?enhanced&format=webp';
import pAwOtFVoGYlA from '../assets/genshin/characters/Xiao/UI_Talent_U_02.png?enhanced&format=webp';
import JIAJUvpMDcPM from '../assets/genshin/characters/Xiao/UI_Talent_S_04.png?enhanced&format=webp';
import ZIhsFLDJChEF from '../assets/genshin/characters/Xiao/Skill_E_01.png?enhanced&format=webp';
import nJltJYLfvXra from '../assets/genshin/characters/Xiao/Skill_S_01.png?enhanced&format=webp';
import qYYsQyPpETok from '../assets/genshin/characters/Xiao/UI_AvatarIcon.png?enhanced&format=webp';
import KXiZABBamyJT from '../assets/genshin/characters/Xiao/Skill_A_03.png?enhanced&format=webp';
import xCquWRTDCYOE from '../assets/genshin/characters/Xiao/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import TJJWmYrkWxJF from '../assets/genshin/characters/Xiao/UI_Talent_S_05.png?enhanced&format=webp';
import stCkNbpqnWuk from '../assets/genshin/characters/Xiao/UI_Talent_S_06.png?enhanced&format=webp';
import oRVSnlixImEW from '../assets/genshin/characters/Xiao/UI_Talent_Explosion_Climb.png?enhanced&format=webp';
import FWGcfhhivnOX from '../assets/genshin/characters/Xianyun/UI_AvatarIcon_Side_Liuyun.png?enhanced&format=webp';
import IAvOYxbOambB from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_01.png?enhanced&format=webp';
import azpLXvMTIlzL from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_02.png?enhanced&format=webp';
import inyedzMXPMTn from '../assets/genshin/characters/Xianyun/UI_Talent_U_Liuyun_02.png?enhanced&format=webp';
import MwZsmWSrpKDv from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_03.png?enhanced&format=webp';
import XjQoZoCaMXoN from '../assets/genshin/characters/Xianyun/UI_Talent_U_Liuyun_01.png?enhanced&format=webp';
import uBCmMDbstDqc from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_04.png?enhanced&format=webp';
import WRisFDwBmOIi from '../assets/genshin/characters/Xianyun/Skill_E_Liuyun_01.png?enhanced&format=webp';
import bhWZSKSWVOJA from '../assets/genshin/characters/Xianyun/Skill_S_Liuyun_01.png?enhanced&format=webp';
import WNpPaxxTguFY from '../assets/genshin/characters/Xianyun/UI_AvatarIcon_Liuyun.png?enhanced&format=webp';
import TcLdazFkqEBP from '../assets/genshin/characters/Xianyun/Skill_A_Catalyst_MD.png?enhanced&format=webp';
import dfMAnZvSMsKY from '../assets/genshin/characters/Xianyun/UI_Gacha_AvatarImg_Liuyun.png?enhanced&format=webp';
import VfXdGvCRdhFJ from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_05.png?enhanced&format=webp';
import WUYaabVfxQlu from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_06.png?enhanced&format=webp';
import lxAfmpKoYZWF from '../assets/genshin/characters/Xianyun/UI_Talent_S_Liuyun_07.png?enhanced&format=webp';
import oDOKmpDcHXIo from '../assets/genshin/characters/Faruzan/UI_AvatarIcon_Side.png?enhanced&format=webp';
import gTESeYfYDejw from '../assets/genshin/characters/Faruzan/UI_Talent_S_01.png?enhanced&format=webp';
import wDiQmaLCLeVB from '../assets/genshin/characters/Faruzan/UI_Talent_S_02.png?enhanced&format=webp';
import NImtqilJflno from '../assets/genshin/characters/Faruzan/UI_Talent_U_01.png?enhanced&format=webp';
import BNkUzVtdbesX from '../assets/genshin/characters/Faruzan/UI_Talent_S_03.png?enhanced&format=webp';
import yztRiJiwzrhx from '../assets/genshin/characters/Faruzan/UI_Talent_U_02.png?enhanced&format=webp';
import kwJOBmRslapZ from '../assets/genshin/characters/Faruzan/UI_Talent_S_04.png?enhanced&format=webp';
import jdqLaRwuEtuH from '../assets/genshin/characters/Faruzan/Skill_E_01.png?enhanced&format=webp';
import XOFJAVZqfChV from '../assets/genshin/characters/Faruzan/Skill_S_01.png?enhanced&format=webp';
import CMyBIRROFFQP from '../assets/genshin/characters/Faruzan/UI_AvatarIcon.png?enhanced&format=webp';
import wbjvOTQEwNvB from '../assets/genshin/characters/Faruzan/Skill_A_02.png?enhanced&format=webp';
import HCOinSgrogJh from '../assets/genshin/characters/Faruzan/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import sQxcqkgVBuAi from '../assets/genshin/characters/Faruzan/UI_Talent_S_05.png?enhanced&format=webp';
import aZLmckSCDxHX from '../assets/genshin/characters/Faruzan/UI_Talent_S_06.png?enhanced&format=webp';
import cEvuOuNSkKtJ from '../assets/genshin/characters/Faruzan/UI_Talent_S_Cyno_07.png?enhanced&format=webp';
import DuGNRWGZwWTA from '../assets/genshin/characters/Furina/UI_AvatarIcon_Side.png?enhanced&format=webp';
import DqsxINpCCEbB from '../assets/genshin/characters/Furina/UI_Talent_S_01.png?enhanced&format=webp';
import VSjDJikSUWHE from '../assets/genshin/characters/Furina/UI_Talent_S_04.png?enhanced&format=webp';
import aLaBLNUktkNR from '../assets/genshin/characters/Furina/UI_Talent_U_02.png?enhanced&format=webp';
import sUbgTZBYsrVg from '../assets/genshin/characters/Furina/UI_Talent_S_03.png?enhanced&format=webp';
import ufQTOFeXztuB from '../assets/genshin/characters/Furina/UI_Talent_U_01.png?enhanced&format=webp';
import wBYlWgdBBLTh from '../assets/genshin/characters/Furina/UI_Talent_S_02.png?enhanced&format=webp';
import prncVEsLIeOq from '../assets/genshin/characters/Furina/Skill_E_01.png?enhanced&format=webp';
import AyBayEiWbImf from '../assets/genshin/characters/Furina/Skill_S_01.png?enhanced&format=webp';
import HeYFfEjlVEZd from '../assets/genshin/characters/Furina/UI_AvatarIcon.png?enhanced&format=webp';
import ejPTtyQGsTkN from '../assets/genshin/characters/Furina/Skill_A_01.png?enhanced&format=webp';
import caRhcQMJwjVd from '../assets/genshin/characters/Furina/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import RciCtBKVwHGE from '../assets/genshin/characters/Furina/UI_Talent_S_05.png?enhanced&format=webp';
import AwPAjQpAsgQZ from '../assets/genshin/characters/Furina/UI_Talent_S_06.png?enhanced&format=webp';
import HaiFEAjtBMOv from '../assets/genshin/characters/Furina/UI_Talent_S_07.png?enhanced&format=webp';
import jrCnzDtAEuQy from '../assets/genshin/characters/Nahida/UI_AvatarIcon_Side.png?enhanced&format=webp';
import yBmJGADXWyBV from '../assets/genshin/characters/Nahida/UI_Talent_S_01.png?enhanced&format=webp';
import swVHKDYldmvv from '../assets/genshin/characters/Nahida/UI_Talent_S_02.png?enhanced&format=webp';
import jaJDJHeUNtYJ from '../assets/genshin/characters/Nahida/UI_Talent_U_01.png?enhanced&format=webp';
import hkxbsTgsIJnZ from '../assets/genshin/characters/Nahida/UI_Talent_S_03.png?enhanced&format=webp';
import OTdzSsphKTEe from '../assets/genshin/characters/Nahida/UI_Talent_U_02.png?enhanced&format=webp';
import PhIlKRtyGXaL from '../assets/genshin/characters/Nahida/UI_Talent_S_04.png?enhanced&format=webp';
import PqipzTWiZFFw from '../assets/genshin/characters/Nahida/Skill_E_01.png?enhanced&format=webp';
import vezvwYIHYYgM from '../assets/genshin/characters/Nahida/Skill_S_01.png?enhanced&format=webp';
import zIXBPzcJAcOH from '../assets/genshin/characters/Nahida/UI_AvatarIcon.png?enhanced&format=webp';
import HUaBItGHGJVZ from '../assets/genshin/characters/Nahida/Skill_A_Catalyst_MD.png?enhanced&format=webp';
import sFFVhfuiBVLI from '../assets/genshin/characters/Nahida/UI_Gacha_AvatarImg.png?enhanced&format=webp';
import KPmuvPYRFpJD from '../assets/genshin/characters/Nahida/UI_Talent_S_05.png?enhanced&format=webp';
import tFFnauOPnSHU from '../assets/genshin/characters/Nahida/UI_Talent_S_06.png?enhanced&format=webp';
import xCGqQOovmNjp from '../assets/genshin/characters/Nahida/UI_Talent_S_07.png?enhanced&format=webp';
import odYuoKOzWosq from '../assets/genshin/characters/RaidenShogun/UI_AvatarIcon_Side_Shougun.png?enhanced&format=webp';
import lQJVbsHyqfqu from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_01.png?enhanced&format=webp';
import qoktdBfQcZfq from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_03.png?enhanced&format=webp';
import YTvMnTJKMBWn from '../assets/genshin/characters/RaidenShogun/UI_Talent_U_Shougun_02.png?enhanced&format=webp';
import fgAiYSKcMSfk from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_02.png?enhanced&format=webp';
import zlcMitWUlZyi from '../assets/genshin/characters/RaidenShogun/UI_Talent_U_Shougun_01.png?enhanced&format=webp';
import XbhBmWIUSAUI from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_04.png?enhanced&format=webp';
import AzNjfmtstJwz from '../assets/genshin/characters/RaidenShogun/Skill_E_Shougun_01.png?enhanced&format=webp';
import BiQmzwzwHGuG from '../assets/genshin/characters/RaidenShogun/Skill_S_Shougun_01.png?enhanced&format=webp';
import DqgLKCEriPIk from '../assets/genshin/characters/RaidenShogun/UI_AvatarIcon_Shougun.png?enhanced&format=webp';
import TrEfaoAXQSBz from '../assets/genshin/characters/RaidenShogun/Skill_A_03.png?enhanced&format=webp';
import phIqJEjNlcXU from '../assets/genshin/characters/RaidenShogun/UI_Gacha_AvatarImg_Shougun.png?enhanced&format=webp';
import RrhDLjzdlwDv from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_05.png?enhanced&format=webp';
import MUFBFXJvefaJ from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_06.png?enhanced&format=webp';
import wgNWqJqgUhog from '../assets/genshin/characters/RaidenShogun/UI_Talent_S_Shougun_07.png?enhanced&format=webp';
import XjeQYoBXzyaC from '../assets/genshin/characters/KaedeharaKazuha/UI_AvatarIcon_Side_Kazuha.png?enhanced&format=webp';
import rAfNvEFqJoqW from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_01.png?enhanced&format=webp';
import lVsLTLjGjVQV from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_02.png?enhanced&format=webp';
import tYUQXApyTarJ from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_U_Kazuha_01.png?enhanced&format=webp';
import vhbMARyChTMz from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_03.png?enhanced&format=webp';
import OKzZYHjYxDYT from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_U_Kazuha_02.png?enhanced&format=webp';
import WgiWucvFRaVm from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_04.png?enhanced&format=webp';
import xLBUENIbaOQD from '../assets/genshin/characters/KaedeharaKazuha/Skill_E_Kazuha_01.png?enhanced&format=webp';
import TmDdjgztFlxx from '../assets/genshin/characters/KaedeharaKazuha/Skill_S_Kazuha_01.png?enhanced&format=webp';
import jMMPLohlVYsF from '../assets/genshin/characters/KaedeharaKazuha/UI_AvatarIcon_Kazuha.png?enhanced&format=webp';
import CiiHgTPyZcdn from '../assets/genshin/characters/KaedeharaKazuha/Skill_A_01.png?enhanced&format=webp';
import DnbLCVGmHdeT from '../assets/genshin/characters/KaedeharaKazuha/UI_Gacha_AvatarImg_Kazuha.png?enhanced&format=webp';
import nkxznDKCQRxu from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_05.png?enhanced&format=webp';
import DOiavryEtIRP from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_S_Kazuha_06.png?enhanced&format=webp';
import cbqDkHoSRNQD from '../assets/genshin/characters/KaedeharaKazuha/UI_Talent_Explosion_Sprint.png?enhanced&format=webp';
import KHBaqAEPVJkV from '../assets/genshin/characters/HuTao/UI_AvatarIcon_Side_Hutao.png?enhanced&format=webp';
import DgeTEqrpMtiy from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_03.png?enhanced&format=webp';
import uJaIOlmvqGLw from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_01.png?enhanced&format=webp';
import wlUBeasLjAJI from '../assets/genshin/characters/HuTao/UI_Talent_U_Hutao_01.png?enhanced&format=webp';
import KKMNIJXGRDXf from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_02.png?enhanced&format=webp';
import NzpXrzicEqny from '../assets/genshin/characters/HuTao/UI_Talent_U_Hutao_02.png?enhanced&format=webp';
import TuzrXwJpSFwJ from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_04.png?enhanced&format=webp';
import hhibnrmhSTWz from '../assets/genshin/characters/HuTao/Skill_E_Hutao_01.png?enhanced&format=webp';
import HLNpnPLbTFsy from '../assets/genshin/characters/HuTao/Skill_S_Hutao_01.png?enhanced&format=webp';
import MXBULhhMWVQK from '../assets/genshin/characters/HuTao/UI_AvatarIcon_Hutao.png?enhanced&format=webp';
import jNWzQlQSBPGe from '../assets/genshin/characters/HuTao/Skill_A_03.png?enhanced&format=webp';
import tfCvNBggeKpb from '../assets/genshin/characters/HuTao/UI_Gacha_AvatarImg_Hutao.png?enhanced&format=webp';
import wrGFyPVGWzJG from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_05.png?enhanced&format=webp';
import abCtWOjSySof from '../assets/genshin/characters/HuTao/UI_Talent_S_Hutao_06.png?enhanced&format=webp';
import MrBUSZeyCCPA from '../assets/genshin/characters/HuTao/UI_Talent_Cook_ExtraFailedItem.png?enhanced&format=webp';

type CharacterImageKey =
	| 'sideIcon'
	| 'con_0'
	| 'con_1'
	| 'con_2'
	| 'con_3'
	| 'con_4'
	| 'con_5'
	| 'burst'
	| 'skill'
	| 'characterIcon'
	| 'normal'
	| 'splashImage'
	| 'talent_0'
	| 'talent_1'
	| 'talent_2';

type CharacterKey =
	| 'Arlecchino'
	| 'Zhongli'
	| 'Yelan'
	| 'Xingqiu'
	| 'Xiao'
	| 'Xianyun'
	| 'Faruzan'
	| 'Furina'
	| 'Nahida'
	| 'RaidenShogun'
	| 'KaedeharaKazuha'
	| 'HuTao';

const characterImageDict: Record<CharacterKey, Record<CharacterImageKey, Picture>> = {
	Arlecchino: {
		sideIcon: kVbUhCHSxPgg,
		con_0: XBqfvsguGJAD,
		con_1: lNtwZetXJqzB,
		con_2: aybjEmLxwfJJ,
		con_3: YrdJAUenBpsK,
		con_4: wSDJCoIrwhDQ,
		con_5: jKypIxjPagxb,
		burst: MNQsRStLUUOp,
		skill: nyXDspjqiXJR,
		characterIcon: YFJQvzMBeDEH,
		normal: azwNxFLDmRXm,
		splashImage: GrvYtKMTBAUu,
		talent_0: ZgBlurqrTRBi,
		talent_1: hZUUQLfNNWEY,
		talent_2: rAVfWFDWILsm
	},
	Zhongli: {
		sideIcon: VPKoqGyKbXyd,
		con_0: PkleNQSAWoCJ,
		con_1: uYDUwtUGeRuJ,
		con_2: lvyiJAEWpvit,
		con_3: OkuZwnvsfZNR,
		con_4: lyekYrYeKPLJ,
		con_5: DEppRgmLaxNT,
		burst: EjoVpnhVIFXZ,
		skill: jeOxcAGvWGiI,
		characterIcon: UiiCWOInErFj,
		normal: WxFMrmRiHGDg,
		splashImage: CLxzeObTDszJ,
		talent_0: tmKEuRgrDSUp,
		talent_1: BlvKNxgRspNI,
		talent_2: KoStHujvFZML
	},
	Yelan: {
		sideIcon: WIjnXLcNSJMU,
		con_0: GEfPgZQPVdqj,
		con_1: FOXmhggijJSl,
		con_2: gFlOYAsKOySY,
		con_3: lVmrIJlTTyPF,
		con_4: lxLUkeRyrxsz,
		con_5: nUEgWbRThele,
		burst: PPwfmMPautyz,
		skill: eJTULYddxqkM,
		characterIcon: WsyKdaOfOCBF,
		normal: iIaGsZquvcQx,
		splashImage: sgoGcCQRyjyD,
		talent_0: FzIyGepPBgGV,
		talent_1: yzDNFXZxxMMl,
		talent_2: oBBSkkwUQLxn
	},
	Xingqiu: {
		sideIcon: GSNkSzhKvqaV,
		con_0: vIQtvRBHSzkp,
		con_1: zVMLyMrmGvWc,
		con_2: ULAfCTTKaymk,
		con_3: IFIXTgDtLKCt,
		con_4: PQEldfxZgsIJ,
		con_5: AFmVIazeOBRE,
		burst: XepVZMepYeEn,
		skill: eYSwDMJwUITX,
		characterIcon: ludKHEUCVYjJ,
		normal: rPpbzfGAgyDf,
		splashImage: IDnVbKoMlrio,
		talent_0: FnbAWsVxhXFz,
		talent_1: cinyZXRcbOFl,
		talent_2: qIHfzUnQrLvZ
	},
	Xiao: {
		sideIcon: zZziQHwSMdrL,
		con_0: xGTwopVZeHbU,
		con_1: haiNGllppGBT,
		con_2: ebasusAkRCTg,
		con_3: LFjcAimCTzOu,
		con_4: pAwOtFVoGYlA,
		con_5: JIAJUvpMDcPM,
		burst: ZIhsFLDJChEF,
		skill: nJltJYLfvXra,
		characterIcon: qYYsQyPpETok,
		normal: KXiZABBamyJT,
		splashImage: xCquWRTDCYOE,
		talent_0: TJJWmYrkWxJF,
		talent_1: stCkNbpqnWuk,
		talent_2: oRVSnlixImEW
	},
	Xianyun: {
		sideIcon: FWGcfhhivnOX,
		con_0: IAvOYxbOambB,
		con_1: azpLXvMTIlzL,
		con_2: inyedzMXPMTn,
		con_3: MwZsmWSrpKDv,
		con_4: XjQoZoCaMXoN,
		con_5: uBCmMDbstDqc,
		burst: WRisFDwBmOIi,
		skill: bhWZSKSWVOJA,
		characterIcon: WNpPaxxTguFY,
		normal: TcLdazFkqEBP,
		splashImage: dfMAnZvSMsKY,
		talent_0: VfXdGvCRdhFJ,
		talent_1: WUYaabVfxQlu,
		talent_2: lxAfmpKoYZWF
	},
	Faruzan: {
		sideIcon: oDOKmpDcHXIo,
		con_0: gTESeYfYDejw,
		con_1: wDiQmaLCLeVB,
		con_2: NImtqilJflno,
		con_3: BNkUzVtdbesX,
		con_4: yztRiJiwzrhx,
		con_5: kwJOBmRslapZ,
		burst: jdqLaRwuEtuH,
		skill: XOFJAVZqfChV,
		characterIcon: CMyBIRROFFQP,
		normal: wbjvOTQEwNvB,
		splashImage: HCOinSgrogJh,
		talent_0: sQxcqkgVBuAi,
		talent_1: aZLmckSCDxHX,
		talent_2: cEvuOuNSkKtJ
	},
	Furina: {
		sideIcon: DuGNRWGZwWTA,
		con_0: DqsxINpCCEbB,
		con_1: VSjDJikSUWHE,
		con_2: aLaBLNUktkNR,
		con_3: sUbgTZBYsrVg,
		con_4: ufQTOFeXztuB,
		con_5: wBYlWgdBBLTh,
		burst: prncVEsLIeOq,
		skill: AyBayEiWbImf,
		characterIcon: HeYFfEjlVEZd,
		normal: ejPTtyQGsTkN,
		splashImage: caRhcQMJwjVd,
		talent_0: RciCtBKVwHGE,
		talent_1: AwPAjQpAsgQZ,
		talent_2: HaiFEAjtBMOv
	},
	Nahida: {
		sideIcon: jrCnzDtAEuQy,
		con_0: yBmJGADXWyBV,
		con_1: swVHKDYldmvv,
		con_2: jaJDJHeUNtYJ,
		con_3: hkxbsTgsIJnZ,
		con_4: OTdzSsphKTEe,
		con_5: PhIlKRtyGXaL,
		burst: PqipzTWiZFFw,
		skill: vezvwYIHYYgM,
		characterIcon: zIXBPzcJAcOH,
		normal: HUaBItGHGJVZ,
		splashImage: sFFVhfuiBVLI,
		talent_0: KPmuvPYRFpJD,
		talent_1: tFFnauOPnSHU,
		talent_2: xCGqQOovmNjp
	},
	RaidenShogun: {
		sideIcon: odYuoKOzWosq,
		con_0: lQJVbsHyqfqu,
		con_1: qoktdBfQcZfq,
		con_2: YTvMnTJKMBWn,
		con_3: fgAiYSKcMSfk,
		con_4: zlcMitWUlZyi,
		con_5: XbhBmWIUSAUI,
		burst: AzNjfmtstJwz,
		skill: BiQmzwzwHGuG,
		characterIcon: DqgLKCEriPIk,
		normal: TrEfaoAXQSBz,
		splashImage: phIqJEjNlcXU,
		talent_0: RrhDLjzdlwDv,
		talent_1: MUFBFXJvefaJ,
		talent_2: wgNWqJqgUhog
	},
	KaedeharaKazuha: {
		sideIcon: XjeQYoBXzyaC,
		con_0: rAfNvEFqJoqW,
		con_1: lVsLTLjGjVQV,
		con_2: tYUQXApyTarJ,
		con_3: vhbMARyChTMz,
		con_4: OKzZYHjYxDYT,
		con_5: WgiWucvFRaVm,
		burst: xLBUENIbaOQD,
		skill: TmDdjgztFlxx,
		characterIcon: jMMPLohlVYsF,
		normal: CiiHgTPyZcdn,
		splashImage: DnbLCVGmHdeT,
		talent_0: nkxznDKCQRxu,
		talent_1: DOiavryEtIRP,
		talent_2: cbqDkHoSRNQD
	},
	HuTao: {
		sideIcon: KHBaqAEPVJkV,
		con_0: DgeTEqrpMtiy,
		con_1: uJaIOlmvqGLw,
		con_2: wlUBeasLjAJI,
		con_3: KKMNIJXGRDXf,
		con_4: NzpXrzicEqny,
		con_5: TuzrXwJpSFwJ,
		burst: hhibnrmhSTWz,
		skill: HLNpnPLbTFsy,
		characterIcon: MXBULhhMWVQK,
		normal: jNWzQlQSBPGe,
		splashImage: tfCvNBggeKpb,
		talent_0: wrGFyPVGWzJG,
		talent_1: abCtWOjSySof,
		talent_2: MrBUSZeyCCPA
	}
};
const getCharacterImage = (character: CharacterKey, image: CharacterImageKey) => {
	return characterImageDict[character][image];
};

export { getCharacterImage };

import yYfmPQUXzyrh from '../assets/genshin/weapons/StaffOfHoma/UI_EquipIcon_Pole_Homa.png?enhanced&format=webp';
import GYFJcivlYxYY from '../assets/genshin/weapons/StaffOfHoma/UI_EquipIcon_Pole_Homa_Awaken.png?enhanced&format=webp';
import RHNWrdTQkDbl from '../assets/genshin/weapons/StaffOfHoma/UI_Gacha_EquipIcon_Pole_Homa.png?enhanced&format=webp';
import ZNEHvCwIAzrV from '../assets/genshin/weapons/BlackTassel/UI_EquipIcon_Pole_Noire.png?enhanced&format=webp';
import nlEVfsHcNdLU from '../assets/genshin/weapons/BlackTassel/UI_EquipIcon_Pole_Noire_Awaken.png?enhanced&format=webp';
import aLPFCZTxarYm from '../assets/genshin/weapons/BlackTassel/UI_Gacha_EquipIcon_Pole_Noire.png?enhanced&format=webp';
import bVaSMPZfReCO from '../assets/genshin/weapons/AquaSimulacra/UI_EquipIcon_Bow_Kirin.png?enhanced&format=webp';
import KnydhMkRkylu from '../assets/genshin/weapons/AquaSimulacra/UI_EquipIcon_Bow_Kirin_Awaken.png?enhanced&format=webp';
import VKsnMpqiSgsd from '../assets/genshin/weapons/AquaSimulacra/UI_Gacha_EquipIcon_Bow_Kirin.png?enhanced&format=webp';
import rKAXBKYPNmfr from '../assets/genshin/weapons/SkywardBlade/UI_EquipIcon_Sword_Dvalin.png?enhanced&format=webp';
import LWUJpBmVGHWI from '../assets/genshin/weapons/SkywardBlade/UI_EquipIcon_Sword_Dvalin_Awaken.png?enhanced&format=webp';
import MPcAwzgHwQFj from '../assets/genshin/weapons/SkywardBlade/UI_Gacha_EquipIcon_Sword_Dvalin.png?enhanced&format=webp';
import pOzrBpwczRQZ from '../assets/genshin/weapons/OathswornEye/UI_EquipIcon_Catalyst_Jyanome.png?enhanced&format=webp';
import OhVPWyeGaWhL from '../assets/genshin/weapons/OathswornEye/UI_EquipIcon_Catalyst_Jyanome_Awaken.png?enhanced&format=webp';
import lyqRjOJJXzIB from '../assets/genshin/weapons/OathswornEye/UI_Gacha_EquipIcon_Catalyst_Jyanome.png?enhanced&format=webp';
import oSlSqzOiAIBh from '../assets/genshin/weapons/FavoniusWarbow/UI_EquipIcon_Bow_Zephyrus.png?enhanced&format=webp';
import iGgczOuBUULj from '../assets/genshin/weapons/FavoniusWarbow/UI_EquipIcon_Bow_Zephyrus_Awaken.png?enhanced&format=webp';
import jdfPsDZvpOKR from '../assets/genshin/weapons/FavoniusWarbow/UI_Gacha_EquipIcon_Bow_Zephyrus.png?enhanced&format=webp';
import bbBJhozhHUQc from '../assets/genshin/weapons/FleuveCendreFerryman/UI_EquipIcon_Sword_Machination.png?enhanced&format=webp';
import ItebETzUfohE from '../assets/genshin/weapons/FleuveCendreFerryman/UI_EquipIcon_Sword_Machination_Awaken.png?enhanced&format=webp';
import uZWHbBajYaXF from '../assets/genshin/weapons/FleuveCendreFerryman/UI_Gacha_EquipIcon_Sword_Machination.png?enhanced&format=webp';
import EBGbiHMGkEXh from '../assets/genshin/weapons/SacrificialFragments/UI_EquipIcon_Catalyst_Fossil.png?enhanced&format=webp';
import WxcADeEqrBRX from '../assets/genshin/weapons/SacrificialFragments/UI_EquipIcon_Catalyst_Fossil_Awaken.png?enhanced&format=webp';
import SbjEqObLRNjH from '../assets/genshin/weapons/SacrificialFragments/UI_Gacha_EquipIcon_Catalyst_Fossil.png?enhanced&format=webp';
import DzamBEqIlnnT from '../assets/genshin/weapons/DragonsBane/UI_EquipIcon_Pole_Stardust.png?enhanced&format=webp';
import kZkkDPPlQkGO from '../assets/genshin/weapons/DragonsBane/UI_EquipIcon_Pole_Stardust_Awaken.png?enhanced&format=webp';
import FXaraeFSvSce from '../assets/genshin/weapons/DragonsBane/UI_Gacha_EquipIcon_Pole_Stardust.png?enhanced&format=webp';
import OIuWAMXWnqFL from '../assets/genshin/weapons/FavoniusSword/UI_EquipIcon_Sword_Zephyrus.png?enhanced&format=webp';
import lDfQqYaUdKdF from '../assets/genshin/weapons/FavoniusSword/UI_EquipIcon_Sword_Zephyrus_Awaken.png?enhanced&format=webp';
import qxKWrTCuiyis from '../assets/genshin/weapons/FavoniusSword/UI_Gacha_EquipIcon_Sword_Zephyrus.png?enhanced&format=webp';
import UhIoXaWhCUbN from '../assets/genshin/weapons/CalamityQueller/UI_EquipIcon_Pole_Santika.png?enhanced&format=webp';
import AXsImJkuCHcl from '../assets/genshin/weapons/CalamityQueller/UI_EquipIcon_Pole_Santika_Awaken.png?enhanced&format=webp';
import iowSfjHkoljO from '../assets/genshin/weapons/CalamityQueller/UI_Gacha_EquipIcon_Pole_Santika.png?enhanced&format=webp';

type WeaponImageKey = 'baseIocn' | 'awakenIcon' | 'splashImage';

type WeaponKey =
	| 'StaffOfHoma'
	| 'BlackTassel'
	| 'AquaSimulacra'
	| 'SkywardBlade'
	| 'OathswornEye'
	| 'FavoniusWarbow'
	| 'FleuveCendreFerryman'
	| 'SacrificialFragments'
	| 'DragonsBane'
	| 'FavoniusSword'
	| 'CalamityQueller';

const weaponImageDict: Record<WeaponKey, Record<WeaponImageKey, Picture>> = {
	StaffOfHoma: {
		baseIocn: yYfmPQUXzyrh,
		awakenIcon: GYFJcivlYxYY,
		splashImage: RHNWrdTQkDbl
	},
	BlackTassel: {
		baseIocn: ZNEHvCwIAzrV,
		awakenIcon: nlEVfsHcNdLU,
		splashImage: aLPFCZTxarYm
	},
	AquaSimulacra: {
		baseIocn: bVaSMPZfReCO,
		awakenIcon: KnydhMkRkylu,
		splashImage: VKsnMpqiSgsd
	},
	SkywardBlade: {
		baseIocn: rKAXBKYPNmfr,
		awakenIcon: LWUJpBmVGHWI,
		splashImage: MPcAwzgHwQFj
	},
	OathswornEye: {
		baseIocn: pOzrBpwczRQZ,
		awakenIcon: OhVPWyeGaWhL,
		splashImage: lyqRjOJJXzIB
	},
	FavoniusWarbow: {
		baseIocn: oSlSqzOiAIBh,
		awakenIcon: iGgczOuBUULj,
		splashImage: jdfPsDZvpOKR
	},
	FleuveCendreFerryman: {
		baseIocn: bbBJhozhHUQc,
		awakenIcon: ItebETzUfohE,
		splashImage: uZWHbBajYaXF
	},
	SacrificialFragments: {
		baseIocn: EBGbiHMGkEXh,
		awakenIcon: WxcADeEqrBRX,
		splashImage: SbjEqObLRNjH
	},
	DragonsBane: {
		baseIocn: DzamBEqIlnnT,
		awakenIcon: kZkkDPPlQkGO,
		splashImage: FXaraeFSvSce
	},
	FavoniusSword: {
		baseIocn: OIuWAMXWnqFL,
		awakenIcon: lDfQqYaUdKdF,
		splashImage: qxKWrTCuiyis
	},
	CalamityQueller: {
		baseIocn: UhIoXaWhCUbN,
		awakenIcon: AXsImJkuCHcl,
		splashImage: iowSfjHkoljO
	}
};
const getWeaponImage = (weapon: WeaponKey, image: WeaponImageKey) => {
	return weaponImageDict[weapon][image];
};

export { getWeaponImage };

import XDLZojGMBoEY from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_1.png?enhanced&format=webp';
import sCDWdXvBtIcC from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_2.png?enhanced&format=webp';
import IXhdHeLRYpit from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_3.png?enhanced&format=webp';
import MOKShTDgnwIZ from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_4.png?enhanced&format=webp';
import FzBKGEdrmwCf from '../assets/genshin/artifacts/FragmentOfHarmonicWhimsy/UI_RelicIcon_15035_5.png?enhanced&format=webp';
import IJEKBuSICnoA from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_1.png?enhanced&format=webp';
import TeKObvwdIJMa from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_2.png?enhanced&format=webp';
import KJNYeymAQeyV from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_3.png?enhanced&format=webp';
import IlcDTaLjiDCP from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_4.png?enhanced&format=webp';
import DQceAvynZYio from '../assets/genshin/artifacts/GladiatorsFinale/UI_RelicIcon_15001_5.png?enhanced&format=webp';
import YcQZAaGMtdSK from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_1.png?enhanced&format=webp';
import VbkSBiyzAhOG from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_2.png?enhanced&format=webp';
import sDWkKZuoEEBV from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_3.png?enhanced&format=webp';
import VHKHLPvbLLvf from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_4.png?enhanced&format=webp';
import RCmzJmKGngKt from '../assets/genshin/artifacts/TenacityOfTheMillelith/UI_RelicIcon_15017_5.png?enhanced&format=webp';
import MXqxGZTTXMgi from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_1.png?enhanced&format=webp';
import FDBTVNqUcOaY from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_2.png?enhanced&format=webp';
import AxTrozQTjvoO from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_3.png?enhanced&format=webp';
import wBbdJbaSpAkh from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_4.png?enhanced&format=webp';
import hpEKyEElmBgc from '../assets/genshin/artifacts/EmblemOfSeveredFate/UI_RelicIcon_15020_5.png?enhanced&format=webp';
import WNVabLGYrOyz from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_1.png?enhanced&format=webp';
import JdYysTWvRsuQ from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_2.png?enhanced&format=webp';
import DFlitpeDutVu from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_3.png?enhanced&format=webp';
import jUzTkQOpJisD from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_4.png?enhanced&format=webp';
import VlQOycGOqEIH from '../assets/genshin/artifacts/ThunderingFury/UI_RelicIcon_15005_5.png?enhanced&format=webp';
import dVJcohieTsCB from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_1.png?enhanced&format=webp';
import wCYcBVjnqNbr from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_2.png?enhanced&format=webp';
import PiJIShsKWFgz from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_3.png?enhanced&format=webp';
import DAQnMgqXaaOL from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_4.png?enhanced&format=webp';
import NHigLPekhwBA from '../assets/genshin/artifacts/ViridescentVenerer/UI_RelicIcon_15002_5.png?enhanced&format=webp';
import gPCdHZVVllTv from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_1.png?enhanced&format=webp';
import ukGlwpwiUDsQ from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_2.png?enhanced&format=webp';
import HvnppybgUSpD from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_3.png?enhanced&format=webp';
import DyJBGhcUoYaH from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_4.png?enhanced&format=webp';
import bmAFuDECLDmn from '../assets/genshin/artifacts/MarechausseeHunter/UI_RelicIcon_15031_5.png?enhanced&format=webp';
import ddjpYrxmDxKd from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_1.png?enhanced&format=webp';
import CTuAcqeDMzua from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_2.png?enhanced&format=webp';
import lCnntYHuOFxT from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_3.png?enhanced&format=webp';
import dKRfoWMfXUwH from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_4.png?enhanced&format=webp';
import WMQHXaxgcWsx from '../assets/genshin/artifacts/UnfinishedReverie/UI_RelicIcon_15036_5.png?enhanced&format=webp';
import tObAtPhxZkVl from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_1.png?enhanced&format=webp';
import DSeUQEtBpsfR from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_2.png?enhanced&format=webp';
import rCooRTHXAwMp from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_3.png?enhanced&format=webp';
import JVbdxSZzEkvE from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_4.png?enhanced&format=webp';
import OFaHhjLdxwTA from '../assets/genshin/artifacts/ShimenawasReminiscence/UI_RelicIcon_15019_5.png?enhanced&format=webp';
import iCvoHiEHcFtL from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_1.png?enhanced&format=webp';
import ZDxNuTKcnufH from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_2.png?enhanced&format=webp';
import KjNrNtDIgQsB from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_3.png?enhanced&format=webp';
import kXscYPxVPiYd from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_4.png?enhanced&format=webp';
import RcYmEauEqSAn from '../assets/genshin/artifacts/GoldenTroupe/UI_RelicIcon_15032_5.png?enhanced&format=webp';
import HZpHpVZYCmli from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_1.png?enhanced&format=webp';
import StGWSszJlWMd from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_2.png?enhanced&format=webp';
import AIcYBCEdNtAI from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_3.png?enhanced&format=webp';
import mbftBshzIBbg from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_4.png?enhanced&format=webp';
import AvMbsWvkvHzs from '../assets/genshin/artifacts/CrimsonWitchOfFlames/UI_RelicIcon_15006_5.png?enhanced&format=webp';
import GcyaXeJBRuMS from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_1.png?enhanced&format=webp';
import FOoNbZcsPCvQ from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_2.png?enhanced&format=webp';
import AjRnsqBDPvvS from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_3.png?enhanced&format=webp';
import gfQrjlsJSMSp from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_4.png?enhanced&format=webp';
import PJfymPqdSpWH from '../assets/genshin/artifacts/DeepwoodMemories/UI_RelicIcon_15025_5.png?enhanced&format=webp';
import ghjsretVXJMy from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_1.png?enhanced&format=webp';
import ChFvlTdEYHBC from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_2.png?enhanced&format=webp';
import vmfYIKxGfgmM from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_3.png?enhanced&format=webp';
import etGiKOQLgQIN from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_4.png?enhanced&format=webp';
import UAqzqWPzFvLZ from '../assets/genshin/artifacts/GildedDreams/UI_RelicIcon_15026_5.png?enhanced&format=webp';
import lCydsvdyXccC from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_1.png?enhanced&format=webp';
import TxYDkQqdSDap from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_2.png?enhanced&format=webp';
import SNPjiacLDFRN from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_3.png?enhanced&format=webp';
import GQThzUDUTsEi from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_4.png?enhanced&format=webp';
import ymkXMSAUlAtM from '../assets/genshin/artifacts/MaidenBeloved/UI_RelicIcon_14004_5.png?enhanced&format=webp';

type ArtifactImageKey = 'goblet' | 'plume' | 'circlet' | 'flower' | 'sands';

type Artifact =
	| 'FragmentOfHarmonicWhimsy'
	| 'GladiatorsFinale'
	| 'TenacityOfTheMillelith'
	| 'EmblemOfSeveredFate'
	| 'ThunderingFury'
	| 'ViridescentVenerer'
	| 'MarechausseeHunter'
	| 'UnfinishedReverie'
	| 'ShimenawasReminiscence'
	| 'GoldenTroupe'
	| 'CrimsonWitchOfFlames'
	| 'DeepwoodMemories'
	| 'GildedDreams'
	| 'MaidenBeloved';

const artifactImageDict: Record<Artifact, Record<ArtifactImageKey, Picture>> = {
	FragmentOfHarmonicWhimsy: {
		goblet: XDLZojGMBoEY,
		plume: sCDWdXvBtIcC,
		circlet: IXhdHeLRYpit,
		flower: MOKShTDgnwIZ,
		sands: FzBKGEdrmwCf
	},
	GladiatorsFinale: {
		goblet: IJEKBuSICnoA,
		plume: TeKObvwdIJMa,
		circlet: KJNYeymAQeyV,
		flower: IlcDTaLjiDCP,
		sands: DQceAvynZYio
	},
	TenacityOfTheMillelith: {
		goblet: YcQZAaGMtdSK,
		plume: VbkSBiyzAhOG,
		circlet: sDWkKZuoEEBV,
		flower: VHKHLPvbLLvf,
		sands: RCmzJmKGngKt
	},
	EmblemOfSeveredFate: {
		goblet: MXqxGZTTXMgi,
		plume: FDBTVNqUcOaY,
		circlet: AxTrozQTjvoO,
		flower: wBbdJbaSpAkh,
		sands: hpEKyEElmBgc
	},
	ThunderingFury: {
		goblet: WNVabLGYrOyz,
		plume: JdYysTWvRsuQ,
		circlet: DFlitpeDutVu,
		flower: jUzTkQOpJisD,
		sands: VlQOycGOqEIH
	},
	ViridescentVenerer: {
		goblet: dVJcohieTsCB,
		plume: wCYcBVjnqNbr,
		circlet: PiJIShsKWFgz,
		flower: DAQnMgqXaaOL,
		sands: NHigLPekhwBA
	},
	MarechausseeHunter: {
		goblet: gPCdHZVVllTv,
		plume: ukGlwpwiUDsQ,
		circlet: HvnppybgUSpD,
		flower: DyJBGhcUoYaH,
		sands: bmAFuDECLDmn
	},
	UnfinishedReverie: {
		goblet: ddjpYrxmDxKd,
		plume: CTuAcqeDMzua,
		circlet: lCnntYHuOFxT,
		flower: dKRfoWMfXUwH,
		sands: WMQHXaxgcWsx
	},
	ShimenawasReminiscence: {
		goblet: tObAtPhxZkVl,
		plume: DSeUQEtBpsfR,
		circlet: rCooRTHXAwMp,
		flower: JVbdxSZzEkvE,
		sands: OFaHhjLdxwTA
	},
	GoldenTroupe: {
		goblet: iCvoHiEHcFtL,
		plume: ZDxNuTKcnufH,
		circlet: KjNrNtDIgQsB,
		flower: kXscYPxVPiYd,
		sands: RcYmEauEqSAn
	},
	CrimsonWitchOfFlames: {
		goblet: HZpHpVZYCmli,
		plume: StGWSszJlWMd,
		circlet: AIcYBCEdNtAI,
		flower: mbftBshzIBbg,
		sands: AvMbsWvkvHzs
	},
	DeepwoodMemories: {
		goblet: GcyaXeJBRuMS,
		plume: FOoNbZcsPCvQ,
		circlet: AjRnsqBDPvvS,
		flower: gfQrjlsJSMSp,
		sands: PJfymPqdSpWH
	},
	GildedDreams: {
		goblet: ghjsretVXJMy,
		plume: ChFvlTdEYHBC,
		circlet: vmfYIKxGfgmM,
		flower: etGiKOQLgQIN,
		sands: UAqzqWPzFvLZ
	},
	MaidenBeloved: {
		goblet: lCydsvdyXccC,
		plume: TxYDkQqdSDap,
		circlet: SNPjiacLDFRN,
		flower: GQThzUDUTsEi,
		sands: ymkXMSAUlAtM
	}
};
const getArtifactImage = (weapon: Artifact, image: ArtifactImageKey) => {
	return artifactImageDict[weapon][image];
};

export { getArtifactImage };
