/**
 * NOTE: This file is auto-generated by scripts/optimize_screenshots.ts
 * DO NOT modify manually
 */

import type { Picture } from 'vite-imagetools';
type ScreenshotGetter = () => Promise<Picture>;
type Screenshot = {
    thumbnail: ScreenshotGetter;
    full: ScreenshotGetter;
    aspectRatio: number;
};
export type ScreenshotImageDictKey = 'acs' | 'genshin' | 'hfw';
export const screenshotImageDict: Record<ScreenshotImageDictKey, Screenshot[]> = {
	acs: [
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_03_31_20_03_35.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_03_31_20_03_35.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_03_31_19_40_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_03_31_19_40_12.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_05_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_05_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_09_55_07.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_09_55_07.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_10_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_10_14.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_01_58.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_01_58.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_02_25.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_02_25.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_09_27.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_09_27.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_32_10.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_32_10.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_20_31.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_20_31.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_49_26.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_49_26.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_21_53.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_21_53.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_34_57.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_34_57.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_29_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_29_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_13_51_28.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_13_51_28.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_01_06.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_01_06.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_03_28.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_03_28.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_29_08.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_29_08.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_30_38.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_30_38.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_15_57_58.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_15_57_58.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_34_06.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_34_06.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_49_19.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_49_19.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_48_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_48_12.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_35_23.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_35_23.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_57_22.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_57_22.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_07_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_07_12.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_11_16_31_53.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_11_16_31_53.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_12_05.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_12_05.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_17_19.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_17_19.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_33_52.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_33_52.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_18_55.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_18_55.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_35_00.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_35_00.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_36_50.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_36_50.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_13_18_19_45.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_13_18_19_45.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_13_18_23_03.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_13_18_23_03.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_13_18_32_04.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_13_18_32_04.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_12_19_22_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_12_19_22_14.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_13_18_36_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_13_18_36_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_14_18_56_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_14_18_56_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_14_19_46_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_14_19_46_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_14_19_34_10.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_14_19_34_10.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_15_19_07_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_15_19_07_14.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_15_20_04_07.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_15_20_04_07.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_15_19_16_02.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_15_19_16_02.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_15_19_09_18.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_15_19_09_18.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_21_17_24_57.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_21_17_24_57.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_12_46_43.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_12_46_43.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_21_16_40_23.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_21_16_40_23.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_03_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_03_12.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_04_35.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_04_35.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_12_55_44.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_12_55_44.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_06_26.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_06_26.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_07_18.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_07_18.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_09_04.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_09_04.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_10_08.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_10_08.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_11_24.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_11_24.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_15_10.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_15_10.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_17_11.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_17_11.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_05_34.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_05_34.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_20_26.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_20_26.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_3_20_28_15.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_3_20_28_15.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_09_59_50.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_09_59_50.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_01_54.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_01_54.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_21_59.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_21_59.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_27_28.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_27_28.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_22_13_21_17.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_22_13_21_17.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_17_59_57.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_17_59_57.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_05_43.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_05_43.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_25_05.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_25_05.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_09_39.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_09_39.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_18_50.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_18_50.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_08_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_08_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_21_01.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_21_01.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_20_55_31.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_20_55_31.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_6_20_57_23.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_6_20_57_23.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_3_20_25_48.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_3_20_25_48.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_6_21_02_13.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_6_21_02_13.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_6_20_58_09.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_6_20_58_09.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_6_21_03_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_6_21_03_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_15_14_46_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_15_14_46_14.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_15_14_55_22.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_15_14_55_22.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_5_18_23_29.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_5_18_23_29.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_15_15_51_20.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_15_15_51_20.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_15_14_47_57.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_15_14_47_57.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_8_18_50_52.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_8_18_50_52.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_12_07_40_19.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_12_07_40_19.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_06_8_18_54_52.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_06_8_18_54_52.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_07_7_17_42_55.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_07_7_17_42_55.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_10_20_02_23_2025_06_10_20_02_36-6 images.jpg?enhanced&w=920;540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_10_20_02_23_2025_06_10_20_02_36-6 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 4.8063
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_15_16_41_02_2025_06_15_16_42_02-20 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_15_16_41_02_2025_06_15_16_42_02-20 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 3.4928
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_7_19_08_43_2025_06_7_19_08_54-5 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_7_19_08_43_2025_06_7_19_08_54-5 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.4292
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_12_07_32_17_2025_06_12_07_32_30-4 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_12_07_32_17_2025_06_12_07_32_30-4 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 3.8755
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_7_19_23_36_2025_06_7_19_24_14-15 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_7_19_23_36_2025_06_7_19_24_14-15 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 3.1173
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_15_15_58_50_2025_06_15_15_58_59-5 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/[Group 0]-2025_06_15_15_58_50_2025_06_15_15_58_59-5 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 3.0667
        }
    ],
	genshin: [
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250331174034.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250331174034.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250404201855.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250404201855.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250331173924.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250331173924.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250402194916.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250402194916.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412085023.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412085023.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250404202717.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250404202717.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412104814.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412104814.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412204538.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412204538.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412205345.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412205345.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412100914.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412100914.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412205940.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412205940.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250508175631.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250508175631.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250621091022.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250621091022.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250629120455.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250629120455.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250510103425.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250510103425.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 4_12_2025 11_51_15 AM.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 4_12_2025 11_51_15 AM.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250720145723 - 20250720150107.jpg?enhanced&w=920;540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250720145723 - 20250720150107.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 4.8915
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 19_13_59.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 19_13_59.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 21_31_24.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 21_31_24.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 21_41_12.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_19_2025 21_41_12.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 4_12_2025 11_29_15 AM.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 4_12_2025 11_29_15 AM.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_29_2025 12_59_30.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_29_2025 12_59_30.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_29_2025 13_07_05.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_29_2025 13_07_05.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620170047_20250620170146-13 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620170047_20250620170146-13 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 3.0946
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620171844_20250620172145-20 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620171844_20250620172145-20 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.2468
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250621090333_20250621090421-11 images_0001.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250621090333_20250621090421-11 images_0001.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.0190
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250719200012_20250719200145-20 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250719200012_20250719200145-20 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.6646
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721155944_20250721155949-2 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721155944_20250721155949-2 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.6205
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_25_2025 17_21_22.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/Genshin Impact 6_25_2025 17_21_22.png?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620181004_20250620181109-17 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250620181004_20250620181109-17 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.4169
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 1]-20250620170927_20250620171001-8 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 1]-20250620170927_20250620171001-8 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.0567
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721161505_20250721161613-6 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721161505_20250721161613-6 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.5137
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 2]-20250620172753_20250620172834-11 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 2]-20250620172753_20250620172834-11 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.6120
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 3]-20250621092136_20250621092228-15 images_0001.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 3]-20250621092136_20250621092228-15 images_0001.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7229
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 4]-20250620173912_20250620173953-12 images2.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 4]-20250620173912_20250620173953-12 images2.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.9447
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 5]-20250620174840_20250620174958-22 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 5]-20250620174840_20250620174958-22 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.9695
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/enka2.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/enka2.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.0582
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 1]-20250621091201_20250621091347-15 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 1]-20250621091201_20250621091347-15 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.0000
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721162702_20250721162730-6 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 0]-20250721162702_20250721162730-6 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7175
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/[Group 2]-20250620194440_20250620194618-25 images.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/[Group 2]-20250620194440_20250620194618-25 images.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 2.2462
        }
    ],
	hfw: [
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_0.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_0.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_1.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_1.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_10.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_10.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_102.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_102.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_103.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_103.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_11.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_11.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_101.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_101.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_12.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_14.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_15.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_15.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_16.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_16.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_18.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_18.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_19.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_19.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_17.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_17.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_2.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_2.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_13.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_13.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_21.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_21.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_100.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_100.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_22.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_22.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_23.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_23.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_24.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_24.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_25.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_25.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_26.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_26.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_29.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_29.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_3.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_3.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_32.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_32.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_30.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_30.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_33.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_33.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_34.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_34.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_35.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_35.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_36.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_36.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_38.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_38.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_37.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_37.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_39.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_39.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_4.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_4.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_40.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_40.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_42.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_43.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_43.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_46.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_46.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_47.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_47.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_49.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_49.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_48.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_48.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_5.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_5.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_50.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_50.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_51.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_51.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_53.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_53.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_52.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_52.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_55.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_55.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_57.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_57.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_56.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_56.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_59.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_59.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_6.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_6.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_60.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_60.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_61.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_61.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_54.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_54.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_63.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_63.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_64.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_64.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_66.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_66.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_65.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_65.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_67.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_67.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_68.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_68.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_69.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_69.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_7.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_7.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_70.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_70.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_71.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_71.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_72.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_72.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_73.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_73.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_75.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_75.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_74.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_74.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_76.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_76.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_77.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_77.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_78.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_78.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_8.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_8.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_80.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_80.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_79.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_79.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_81.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_81.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_82.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_82.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_83.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_83.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_84.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_84.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_85.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_85.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_87.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_87.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_88.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_88.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_89.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_89.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_90.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_90.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_9.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_9.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_91.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_91.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_92.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_92.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_94.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_94.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_96.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_96.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_95.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_95.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_97.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_97.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_98.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_98.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/hfw/2420110_99.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/hfw/2420110_99.jpg?enhanced&w=3840;2560;1920&format=jpg')).default,
            aspectRatio: 1.7778
        }
    ]
} as const;