/**
 * NOTE: This file is auto-generated by scripts/optimize_screenshots.ts
 * DO NOT modify manually
 */

import type { Picture } from 'vite-imagetools';
type ScreenshotGetter = () => Promise<Picture>;
type Screenshot = {
    thumbnail: ScreenshotGetter;
    full: ScreenshotGetter;
};
export type ScreenshotImageDictKey = 'acs' | 'genshin';
export const screenshotImageDict: Record<ScreenshotImageDictKey, Screenshot[]> = {
	acs: [
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_03_31_19_40_12.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_03_31_19_40_12.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_03_31_20_03_35.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_03_31_20_03_35.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_09_55_07.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_09_55_07.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_05_42.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_05_42.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_09_27.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_09_27.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_27_11_10_14.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_27_11_10_14.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_01_58.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_01_58.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_02_25.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_02_25.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_04_28_19_32_10.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_04_28_19_32_10.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_3_20_25_48.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_3_20_25_48.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_3_20_28_15.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_3_20_28_15.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_09_59_50.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_09_59_50.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_01_54.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_01_54.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_21_59.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_21_59.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_25_05.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_25_05.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/acs/2025_05_4_10_27_28.jpg?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/acs/2025_05_4_10_27_28.jpg?enhanced&w=2160;1440;1080&format=jpg')).default
        }
    ],
	genshin: [
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250331173924.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250331173924.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250331174034.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250331174034.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250402194916.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250402194916.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250404201855.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250404201855.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250404202717.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250404202717.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412085023.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412085023.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412100914.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412100914.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412104814.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412104814.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412204538.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412204538.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412205345.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412205345.png?enhanced&w=2160;1440;1080&format=jpg')).default
        },
		{
            thumbnail: async () => (await import('../assets/screenshots/genshin/20250412205940.png?enhanced&w=540;360&format=webp')).default,
            full: async () => (await import('../assets/screenshots/genshin/20250412205940.png?enhanced&w=2160;1440;1080&format=jpg')).default
        }
    ]
} as const;