name: Fetch Genshin Profile

on:
  schedule:
    - cron: '59 23 * * 1'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      - name: Genshin Fetch
        id: genshin
        uses: quantum-pi/Action-GenshinAPI@v3.0.4
        with:
          uuid: 605452914
          usage: 'QuantumPie.net Genshin profile display'
          outputDir: 'data/'
      - name: Write Output
        run: |
          pnpm update enka-network-api
          pnpm format:data
          pnpm run prefetch
          pnpm run aggregate

          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add pnpm-lock.yaml
          git add data/genshin_raw.ts
          git add src/assets/games/
          git add src/assets/profile_pictures/
          git commit -m "Update profile info"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push

      - name: Build site
        run: pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from main,
        # also change the `main` in `refs/heads/main`
        # below accordingly.
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
